'hist_STTH1L3BHct.root':
  type: signal
  pretty-name: 'STTH1L3BHct'
  cross-section: 0.076
  generated-events: 3185542 #3902188
  line-color: '#006666'
  legend: 'STHct'
  order: 1

#'hist_TTTH1L3BHct.root':
#  type: signal
#  pretty-name: 'TTTH1L3BHct'
#  cross-section: 1.86
#  generated-events: 1373754 #1723976
#  line-color: '#0000cc'
#  legend: 'TTHct'
#  order: 2

'hist_TTTH1L3BaTLepHct.root':
  type: signal
  pretty-name: 'TTTH1L3BTLepHct'
  cross-section: 0.93
  generated-events: 668890
  line-color: '#0000cc'
  legend: 'TTHct'
  order: 2

'hist_TTTH1L3BaTLepHct.root':
  type: signal
  pretty-name: 'TTTH1L3BaTLepHct'
  cross-section: 0.93
  generated-events: 704864
  line-color: '#0000cc'
  legend: 'TTHct'
  order: 2

'hist_STTH1L3BHut.root':
  type: signal
  pretty-name: 'STTH1L3BHut'
  cross-section: 0.55
  generated-events: 3245588 #3949974
  line-color: '#666600'
  legend: 'STHut'
  order: 3

#'hist_TTTH1L3BHut.root':
#  type: signal
#  pretty-name: 'TTTH1L3BHut'
#  cross-section: 1.86
#  generated-events: 1524358 #1932536
#  line-color: '#cccc00'
#  legend: 'TTHut'
#  order: 4

'hist_TTTH1L3BaTLepHut.root':
  type: signal
  pretty-name: 'TTTH1L3BaTLepHut'
  cross-section: 0.93
  generated-events: 790161
  line-color: '#cccc00'
  legend: 'TTHut'
  order: 4

'hist_TTTH1L3BTLepHut.root':
  type: signal
  pretty-name: 'TTTH1L3BTLepHut'
  cross-section: 0.93
  generated-events: 734197
  line-color: '#cccc00'
  legend: 'TTHut'
  order: 4

'hist_SingleMuonRun2017.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  group: GData

'hist_SingleElectronRun2017.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  group: GData

'hist_TTpowhegttbb.root':
  type: mc
  pretty-name: 'TTpowhegttbb'
  cross-section: 365.34
  generated-events: 104564754 #109194238
  fill-color: "#330000"
  legend: "ttbb"
  yields-group: '0\ttbar\bbbar'
  order: 0

'hist_TTpowhegttbj.root':
  type: mc
  pretty-name: 'TTpowhegttbj'
  cross-section: 365.34
  generated-events: 104564754 #109194238
  fill-color: '#660000'
  legend: 'ttbj'
  yields-group: '1\ttbar bj'
  order: 1

'hist_TTpowhegttcc.root':
  type: mc
  pretty-name: 'TTpowhegttcc'
  cross-section: 365.34
  generated-events: 104564754 #109194238
  fill-color: '#990000'
  legend: 'ttcc'
  yields-group: '2\ttbar\ccbar'
  order: 2

'hist_TTpowhegttlf.root':
  type: mc
  pretty-name: 'TTpowhegttlf'
  cross-section: 365.34
  generated-events: 104564754 #109194238
  fill-color: '#cc0000'
  legend: 'ttLF'
  yields-group: '3\ttbar LF'
  order: 3

'hist_TTpowhegttother.root':
  type: mc
  pretty-name: 'TTpowhegttother'
  cross-section: 365.34
  generated-events: 104564754 #109194238
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 4

'hist_TTHadpowheg.root':
  type: mc
  pretty-name: 'TTHadpowheg'
  cross-section: 377.96
  generated-events: 129211204
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 5

'hist_TTLLpowheg.root':
  type: mc
  pretty-name: 'TTLLpowheg'
  cross-section: 88.29
  generated-events: 65393700 #68595608
  fill-color: '#ff6666'
  legend: 'ttBkg'
  group: GttBkg
  yields-group: '4\ttbar Bkg'
  order: 6

'hist_ttHTobb.root':
  type: mc
  pretty-name: 'ttHTobb'
  cross-section: 0.2934
  generated-events: 7833734
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 7

'hist_ttHToNonbb.root':
  type: mc
  pretty-name: 'ttHToNonbb'
  cross-section: 0.2151
  generated-events: 7814711
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 8

'hist_TTWJetsToLNuPSweight.root':
  type: mc
  pretty-name: 'TTWJetsToLNuPSweight'
  cross-section: 0.2043 
  generated-events: 2686141
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 9

'hist_TTWJetsToQQ.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  generated-events: 441560
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 10

'hist_TTZToLLNuNu.root':
  type: mc
  pretty-name: 'TTZToLLNuNu'
  cross-section: 0.2529
  generated-events: 3570720
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 11

'hist_TTZToQQ.root':
  type: mc
  pretty-name: 'TTZToQQ'
  cross-section: 0.5297
  generated-events: 356286
  fill-color: '#ff66ff'
  legend: 'ttV'
  group: GttV
  yields-group: '5Other'
  order: 12

'hist_W1JetsToLNu.root':
  type: mc
  pretty-name: 'W1JetsToLNu'
  cross-section: 9625
  generated-events: 54106926
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 23

'hist_W2JetsToLNu.root':
  type: mc
  pretty-name: 'W2JetsToLNu'
  cross-section: 2793
  generated-events: 6570442
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 24

'hist_W3JetsToLNu.root':
  type: mc
  pretty-name: 'W3JetsToLNu'
  cross-section: 992.5
  generated-events: 19669693
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 25

'hist_W4JetsToLNu.root':
  type: mc
  pretty-name: 'W4JetsToLNu'
  cross-section: 544.3
  generated-events: 11074019
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '5Other'
  order: 26

'hist_DYJets.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 6225.42
  generated-events: 123485957
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
  yields-group: '5Other'
  order: 21

'hist_DYJets10to50.root':
  type: mc
  pretty-name: 'DYJets10to50'
  cross-section: 18610
  generated-events: 39489654
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
  yields-group: '5Other'
  order: 22

'hist_SingleTops.root':
  type: mc
  pretty-name: 'SingleTops'
  cross-section: 3.36
  generated-events: 6185062
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 13

'hist_SingleTopt.root':
  type: mc
  pretty-name: 'SingleTopt'
  cross-section: 136.02
  generated-events: 5982064
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 14

'hist_SingleTbart.root':
  type: mc
  pretty-name: 'SingleTbart'
  cross-section: 80.95
  generated-events: 3675910
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 15

'hist_SingleToptW.root':
  type: mc
  pretty-name: 'SingleToptW'
  cross-section: 35.85
  generated-events: 7884388
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 16

'hist_SingleTbartW.root':
  type: mc
  pretty-name: 'SingleTbartW'
  cross-section: 35.85
  generated-events: 7686032
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '5Other'
  order: 17

'hist_WW.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 118.7
  generated-events: 7791498
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '5Other'
  order: 18

'hist_WZ.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 47.13
  generated-events: 3928630
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '5Other'
  order: 19

'hist_ZZ.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 16.523
  generated-events: 1949768
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '5Other'
  order: 20
