#Ch0
'h_FCNHkinLepTopM_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

#Ch1
'h_FCNHkinLepTopM_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

#Ch2
'h_FCNHkinLepTopM_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadWMass_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_FCNHkinHadTopM_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
