'h_DNN_Ch0':
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true

'h_DNN_Ch1':
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true

'h_DNN_Ch2':
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true
