'hist_STTH1L3BHct.root':
  type: signal
  pretty-name: 'STTH1L3BHct'
  cross-section: 0.076
  generated-events: 3099824
  line-color: '#006666'
  legend: 'STHct'
  group: GSTHct
  order: 1

'hist_TTTH1L3BHct.root':
  type: signal
  pretty-name: 'TTTH1L3BHct'
  cross-section: 1.86
  generated-events: 988758
  line-color: '#0000cc'
  legend: 'TTHct'
  group: GTTHct
  order: 2

#'hist_TTTH1L3BaTLepHct.root':
#  type: signal
#  pretty-name: 'TTTH1L3BaTLepHct'
#  cross-section: 0.93
#  generated-events: 688297
#  line-color: '#0000cc'
#  legend: 'TTHct'
#  group: GTTHct
#  order: 2
#
#'hist_TTTH1L3BTLepHct.root':
#  type: signal
#  pretty-name: 'TTTH1L3BTLepHct'
#  cross-section: 0.93
#  generated-events: 300461
#  line-color: '#0000cc'
#  legend: 'TTHct'
#  group: GTTHct
#  order: 2

'hist_STTH1L3BHut.root':
  type: signal
  pretty-name: 'STTH1L3BHut'
  cross-section: 0.55
  generated-events: 2598940
  line-color: '#666600'
  legend: 'STHut'
  group: GSTHut
  order: 3

'hist_TTTH1L3BHut.root':
  type: signal
  pretty-name: 'TTTH1L3BHut'
  cross-section: 1.86
  generated-events: 1586324
  line-color: '#cccc00'
  legend: 'TTHut'
  group: GTTHut
  order: 4

#'hist_TTTH1L3BaTLepHut.root':
#  type: signal
#  pretty-name: 'TTTH1L3BaTLepHut'
#  cross-section: 0.93
#  generated-events: 796066
#  line-color: '#cccc00'
#  legend: 'TTHut'
#  group: GTTHut
#  order: 4
#
#'hist_TTTH1L3BTLepHut.root':
#  type: signal
#  pretty-name: 'TTTH1L3BTLepHut'
#  cross-section: 0.93
#  generated-events: 790258
#  line-color: '#cccc00'
#  legend: 'TTHut'
#  group: GTTHut
#  order: 4

'hist_SingleMuonRun2017.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  group: GData

'hist_SingleElectronRun2017.root':
  type: data
  legend: 'Data'
  pretty-name: 'Data'
  group: GData

'hist_TTpowhegttbb.root':
  type: mc
  pretty-name: 'TTpowhegttbb'
  cross-section: 365.34
  generated-events: 99226336
  fill-color: "#330000"
  legend: "ttbb"
  group: Gttbb
  yields-group: '0\ttbar\bbbar'
  order: 0

'hist_TTLLpowhegttbb.root':
  type: mc
  pretty-name: 'TTLLpowhegttbb'
  cross-section: 88.29
  generated-events: 60757798
  fill-color: "#330000"
  legend: "ttbb"
  group: Gttbb
  yields-group: '0\ttbar\bbbar'
  order: 1

'hist_TTHadpowhegttbb.root':
  type: mc
  pretty-name: 'TTHadpowhegttbb'
  cross-section: 377.96
  generated-events: 129211204
  fill-color: "#330000"
  legend: "ttbb"
  group: Gttbb
  yields-group: '0\ttbar\bbbar'
  order: 2

'hist_TTpowhegttcc.root':
  type: mc
  pretty-name: 'TTpowhegttcc'
  cross-section: 365.34
  generated-events: 99226336
  fill-color: '#990000'
  legend: 'ttcc'
  group: Gttcc
  yields-group: '1\ttbar\ccbar'
  order: 3

'hist_TTLLpowhegttcc.root':
  type: mc
  pretty-name: 'TTLLpowhegttcc'
  cross-section: 88.29
  generated-events: 60757798
  fill-color: '#990000'
  legend: 'ttcc'
  group: Gttcc
  yields-group: '1\ttbar\ccbar'
  order: 4

'hist_TTHadpowhegttcc.root':
  type: mc
  pretty-name: 'TTHadpowhegttcc'
  cross-section: 377.96
  generated-events: 129211204
  fill-color: '#990000'
  legend: 'ttcc'
  group: Gttcc
  yields-group: '1\ttbar\ccbar'
  order: 5

'hist_TTpowhegttlf.root':
  type: mc
  pretty-name: 'TTpowhegttlf'
  cross-section: 365.34
  generated-events: 99226336
  fill-color: '#cc0000'
  legend: 'ttLF'
  group: Gttlf
  yields-group: '2\ttbar LF'
  order: 6

'hist_TTLLpowhegttlf.root':
  type: mc
  pretty-name: 'TTLLpowhegttlf'
  cross-section: 88.29
  generated-events: 60757798
  fill-color: '#cc0000'
  legend: 'ttLF'
  group: Gttlf
  yields-group: '2\ttbar LF'
  order: 7

'hist_TTHadpowhegttlf.root':
  type: mc
  pretty-name: 'TTHadpowhegttlf'
  cross-section: 377.96
  generated-events: 129211204
  fill-color: '#cc0000'
  legend: 'ttLF'
  group: Gttlf
  yields-group: '2\ttbar LF'
  order: 8

'hist_ttHTobb.root':
  type: mc
  pretty-name: 'ttHTobb'
  cross-section: 0.2934
  generated-events: 7833734
  fill-color: '#ff66ff'
  legend: 'ttV/H'
  group: GttV
  yields-group: '3Other'
  order: 9

'hist_ttHToNonbb.root':
  type: mc
  pretty-name: 'ttHToNonbb'
  cross-section: 0.2151
  generated-events: 7814711
  fill-color: '#ff66ff'
  legend: 'ttV/H'
  group: GttV
  yields-group: '3Other'
  order: 10

'hist_TTWJetsToLNu.root':
  type: mc
  pretty-name: 'TTWJetsToLNu'
  cross-section: 0.2043
  generated-events: 2686141
  fill-color: '#ff66ff'
  legend: 'ttV/H'
  group: GttV
  yields-group: '3Other'
  order: 11

'hist_TTWJetsToQQ.root':
  type: mc
  pretty-name: 'TTWJetsToQQ'
  cross-section: 0.4062
  generated-events: 441560
  fill-color: '#ff66ff'
  legend: 'ttV/H'
  group: GttV
  yields-group: '3Other'
  order: 12

'hist_TTZToLLNuNu.root':
  type: mc
  pretty-name: 'TTZToLLNuNu'
  cross-section: 0.2529
  generated-events: 3570720
  fill-color: '#ff66ff'
  legend: 'ttV/H'
  group: GttV
  yields-group: '3Other'
  order: 13

'hist_TTZToQQ.root':
  type: mc
  pretty-name: 'TTZToQQ'
  cross-section: 0.5297
  generated-events: 356286
  fill-color: '#ff66ff'
  legend: 'ttV/H'
  group: GttV
  yields-group: '3Other'
  order: 14

'hist_W1JetsToLNu.root':
  type: mc
  pretty-name: 'W1JetsToLNu'
  cross-section: 9625
  generated-events: 54106926
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '3Other'
  order: 25

'hist_W2JetsToLNu.root':
  type: mc
  pretty-name: 'W2JetsToLNu'
  cross-section: 2793
  generated-events: 6570442
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '3Other'
  order: 26

'hist_W3JetsToLNu.root':
  type: mc
  pretty-name: 'W3JetsToLNu'
  cross-section: 992.5
  generated-events: 19669693
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '3Other'
  order: 27

'hist_W4JetsToLNu.root':
  type: mc
  pretty-name: 'W4JetsToLNu'
  cross-section: 544.3
  generated-events: 11074019
  fill-color: '#ff9933'
  legend: 'WJets'
  group: GWJets
  yields-group: '3Other'
  order: 28

'hist_DYJets.root':
  type: mc
  pretty-name: 'DYJets'
  cross-section: 6225.42
  generated-events: 123485957
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
  yields-group: '3Other'
  order: 23

'hist_DYJets10to50.root':
  type: mc
  pretty-name: 'DYJets10to50'
  cross-section: 18610
  generated-events: 39489654
  fill-color: '#000099'
  legend: 'ZJets'
  group: GZJets
  yields-group: '3Other'
  order: 24

'hist_SingleTops.root':
  type: mc
  pretty-name: 'SingleTops'
  cross-section: 3.36
  generated-events: 6185062
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '3Other'
  order: 15

'hist_SingleTopt.root':
  type: mc
  pretty-name: 'SingleTopt'
  cross-section: 136.02
  generated-events: 5982064
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '3Other'
  order: 16

'hist_SingleTbart.root':
  type: mc
  pretty-name: 'SingleTbart'
  cross-section: 80.95
  generated-events: 3675910
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '3Other'
  order: 17

'hist_SingleToptW.root':
  type: mc
  pretty-name: 'SingleToptW'
  cross-section: 35.85
  generated-events: 7884388
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '3Other'
  order: 18

'hist_SingleTbartW.root':
  type: mc
  pretty-name: 'SingleTbartW'
  cross-section: 35.85
  generated-events: 7686032
  fill-color: '#990099'
  legend: 'SingleT'
  group: GSingleT
  yields-group: '3Other'
  order: 19

'hist_WW.root':
  type: mc
  pretty-name: 'WW'
  cross-section: 118.7
  generated-events: 7791498
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '3Other'
  order: 20

'hist_WZ.root':
  type: mc
  pretty-name: 'WZ'
  cross-section: 47.13
  generated-events: 3928630
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '3Other'
  order: 21

'hist_ZZ.root':
  type: mc
  pretty-name: 'ZZ'
  cross-section: 16.523
  generated-events: 1949768
  fill-color: '#00cccc'
  legend: 'VV'
  group: GVV
  yields-group: '3Other'
  order: 22

