GData:
  legend: 'Data'
  marker-size: 0.6

Gttbb:
  fill-color: '#330000'
  legend: 'ttbb'

Gttcc:
  fill-color: '#990000'
  legend: 'ttcc'

Gttlf:
  fill-color: '#cc0000'
  legend: 'ttlf'

GttV:
  fill-color: '#ff66ff'
  legend: 'ttV/H'

GZJets:
  fill-color: '#000099'
  legend: 'ZJets'

GWJets:
  fill-color: '#ff9933'
  legend: 'WJets'

GSingleT:
  fill-color: '#990099'
  legend: 'SingleT'

GVV:
  fill-color: '#00cccc'
  legend: 'VV'

GQCD:
  fill-color: '#d0cfd4'
  legend: 'QCD'

GSTHct:
  line-color: '#006666'
  legend: 'STHct'

GSTHut:
  line-color: '#666600'
  legend: 'STHut'

GTTHct:
  line-color: '#0000cc'
  legend: 'TTHct'

GTTHut:
  line-color: '#cccc00'
  legend: 'TTHut'
