'h_JetCSVnoSF_Ch0_S4':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_JetCSVnoSF_Ch1_S4':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']

'h_JetCSVnoSF_Ch2_S4':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
