###############
#For systematic
###############
'h_DNN_j3b2_Ch2':
  x-axis: "BDT Score"
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 0
  yields-title: '$b2j3$'
  rebin: 2
  labels:
    - {text: 'b2j3', position: [0.778, 0.82], size: 18}
#  signal-normalize-data: false

'h_DNN_j3b3_Ch2':
  x-axis: "BDT Score"
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 2
  yields-title: '$j3b3$'
  rebin: 2
  labels:
    - {text: 'b3j3', position: [0.778, 0.82], size: 18}
#  signal-normalize-data: false

'h_DNN_j4b2_Ch2':
  x-axis: "BDT Score"
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 1
  yields-title: '$b2j4$'
  rebin: 2
  labels:
    - {text: 'b2j4', position: [0.778, 0.82], size: 18}
#  signal-normalize-data: false

'h_DNN_j4b3_Ch2':
  x-axis: "BDT Score"
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 3
  yields-title: '$b3j4$'
  rebin: 2
  labels:
    - {text: 'b3j4', position: [0.778, 0.82], size: 18}
#  signal-normalize-data: false

'h_DNN_j4b4_Ch2':
  x-axis: "BDT Score"
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 4
  yields-title: '$b4j4$'
  rebin: 2
  labels:
    - {text: 'b4j4', position: [0.778, 0.82], size: 18}
#  signal-normalize-data: false

####################
#Final distributions
####################
#'h_DNN_j3b2_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j3b2_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j3b2_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 0
#
#'h_DNN_j3b3_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j3b3_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j3b3_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 1
#
#'h_DNN_j4b2_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j4b2_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j4b2_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 2
#
#'h_DNN_j4b3_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j4b3_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j4b3_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 3
#
#'h_DNN_j4b4_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j4b4_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_j4b4_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 4
#  #rebin: 2

###########
#Old histos
###########
#'h_DNN_b2_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_b2_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_b2_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 0
#
#'h_DNN_b3_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_b3_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_b3_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 1
#
#'h_DNN_b4_Ch0':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_b4_Ch1':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#
#'h_DNN_b4_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 2
#  #rebin: 2


#'h_DNN_Ch2':
#  y-axis: "Entries"
#  y-axis-format: "%1% / %2$.2f"
#  save-extensions: ['pdf']
#  for-yields: true
#  yields-table-order: 0
#  blinded-range: [0.7,1]
