// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Mon May 22 14:15:44 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva
Training events: 100000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,16]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,7]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,9]
BJMDPhi                       BJMDPhi                       BJMDPhi                       BJMDPhi                                                         'F'    [-3.1415681839,3.14156198502]
BJMDEta                       BJMDEta                       BJMDEta                       BJMDEta                                                         'F'    [-4.75499534607,4.75167274475]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJMDPhi", "BJMDEta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.683036177788296;
   fWeightMatrix0to1[1][0] = 0.539662514301262;
   fWeightMatrix0to1[2][0] = 0.750329658456426;
   fWeightMatrix0to1[3][0] = 3.94364831362861;
   fWeightMatrix0to1[4][0] = -9.20681598719154;
   fWeightMatrix0to1[5][0] = -0.788149186431013;
   fWeightMatrix0to1[6][0] = -0.366992390262117;
   fWeightMatrix0to1[7][0] = 1.04555468636877;
   fWeightMatrix0to1[8][0] = -0.106815244042926;
   fWeightMatrix0to1[9][0] = -0.110277401518972;
   fWeightMatrix0to1[0][1] = -1.41943081691635;
   fWeightMatrix0to1[1][1] = -2.24373810325441;
   fWeightMatrix0to1[2][1] = 4.41082560812975;
   fWeightMatrix0to1[3][1] = 0.602365540376212;
   fWeightMatrix0to1[4][1] = 0.248189779653978;
   fWeightMatrix0to1[5][1] = 0.372700465524906;
   fWeightMatrix0to1[6][1] = 0.341471262145732;
   fWeightMatrix0to1[7][1] = 2.64388948683827;
   fWeightMatrix0to1[8][1] = 0.878382835449704;
   fWeightMatrix0to1[9][1] = 10.4345486284894;
   fWeightMatrix0to1[0][2] = -3.18529691460012;
   fWeightMatrix0to1[1][2] = 0.43638152429878;
   fWeightMatrix0to1[2][2] = 1.08977835359446;
   fWeightMatrix0to1[3][2] = 0.928220657525576;
   fWeightMatrix0to1[4][2] = 1.22043617643714;
   fWeightMatrix0to1[5][2] = 0.576748771917743;
   fWeightMatrix0to1[6][2] = -0.220202709474363;
   fWeightMatrix0to1[7][2] = -0.345471393544368;
   fWeightMatrix0to1[8][2] = -0.813976876428497;
   fWeightMatrix0to1[9][2] = -0.183521078684914;
   fWeightMatrix0to1[0][3] = 0.151633040877604;
   fWeightMatrix0to1[1][3] = 0.596327498208091;
   fWeightMatrix0to1[2][3] = -0.0855975124020171;
   fWeightMatrix0to1[3][3] = 0.12762228293973;
   fWeightMatrix0to1[4][3] = 0.0317274880083088;
   fWeightMatrix0to1[5][3] = -0.0269111635519394;
   fWeightMatrix0to1[6][3] = 0.204058461623489;
   fWeightMatrix0to1[7][3] = 0.180931424711687;
   fWeightMatrix0to1[8][3] = 0.378061639419001;
   fWeightMatrix0to1[9][3] = 0.0130934990083316;
   fWeightMatrix0to1[0][4] = 1.15003644008841;
   fWeightMatrix0to1[1][4] = 0.0804416219658181;
   fWeightMatrix0to1[2][4] = 1.77664766245856;
   fWeightMatrix0to1[3][4] = 0.865665925985189;
   fWeightMatrix0to1[4][4] = -1.35507025300256;
   fWeightMatrix0to1[5][4] = -2.62362327740345;
   fWeightMatrix0to1[6][4] = -0.0510903485753549;
   fWeightMatrix0to1[7][4] = 1.4486378401176;
   fWeightMatrix0to1[8][4] = 0.194668269166395;
   fWeightMatrix0to1[9][4] = 2.08167292887397;
   fWeightMatrix0to1[0][5] = 2.12010274683503;
   fWeightMatrix0to1[1][5] = -0.117187295867183;
   fWeightMatrix0to1[2][5] = 1.49183645336723;
   fWeightMatrix0to1[3][5] = 3.61593414484813;
   fWeightMatrix0to1[4][5] = -8.19230420875491;
   fWeightMatrix0to1[5][5] = -1.52945452991023;
   fWeightMatrix0to1[6][5] = -0.286486859428248;
   fWeightMatrix0to1[7][5] = -1.63786492884032;
   fWeightMatrix0to1[8][5] = -0.235232459506019;
   fWeightMatrix0to1[9][5] = 8.40776099584176;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.81653676956069;
   fWeightMatrix1to2[0][1] = -0.375713691091919;
   fWeightMatrix1to2[0][2] = -0.814885712480911;
   fWeightMatrix1to2[0][3] = -0.64361446526608;
   fWeightMatrix1to2[0][4] = 0.680760217814877;
   fWeightMatrix1to2[0][5] = -1.44671887026792;
   fWeightMatrix1to2[0][6] = 0.22749848306346;
   fWeightMatrix1to2[0][7] = -1.59915648347007;
   fWeightMatrix1to2[0][8] = 0.385349054001831;
   fWeightMatrix1to2[0][9] = -0.995655359923163;
   fWeightMatrix1to2[0][10] = -0.270458702565001;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 14;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 16;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 16;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 7;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 7;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 8;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 9;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 9;
   fMin_1[0][3] = -3.14155840874;
   fMax_1[0][3] = 3.1413962841;
   fMin_1[1][3] = -3.1415681839;
   fMax_1[1][3] = 3.14156198502;
   fMin_1[2][3] = -3.1415681839;
   fMax_1[2][3] = 3.14156198502;
   fMin_1[0][4] = -4.70970201492;
   fMax_1[0][4] = 4.74954795837;
   fMin_1[1][4] = -4.75499534607;
   fMax_1[1][4] = 4.75167274475;
   fMin_1[2][4] = -4.75499534607;
   fMax_1[2][4] = 4.75167274475;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
