// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Tue May 23 01:50:15 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,16]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,7]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,9]
BJMDPhi                       BJMDPhi                       BJMDPhi                       BJMDPhi                                                         'F'    [-3.14155578613,3.14156198502]
BJMDEta                       BJMDEta                       BJMDEta                       BJMDEta                                                         'F'    [-4.67494106293,4.74954795837]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJMDPhi", "BJMDEta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.58418487052735;
   fWeightMatrix0to1[1][0] = 1.08932847289793;
   fWeightMatrix0to1[2][0] = 0.428936655012191;
   fWeightMatrix0to1[3][0] = 3.77638055948531;
   fWeightMatrix0to1[4][0] = -8.06076468448743;
   fWeightMatrix0to1[5][0] = -0.595093497799679;
   fWeightMatrix0to1[6][0] = -0.850863328423118;
   fWeightMatrix0to1[7][0] = 1.44663487647078;
   fWeightMatrix0to1[8][0] = 0.21207907191625;
   fWeightMatrix0to1[9][0] = -0.52658120199975;
   fWeightMatrix0to1[0][1] = -1.11830893045749;
   fWeightMatrix0to1[1][1] = -1.9150627074695;
   fWeightMatrix0to1[2][1] = 4.26818049266186;
   fWeightMatrix0to1[3][1] = 0.359995134359556;
   fWeightMatrix0to1[4][1] = 0.291042019584214;
   fWeightMatrix0to1[5][1] = 0.183092033666795;
   fWeightMatrix0to1[6][1] = 0.259027489598673;
   fWeightMatrix0to1[7][1] = 2.62191791694733;
   fWeightMatrix0to1[8][1] = 0.407871328876661;
   fWeightMatrix0to1[9][1] = 9.49049847810996;
   fWeightMatrix0to1[0][2] = -2.74253604463992;
   fWeightMatrix0to1[1][2] = -0.189400799932811;
   fWeightMatrix0to1[2][2] = 1.30229915116094;
   fWeightMatrix0to1[3][2] = 1.29212368538702;
   fWeightMatrix0to1[4][2] = 1.27548923596057;
   fWeightMatrix0to1[5][2] = 0.545040358562185;
   fWeightMatrix0to1[6][2] = -0.372043962144306;
   fWeightMatrix0to1[7][2] = -0.443826804838369;
   fWeightMatrix0to1[8][2] = -0.506750846435945;
   fWeightMatrix0to1[9][2] = 0.272530647275911;
   fWeightMatrix0to1[0][3] = 0.495577566776004;
   fWeightMatrix0to1[1][3] = 0.744964167732888;
   fWeightMatrix0to1[2][3] = -0.13779945070997;
   fWeightMatrix0to1[3][3] = 0.256987418537847;
   fWeightMatrix0to1[4][3] = 0.028667330798397;
   fWeightMatrix0to1[5][3] = -0.1499969684933;
   fWeightMatrix0to1[6][3] = -0.0431499944416072;
   fWeightMatrix0to1[7][3] = 0.73681296053063;
   fWeightMatrix0to1[8][3] = 0.768966406088097;
   fWeightMatrix0to1[9][3] = 0.085734233984053;
   fWeightMatrix0to1[0][4] = 1.55269906729072;
   fWeightMatrix0to1[1][4] = 1.23873567602006;
   fWeightMatrix0to1[2][4] = 1.49592385750051;
   fWeightMatrix0to1[3][4] = 0.592617609055808;
   fWeightMatrix0to1[4][4] = -1.07838979638059;
   fWeightMatrix0to1[5][4] = -2.44697831283906;
   fWeightMatrix0to1[6][4] = 0.145051164955824;
   fWeightMatrix0to1[7][4] = 0.482064365434158;
   fWeightMatrix0to1[8][4] = -0.0957583520458882;
   fWeightMatrix0to1[9][4] = 2.13530027628797;
   fWeightMatrix0to1[0][5] = 2.03987519099329;
   fWeightMatrix0to1[1][5] = 0.0700837876489;
   fWeightMatrix0to1[2][5] = 1.3763951944922;
   fWeightMatrix0to1[3][5] = 3.56602614171269;
   fWeightMatrix0to1[4][5] = -7.02403905312658;
   fWeightMatrix0to1[5][5] = -1.46148317180116;
   fWeightMatrix0to1[6][5] = -0.705776605996008;
   fWeightMatrix0to1[7][5] = -2.52539078065861;
   fWeightMatrix0to1[8][5] = -0.317900842755241;
   fWeightMatrix0to1[9][5] = 7.74101128951558;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -1.86035498872786;
   fWeightMatrix1to2[0][1] = -0.426253091082834;
   fWeightMatrix1to2[0][2] = -0.846729224485344;
   fWeightMatrix1to2[0][3] = -0.560446414695918;
   fWeightMatrix1to2[0][4] = 0.689660495887889;
   fWeightMatrix1to2[0][5] = -1.7118003093253;
   fWeightMatrix1to2[0][6] = 0.39462671880004;
   fWeightMatrix1to2[0][7] = -1.39068307380499;
   fWeightMatrix1to2[0][8] = 0.385071636609334;
   fWeightMatrix1to2[0][9] = -1.06707267511064;
   fWeightMatrix1to2[0][10] = -0.15268831769919;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 14;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 16;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 16;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 7;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 8;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 9;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 9;
   fMin_1[0][3] = -3.14139795303;
   fMax_1[0][3] = 3.14126086235;
   fMin_1[1][3] = -3.14155578613;
   fMax_1[1][3] = 3.14156198502;
   fMin_1[2][3] = -3.14155578613;
   fMax_1[2][3] = 3.14156198502;
   fMin_1[0][4] = -4.66926717758;
   fMax_1[0][4] = 4.74954795837;
   fMin_1[1][4] = -4.67494106293;
   fMax_1[1][4] = 4.59502410889;
   fMin_1[2][4] = -4.67494106293;
   fMax_1[2][4] = 4.74954795837;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
