// Class: ReadDNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : DNN::DNN
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Thu May 25 01:36:16 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva/v2
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|30,TANH|20,LINEAR" [Layou of the network.]
ErrorStrategy: "CROSSENTROPY" [Loss function: Mean squared error (regression) or cross entropy (binary classifcation).]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
TrainingStrategy: "LearningRate=0.01,Momentum=0.4,Repetitions=1,ConvergenceSteps=300,BatchSize=100,DropConfig=0.0+0.2+0.0,WeightDecay=0.001,Regularization=L2,TestRepetitions=5,Multithreading=True" [Defines the training strategies.]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Architecture: "STANDARD" [Which architecture to perfrom the training on.]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.388728410006,5.07587337494]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [17.1672954559,299.998291016]
BJet_Pt                       BJet_Pt                       BJet_Pt                       BJet_Pt                                                         'F'    [30.2424373627,299.903961182]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [30.2424373627,299.974487305]
Jet1_Pt                       Jet1_Pt                       Jet1_Pt                       Jet1_Pt                                                         'F'    [33.4113769531,299.983215332]
Jet2_Pt                       Jet2_Pt                       Jet2_Pt                       Jet2_Pt                                                         'F'    [30.5687541962,295.347045898]
Jet3_Pt                       Jet3_Pt                       Jet3_Pt                       Jet3_Pt                                                         'F'    [30.1238079071,255.206192017]
Jet4_Pt                       Jet4_Pt                       Jet4_Pt                       Jet4_Pt                                                         'F'    [30.0002975464,226.160202026]
Jet1_CSV                      Jet1_CSV                      Jet1_CSV                      Jet1_CSV                                                        'F'    [0.0351784825325,0.999569296837]
Jet2_CSV                      Jet2_CSV                      Jet2_CSV                      Jet2_CSV                                                        'F'    [0.0351793691516,1]
Jet3_CSV                      Jet3_CSV                      Jet3_CSV                      Jet3_CSV                                                        'F'    [0.0378077812493,0.999603509903]
Jet4_CSV                      Jet4_CSV                      Jet4_CSV                      Jet4_CSV                                                        'F'    [0.0345279611647,0.999591112137]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDNN : public IClassifierReader {

 public:

   // constructor
   ReadDNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadDNN" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "BJet_M_delta_R", "H_Mass", "BJet_Pt", "CJet_Pt", "Jet1_Pt", "Jet2_Pt", "Jet3_Pt", "Jet4_Pt", "Jet1_CSV", "Jet2_CSV", "Jet3_CSV", "Jet4_CSV" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -0.994405686855316;
      fVmax[0] = 0.896208643913269;
      fVmin[1] = -0.992152988910675;
      fVmax[1] = 0.998837113380432;
      fVmin[2] = -0.996359765529633;
      fVmax[2] = 0.997182130813599;
      fVmin[3] = -1.00100898742676;
      fVmax[3] = 0.999011993408203;
      fVmin[4] = -0.994469106197357;
      fVmax[4] = 0.999414086341858;
      fVmin[5] = -0.99521392583847;
      fVmax[5] = 0.912160754203796;
      fVmin[6] = -0.995741605758667;
      fVmax[6] = 1.03927063941956;
      fVmin[7] = -0.999961674213409;
      fVmax[7] = 0.665053248405457;
      fVmin[8] = -0.979029357433319;
      fVmax[8] = 0.999773383140564;
      fVmin[9] = -0.997335493564606;
      fVmax[9] = 1;
      fVmin[10] = -0.993135273456573;
      fVmax[10] = 0.999950289726257;
      fVmin[11] = -0.97423642873764;
      fVmax[11] = 1.00006580352783;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][12];
   double fMax_1[3][12];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadDNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadDNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.388728410006;
   fMax_1[0][0] = 4.64633131027;
   fMin_1[1][0] = 0.399107426405;
   fMax_1[1][0] = 5.07587337494;
   fMin_1[2][0] = 0.388728410006;
   fMax_1[2][0] = 5.07587337494;
   fMin_1[0][1] = 17.1672954559;
   fMax_1[0][1] = 299.889923096;
   fMin_1[1][1] = 17.3422145844;
   fMax_1[1][1] = 299.998291016;
   fMin_1[2][1] = 17.1672954559;
   fMax_1[2][1] = 299.998291016;
   fMin_1[0][2] = 30.2424373627;
   fMax_1[0][2] = 299.180145264;
   fMin_1[1][2] = 30.4866390228;
   fMax_1[1][2] = 299.903961182;
   fMin_1[2][2] = 30.2424373627;
   fMax_1[2][2] = 299.903961182;
   fMin_1[0][3] = 30.2424373627;
   fMax_1[0][3] = 299.701751709;
   fMin_1[1][3] = 30.4866390228;
   fMax_1[1][3] = 299.974487305;
   fMin_1[2][3] = 30.2424373627;
   fMax_1[2][3] = 299.974487305;
   fMin_1[0][4] = 33.4113769531;
   fMax_1[0][4] = 299.983215332;
   fMin_1[1][4] = 38.0267791748;
   fMax_1[1][4] = 299.974487305;
   fMin_1[2][4] = 33.4113769531;
   fMax_1[2][4] = 299.983215332;
   fMin_1[0][5] = 30.5687541962;
   fMax_1[0][5] = 289.408752441;
   fMin_1[1][5] = 32.4266166687;
   fMax_1[1][5] = 295.347045898;
   fMin_1[2][5] = 30.5687541962;
   fMax_1[2][5] = 295.347045898;
   fMin_1[0][6] = 30.2424373627;
   fMax_1[0][6] = 254.746459961;
   fMin_1[1][6] = 30.1238079071;
   fMax_1[1][6] = 255.206192017;
   fMin_1[2][6] = 30.1238079071;
   fMax_1[2][6] = 255.206192017;
   fMin_1[0][7] = 30.0002975464;
   fMax_1[0][7] = 226.160202026;
   fMin_1[1][7] = 30.0026092529;
   fMax_1[1][7] = 217.017532349;
   fMin_1[2][7] = 30.0002975464;
   fMax_1[2][7] = 226.160202026;
   fMin_1[0][8] = 0.0351784825325;
   fMax_1[0][8] = 0.999569296837;
   fMin_1[1][8] = 0.0408461764455;
   fMax_1[1][8] = 0.999452471733;
   fMin_1[2][8] = 0.0351784825325;
   fMax_1[2][8] = 0.999569296837;
   fMin_1[0][9] = 0.0403668805957;
   fMax_1[0][9] = 0.999591469765;
   fMin_1[1][9] = 0.0351793691516;
   fMax_1[1][9] = 1;
   fMin_1[2][9] = 0.0351793691516;
   fMax_1[2][9] = 1;
   fMin_1[0][10] = 0.0471258163452;
   fMax_1[0][10] = 0.999603509903;
   fMin_1[1][10] = 0.0378077812493;
   fMax_1[1][10] = 0.999564111233;
   fMin_1[2][10] = 0.0378077812493;
   fMax_1[2][10] = 0.999603509903;
   fMin_1[0][11] = 0.0345279611647;
   fMax_1[0][11] = 0.999591112137;
   fMin_1[1][11] = 0.0481413528323;
   fMax_1[1][11] = 0.999580085278;
   fMin_1[2][11] = 0.0345279611647;
   fMax_1[2][11] = 0.999591112137;
}

//_______________________________________________________________________
inline void ReadDNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 12;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<12;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadDNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
