// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Thu May 25 01:09:18 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva/v2/mkNtuple_v2
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,13]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,7]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,10]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.396064758301,5.07587337494]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [17.3422145844,299.998291016]
BJet_Pt                       BJet_Pt                       BJet_Pt                       BJet_Pt                                                         'F'    [30.4308242798,299.903961182]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [30.4533519745,299.903961182]
Jet1_Pt                       Jet1_Pt                       Jet1_Pt                       Jet1_Pt                                                         'F'    [33.8219299316,299.983215332]
Jet2_Pt                       Jet2_Pt                       Jet2_Pt                       Jet2_Pt                                                         'F'    [31.1904850006,289.616546631]
Jet3_Pt                       Jet3_Pt                       Jet3_Pt                       Jet3_Pt                                                         'F'    [30.1238079071,260.883880615]
Jet4_Pt                       Jet4_Pt                       Jet4_Pt                       Jet4_Pt                                                         'F'    [30.0009651184,227.541931152]
Jet1_CSV                      Jet1_CSV                      Jet1_CSV                      Jet1_CSV                                                        'F'    [0.0351784825325,0.999602913857]
Jet2_CSV                      Jet2_CSV                      Jet2_CSV                      Jet2_CSV                                                        'F'    [0.0428134761751,1]
Jet3_CSV                      Jet3_CSV                      Jet3_CSV                      Jet3_CSV                                                        'F'    [0.0378077812493,0.999781787395]
Jet4_CSV                      Jet4_CSV                      Jet4_CSV                      Jet4_CSV                                                        'F'    [0.0469597056508,0.999630331993]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJet_M_delta_R", "H_Mass", "BJet_Pt", "CJet_Pt", "Jet1_Pt", "Jet2_Pt", "Jet3_Pt", "Jet4_Pt", "Jet1_CSV", "Jet2_CSV", "Jet3_CSV", "Jet4_CSV" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][15];
   double fMax_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[21][16];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][21];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 16; fWeights[0] = new double[16]; 
   fLayerSize[1] = 21; fWeights[1] = new double[21]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.105203710830551;
   fWeightMatrix0to1[1][0] = 3.28591629387047;
   fWeightMatrix0to1[2][0] = 2.36649992003593;
   fWeightMatrix0to1[3][0] = 0.934876576313255;
   fWeightMatrix0to1[4][0] = 0.53407709213686;
   fWeightMatrix0to1[5][0] = -7.67299212149688;
   fWeightMatrix0to1[6][0] = -0.147484181670708;
   fWeightMatrix0to1[7][0] = 0.647555207120573;
   fWeightMatrix0to1[8][0] = -1.09782715390994;
   fWeightMatrix0to1[9][0] = -0.360523453083768;
   fWeightMatrix0to1[10][0] = -0.28662272873513;
   fWeightMatrix0to1[11][0] = 0.415313106840569;
   fWeightMatrix0to1[12][0] = 0.421145702650486;
   fWeightMatrix0to1[13][0] = -0.776304819806156;
   fWeightMatrix0to1[14][0] = -0.0693281150988049;
   fWeightMatrix0to1[15][0] = -0.0458891960597591;
   fWeightMatrix0to1[16][0] = -0.348457212307887;
   fWeightMatrix0to1[17][0] = 0.156467474160035;
   fWeightMatrix0to1[18][0] = -0.285378615129733;
   fWeightMatrix0to1[19][0] = 0.00266389843817472;
   fWeightMatrix0to1[0][1] = 1.47926128797899;
   fWeightMatrix0to1[1][1] = -0.0828402592108933;
   fWeightMatrix0to1[2][1] = -0.635917638350042;
   fWeightMatrix0to1[3][1] = -0.410102517864196;
   fWeightMatrix0to1[4][1] = -6.60676900091557;
   fWeightMatrix0to1[5][1] = 0.62939933226275;
   fWeightMatrix0to1[6][1] = -0.0795483037065331;
   fWeightMatrix0to1[7][1] = -1.11067738972066;
   fWeightMatrix0to1[8][1] = -3.341148807187;
   fWeightMatrix0to1[9][1] = -0.169499310424968;
   fWeightMatrix0to1[10][1] = -0.309193121402568;
   fWeightMatrix0to1[11][1] = -0.949577692944558;
   fWeightMatrix0to1[12][1] = -0.51945610590825;
   fWeightMatrix0to1[13][1] = 0.413168737079965;
   fWeightMatrix0to1[14][1] = 0.817646028004885;
   fWeightMatrix0to1[15][1] = -0.944922001462393;
   fWeightMatrix0to1[16][1] = 0.758931726045809;
   fWeightMatrix0to1[17][1] = -0.410837835734818;
   fWeightMatrix0to1[18][1] = -1.79850987028185;
   fWeightMatrix0to1[19][1] = 8.18644041211689;
   fWeightMatrix0to1[0][2] = 0.0259028833566509;
   fWeightMatrix0to1[1][2] = -0.891166891747183;
   fWeightMatrix0to1[2][2] = 3.54314458429319;
   fWeightMatrix0to1[3][2] = -0.617440498421558;
   fWeightMatrix0to1[4][2] = -0.714428736833114;
   fWeightMatrix0to1[5][2] = 1.3786242525662;
   fWeightMatrix0to1[6][2] = 0.14598655365937;
   fWeightMatrix0to1[7][2] = -0.848745405728988;
   fWeightMatrix0to1[8][2] = 1.4228297281277;
   fWeightMatrix0to1[9][2] = 0.296578019456692;
   fWeightMatrix0to1[10][2] = 0.0650654783355523;
   fWeightMatrix0to1[11][2] = 1.35476961784611;
   fWeightMatrix0to1[12][2] = -0.262855464718295;
   fWeightMatrix0to1[13][2] = 0.574893200571388;
   fWeightMatrix0to1[14][2] = -0.0391486016086637;
   fWeightMatrix0to1[15][2] = -0.0714637501642499;
   fWeightMatrix0to1[16][2] = -0.433159899723166;
   fWeightMatrix0to1[17][2] = 0.0787098296658218;
   fWeightMatrix0to1[18][2] = -0.722566050556823;
   fWeightMatrix0to1[19][2] = 0.826629110762144;
   fWeightMatrix0to1[0][3] = -1.8404944808245;
   fWeightMatrix0to1[1][3] = -1.09010809236875;
   fWeightMatrix0to1[2][3] = 0.461705471263654;
   fWeightMatrix0to1[3][3] = -0.127820278012541;
   fWeightMatrix0to1[4][3] = 1.06236138779622;
   fWeightMatrix0to1[5][3] = 1.02774897750607;
   fWeightMatrix0to1[6][3] = -0.37347857472197;
   fWeightMatrix0to1[7][3] = 2.15152777460456;
   fWeightMatrix0to1[8][3] = 0.744761634671917;
   fWeightMatrix0to1[9][3] = -0.0930945170272343;
   fWeightMatrix0to1[10][3] = 0.167738015071184;
   fWeightMatrix0to1[11][3] = -1.2117360247235;
   fWeightMatrix0to1[12][3] = 1.61917403336161;
   fWeightMatrix0to1[13][3] = 0.00551539647927259;
   fWeightMatrix0to1[14][3] = 0.439349246837025;
   fWeightMatrix0to1[15][3] = 1.15350207524691;
   fWeightMatrix0to1[16][3] = -0.996597621083696;
   fWeightMatrix0to1[17][3] = 2.05498243710735;
   fWeightMatrix0to1[18][3] = 2.99812966006931;
   fWeightMatrix0to1[19][3] = 3.65450160314271;
   fWeightMatrix0to1[0][4] = 2.64454766182894;
   fWeightMatrix0to1[1][4] = 1.71936408256701;
   fWeightMatrix0to1[2][4] = -1.07628266222423;
   fWeightMatrix0to1[3][4] = -0.177339160183148;
   fWeightMatrix0to1[4][4] = -1.33259481191616;
   fWeightMatrix0to1[5][4] = -0.578871995721097;
   fWeightMatrix0to1[6][4] = 0.486084308723769;
   fWeightMatrix0to1[7][4] = -0.433954464123605;
   fWeightMatrix0to1[8][4] = -1.74076364729302;
   fWeightMatrix0to1[9][4] = -0.00899306543284319;
   fWeightMatrix0to1[10][4] = 0.512079162072385;
   fWeightMatrix0to1[11][4] = 0.537821707549143;
   fWeightMatrix0to1[12][4] = 7.72564397508295;
   fWeightMatrix0to1[13][4] = 0.589129389521671;
   fWeightMatrix0to1[14][4] = -0.679704670359935;
   fWeightMatrix0to1[15][4] = 3.06830360009099;
   fWeightMatrix0to1[16][4] = -0.240047727057516;
   fWeightMatrix0to1[17][4] = -7.53254928508999;
   fWeightMatrix0to1[18][4] = -4.85226112452058;
   fWeightMatrix0to1[19][4] = 0.149020701347594;
   fWeightMatrix0to1[0][5] = -2.02634260605336;
   fWeightMatrix0to1[1][5] = -4.44865513372508;
   fWeightMatrix0to1[2][5] = 1.33835159350482;
   fWeightMatrix0to1[3][5] = 0.57780999335503;
   fWeightMatrix0to1[4][5] = -0.1151944471968;
   fWeightMatrix0to1[5][5] = 0.892794778536898;
   fWeightMatrix0to1[6][5] = -0.401276032851859;
   fWeightMatrix0to1[7][5] = 0.660902762142752;
   fWeightMatrix0to1[8][5] = 0.765918162796408;
   fWeightMatrix0to1[9][5] = -0.0154539962482541;
   fWeightMatrix0to1[10][5] = -0.831527927709956;
   fWeightMatrix0to1[11][5] = 0.752176925551856;
   fWeightMatrix0to1[12][5] = -0.847462466734227;
   fWeightMatrix0to1[13][5] = -0.472332793406979;
   fWeightMatrix0to1[14][5] = -0.305517386373696;
   fWeightMatrix0to1[15][5] = 1.58140458358392;
   fWeightMatrix0to1[16][5] = 0.149398838075687;
   fWeightMatrix0to1[17][5] = 1.80134030014577;
   fWeightMatrix0to1[18][5] = 0.3776055269234;
   fWeightMatrix0to1[19][5] = 0.385556500896525;
   fWeightMatrix0to1[0][6] = -1.51887320506909;
   fWeightMatrix0to1[1][6] = 0.0977789163924856;
   fWeightMatrix0to1[2][6] = -1.61273006500503;
   fWeightMatrix0to1[3][6] = 0.511674601742311;
   fWeightMatrix0to1[4][6] = 0.365211554372029;
   fWeightMatrix0to1[5][6] = -0.366068869211226;
   fWeightMatrix0to1[6][6] = -0.120376140503733;
   fWeightMatrix0to1[7][6] = -1.66955097112456;
   fWeightMatrix0to1[8][6] = 1.0045589277711;
   fWeightMatrix0to1[9][6] = 0.309657003283486;
   fWeightMatrix0to1[10][6] = 0.853659886048586;
   fWeightMatrix0to1[11][6] = -1.11721658285153;
   fWeightMatrix0to1[12][6] = 0.355537849097292;
   fWeightMatrix0to1[13][6] = -0.29571790562484;
   fWeightMatrix0to1[14][6] = 0.312190749418401;
   fWeightMatrix0to1[15][6] = -0.311139203095918;
   fWeightMatrix0to1[16][6] = 2.24185910661412;
   fWeightMatrix0to1[17][6] = -0.188925572758475;
   fWeightMatrix0to1[18][6] = 1.15273668461822;
   fWeightMatrix0to1[19][6] = 0.376473118354844;
   fWeightMatrix0to1[0][7] = 1.03978112555245;
   fWeightMatrix0to1[1][7] = -0.578560998328147;
   fWeightMatrix0to1[2][7] = 0.132232681232023;
   fWeightMatrix0to1[3][7] = -0.461276314584145;
   fWeightMatrix0to1[4][7] = 0.0684348815630861;
   fWeightMatrix0to1[5][7] = 0.15339033001617;
   fWeightMatrix0to1[6][7] = 0.322881799582072;
   fWeightMatrix0to1[7][7] = 1.16857907917206;
   fWeightMatrix0to1[8][7] = -0.773067037925352;
   fWeightMatrix0to1[9][7] = -0.108867698755271;
   fWeightMatrix0to1[10][7] = -0.187282868829609;
   fWeightMatrix0to1[11][7] = 0.650035377646186;
   fWeightMatrix0to1[12][7] = 0.131114280786266;
   fWeightMatrix0to1[13][7] = 3.20787747481676;
   fWeightMatrix0to1[14][7] = 0.011635017463956;
   fWeightMatrix0to1[15][7] = -0.312375555588348;
   fWeightMatrix0to1[16][7] = 0.826582643175073;
   fWeightMatrix0to1[17][7] = 0.109664466383136;
   fWeightMatrix0to1[18][7] = -0.49067250976603;
   fWeightMatrix0to1[19][7] = 0.103568908597742;
   fWeightMatrix0to1[0][8] = 0.706039017735244;
   fWeightMatrix0to1[1][8] = 1.15368134111524;
   fWeightMatrix0to1[2][8] = 0.141123379490213;
   fWeightMatrix0to1[3][8] = 0.149268333949871;
   fWeightMatrix0to1[4][8] = 0.082273786336874;
   fWeightMatrix0to1[5][8] = 0.335684606322976;
   fWeightMatrix0to1[6][8] = -0.109923935176829;
   fWeightMatrix0to1[7][8] = -0.140344902258309;
   fWeightMatrix0to1[8][8] = -1.42311439274576;
   fWeightMatrix0to1[9][8] = -0.163497852042755;
   fWeightMatrix0to1[10][8] = 0.86155931552509;
   fWeightMatrix0to1[11][8] = -0.668079340301308;
   fWeightMatrix0to1[12][8] = 0.465403223805881;
   fWeightMatrix0to1[13][8] = 1.52519620816393;
   fWeightMatrix0to1[14][8] = 0.302864850866918;
   fWeightMatrix0to1[15][8] = 1.07666439908981;
   fWeightMatrix0to1[16][8] = 1.97170595386613;
   fWeightMatrix0to1[17][8] = 0.251053752232761;
   fWeightMatrix0to1[18][8] = 0.772471835601238;
   fWeightMatrix0to1[19][8] = 0.655855608979283;
   fWeightMatrix0to1[0][9] = -1.45633833841565;
   fWeightMatrix0to1[1][9] = 1.40956827859619;
   fWeightMatrix0to1[2][9] = 1.99714183984578;
   fWeightMatrix0to1[3][9] = -0.0457021396962956;
   fWeightMatrix0to1[4][9] = 0.753186774522688;
   fWeightMatrix0to1[5][9] = -0.227081082448528;
   fWeightMatrix0to1[6][9] = 0.391057643974325;
   fWeightMatrix0to1[7][9] = 1.7111983776243;
   fWeightMatrix0to1[8][9] = -0.39133419638854;
   fWeightMatrix0to1[9][9] = -0.331508496465875;
   fWeightMatrix0to1[10][9] = -0.572106918487484;
   fWeightMatrix0to1[11][9] = -0.45706346223574;
   fWeightMatrix0to1[12][9] = 0.21324747866725;
   fWeightMatrix0to1[13][9] = 1.07761236168524;
   fWeightMatrix0to1[14][9] = -0.710097024822612;
   fWeightMatrix0to1[15][9] = 1.00070204890726;
   fWeightMatrix0to1[16][9] = -0.577711334539692;
   fWeightMatrix0to1[17][9] = 0.637221239305529;
   fWeightMatrix0to1[18][9] = 1.85535887977044;
   fWeightMatrix0to1[19][9] = 0.0712719298721834;
   fWeightMatrix0to1[0][10] = -0.60366413909192;
   fWeightMatrix0to1[1][10] = 0.307164259174264;
   fWeightMatrix0to1[2][10] = -0.0786303433095867;
   fWeightMatrix0to1[3][10] = 4.54056868501869;
   fWeightMatrix0to1[4][10] = 3.58844952691273;
   fWeightMatrix0to1[5][10] = 0.311199031373626;
   fWeightMatrix0to1[6][10] = -0.533472229116259;
   fWeightMatrix0to1[7][10] = -0.475838783427584;
   fWeightMatrix0to1[8][10] = -0.460029994208698;
   fWeightMatrix0to1[9][10] = 0.285013358858932;
   fWeightMatrix0to1[10][10] = 0.605401408097214;
   fWeightMatrix0to1[11][10] = 0.0814807092817467;
   fWeightMatrix0to1[12][10] = 0.219824429110179;
   fWeightMatrix0to1[13][10] = 4.05569628153295;
   fWeightMatrix0to1[14][10] = 1.55972628460199;
   fWeightMatrix0to1[15][10] = -0.455320816489692;
   fWeightMatrix0to1[16][10] = 2.49192462629852;
   fWeightMatrix0to1[17][10] = 0.670842597436394;
   fWeightMatrix0to1[18][10] = 0.418640461479292;
   fWeightMatrix0to1[19][10] = -0.460902930337373;
   fWeightMatrix0to1[0][11] = 0.411862352939355;
   fWeightMatrix0to1[1][11] = -0.122686574022025;
   fWeightMatrix0to1[2][11] = 0.00753212285117937;
   fWeightMatrix0to1[3][11] = 0.575633704877271;
   fWeightMatrix0to1[4][11] = 0.153221331137;
   fWeightMatrix0to1[5][11] = 0.250407303653296;
   fWeightMatrix0to1[6][11] = 0.0615244196511734;
   fWeightMatrix0to1[7][11] = 1.36846795991885;
   fWeightMatrix0to1[8][11] = -0.381383849926515;
   fWeightMatrix0to1[9][11] = -0.0743216404864825;
   fWeightMatrix0to1[10][11] = -0.805555103966173;
   fWeightMatrix0to1[11][11] = 0.0204362707302252;
   fWeightMatrix0to1[12][11] = 0.077896382826122;
   fWeightMatrix0to1[13][11] = -0.597170820669883;
   fWeightMatrix0to1[14][11] = -0.241386944227492;
   fWeightMatrix0to1[15][11] = -0.152690091013404;
   fWeightMatrix0to1[16][11] = -0.17492097745131;
   fWeightMatrix0to1[17][11] = 0.501834011649183;
   fWeightMatrix0to1[18][11] = -0.446812829021641;
   fWeightMatrix0to1[19][11] = -0.0348906597474863;
   fWeightMatrix0to1[0][12] = -0.404577459344216;
   fWeightMatrix0to1[1][12] = 0.145846544342722;
   fWeightMatrix0to1[2][12] = -0.327399364358793;
   fWeightMatrix0to1[3][12] = 0.682971357157486;
   fWeightMatrix0to1[4][12] = -0.050360443347569;
   fWeightMatrix0to1[5][12] = 0.0217640627779775;
   fWeightMatrix0to1[6][12] = -0.00381952994858582;
   fWeightMatrix0to1[7][12] = -2.01808625761943;
   fWeightMatrix0to1[8][12] = -0.32146689615631;
   fWeightMatrix0to1[9][12] = -0.0220194584745323;
   fWeightMatrix0to1[10][12] = 0.0741546761061417;
   fWeightMatrix0to1[11][12] = 0.195359901956302;
   fWeightMatrix0to1[12][12] = 0.113140087847124;
   fWeightMatrix0to1[13][12] = -0.0951489503820927;
   fWeightMatrix0to1[14][12] = -0.279724634396524;
   fWeightMatrix0to1[15][12] = 0.0124556088929656;
   fWeightMatrix0to1[16][12] = 0.969622183994575;
   fWeightMatrix0to1[17][12] = 0.286445589202301;
   fWeightMatrix0to1[18][12] = -0.240284253521132;
   fWeightMatrix0to1[19][12] = 0.0584846403526929;
   fWeightMatrix0to1[0][13] = -0.378310469041726;
   fWeightMatrix0to1[1][13] = -0.19190299360544;
   fWeightMatrix0to1[2][13] = -0.390312196321318;
   fWeightMatrix0to1[3][13] = 0.251848531994681;
   fWeightMatrix0to1[4][13] = -0.0700557751229606;
   fWeightMatrix0to1[5][13] = 0.0966770398396865;
   fWeightMatrix0to1[6][13] = 0.211150262200573;
   fWeightMatrix0to1[7][13] = 1.06979394388744;
   fWeightMatrix0to1[8][13] = -0.329701183807979;
   fWeightMatrix0to1[9][13] = -0.0982544151644899;
   fWeightMatrix0to1[10][13] = 0.597714736739159;
   fWeightMatrix0to1[11][13] = -0.238996003909662;
   fWeightMatrix0to1[12][13] = -0.0421505466341664;
   fWeightMatrix0to1[13][13] = -0.0307786634755972;
   fWeightMatrix0to1[14][13] = -0.296659968773653;
   fWeightMatrix0to1[15][13] = -0.062280610668036;
   fWeightMatrix0to1[16][13] = 0.731364998500299;
   fWeightMatrix0to1[17][13] = 0.0978433179614993;
   fWeightMatrix0to1[18][13] = -0.786985497321555;
   fWeightMatrix0to1[19][13] = -0.109744355535823;
   fWeightMatrix0to1[0][14] = -0.292136756339971;
   fWeightMatrix0to1[1][14] = -0.188554476835457;
   fWeightMatrix0to1[2][14] = -0.629162685827683;
   fWeightMatrix0to1[3][14] = -0.0750750572912026;
   fWeightMatrix0to1[4][14] = -0.082031840121191;
   fWeightMatrix0to1[5][14] = 0.0598776130584377;
   fWeightMatrix0to1[6][14] = -0.0728497298893595;
   fWeightMatrix0to1[7][14] = 1.235572687065;
   fWeightMatrix0to1[8][14] = 0.244728087963596;
   fWeightMatrix0to1[9][14] = 0.0133366052720953;
   fWeightMatrix0to1[10][14] = 0.194754414606361;
   fWeightMatrix0to1[11][14] = 1.37564532222277;
   fWeightMatrix0to1[12][14] = 0.0340469439761583;
   fWeightMatrix0to1[13][14] = -0.124857296919748;
   fWeightMatrix0to1[14][14] = 0.085933769503814;
   fWeightMatrix0to1[15][14] = -0.0398857643410966;
   fWeightMatrix0to1[16][14] = 0.795377289458228;
   fWeightMatrix0to1[17][14] = 0.0171452819411273;
   fWeightMatrix0to1[18][14] = -0.584235796148099;
   fWeightMatrix0to1[19][14] = -0.0931691394913251;
   fWeightMatrix0to1[0][15] = -1.15535737481422;
   fWeightMatrix0to1[1][15] = 0.623283667347878;
   fWeightMatrix0to1[2][15] = 4.24693649807666;
   fWeightMatrix0to1[3][15] = 2.49728617689841;
   fWeightMatrix0to1[4][15] = -0.7672907394875;
   fWeightMatrix0to1[5][15] = -5.31986205260148;
   fWeightMatrix0to1[6][15] = -0.616227050523223;
   fWeightMatrix0to1[7][15] = 0.265658317398897;
   fWeightMatrix0to1[8][15] = -2.24600765049853;
   fWeightMatrix0to1[9][15] = -0.277576968180356;
   fWeightMatrix0to1[10][15] = 0.155075255037825;
   fWeightMatrix0to1[11][15] = -1.34136067593345;
   fWeightMatrix0to1[12][15] = 1.88831717705953;
   fWeightMatrix0to1[13][15] = 8.06921029823935;
   fWeightMatrix0to1[14][15] = 0.930011977219825;
   fWeightMatrix0to1[15][15] = 2.13801537312524;
   fWeightMatrix0to1[16][15] = 2.23026960605387;
   fWeightMatrix0to1[17][15] = -1.61800596523226;
   fWeightMatrix0to1[18][15] = -0.202456213643664;
   fWeightMatrix0to1[19][15] = 4.08420813217487;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.421779889278508;
   fWeightMatrix1to2[0][1] = -0.302417205171211;
   fWeightMatrix1to2[0][2] = -0.451973174614599;
   fWeightMatrix1to2[0][3] = -0.532989900503534;
   fWeightMatrix1to2[0][4] = 0.513590350939363;
   fWeightMatrix1to2[0][5] = 0.528964287036797;
   fWeightMatrix1to2[0][6] = 0.299734559705511;
   fWeightMatrix1to2[0][7] = -0.287726432617326;
   fWeightMatrix1to2[0][8] = -0.51391540732633;
   fWeightMatrix1to2[0][9] = -0.143700727503542;
   fWeightMatrix1to2[0][10] = -0.405253217663612;
   fWeightMatrix1to2[0][11] = -0.252903849057699;
   fWeightMatrix1to2[0][12] = -0.818904460341342;
   fWeightMatrix1to2[0][13] = -0.69193391722276;
   fWeightMatrix1to2[0][14] = 0.585756435392295;
   fWeightMatrix1to2[0][15] = 0.629066653129668;
   fWeightMatrix1to2[0][16] = -0.230954683533695;
   fWeightMatrix1to2[0][17] = -0.555811675573524;
   fWeightMatrix1to2[0][18] = -0.461564857356136;
   fWeightMatrix1to2[0][19] = -0.853607192561215;
   fWeightMatrix1to2[0][20] = -1.13715337523511;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 11;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 13;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 13;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 5;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 7;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 9;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 10;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 10;
   fMin_1[0][3] = 0.399108380079;
   fMax_1[0][3] = 4.68654870987;
   fMin_1[1][3] = 0.396064758301;
   fMax_1[1][3] = 5.07587337494;
   fMin_1[2][3] = 0.396064758301;
   fMax_1[2][3] = 5.07587337494;
   fMin_1[0][4] = 19.7999248505;
   fMax_1[0][4] = 299.975952148;
   fMin_1[1][4] = 17.3422145844;
   fMax_1[1][4] = 299.998291016;
   fMin_1[2][4] = 17.3422145844;
   fMax_1[2][4] = 299.998291016;
   fMin_1[0][5] = 30.4533519745;
   fMax_1[0][5] = 299.703308105;
   fMin_1[1][5] = 30.4308242798;
   fMax_1[1][5] = 299.903961182;
   fMin_1[2][5] = 30.4308242798;
   fMax_1[2][5] = 299.903961182;
   fMin_1[0][6] = 30.4533519745;
   fMax_1[0][6] = 299.703308105;
   fMin_1[1][6] = 31.5732555389;
   fMax_1[1][6] = 299.903961182;
   fMin_1[2][6] = 30.4533519745;
   fMax_1[2][6] = 299.903961182;
   fMin_1[0][7] = 33.8219299316;
   fMax_1[0][7] = 299.983215332;
   fMin_1[1][7] = 36.9922218323;
   fMax_1[1][7] = 299.940673828;
   fMin_1[2][7] = 33.8219299316;
   fMax_1[2][7] = 299.983215332;
   fMin_1[0][8] = 31.1904850006;
   fMax_1[0][8] = 288.066101074;
   fMin_1[1][8] = 31.8723602295;
   fMax_1[1][8] = 289.616546631;
   fMin_1[2][8] = 31.1904850006;
   fMax_1[2][8] = 289.616546631;
   fMin_1[0][9] = 30.1670379639;
   fMax_1[0][9] = 237.090316772;
   fMin_1[1][9] = 30.1238079071;
   fMax_1[1][9] = 260.883880615;
   fMin_1[2][9] = 30.1238079071;
   fMax_1[2][9] = 260.883880615;
   fMin_1[0][10] = 30.0009651184;
   fMax_1[0][10] = 187.586990356;
   fMin_1[1][10] = 30.0026092529;
   fMax_1[1][10] = 227.541931152;
   fMin_1[2][10] = 30.0009651184;
   fMax_1[2][10] = 227.541931152;
   fMin_1[0][11] = 0.0351784825325;
   fMax_1[0][11] = 0.999602913857;
   fMin_1[1][11] = 0.0368843339384;
   fMax_1[1][11] = 0.999452471733;
   fMin_1[2][11] = 0.0351784825325;
   fMax_1[2][11] = 0.999602913857;
   fMin_1[0][12] = 0.0428134761751;
   fMax_1[0][12] = 0.999524593353;
   fMin_1[1][12] = 0.0438870862126;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0.0428134761751;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0.0419070869684;
   fMax_1[0][13] = 0.999528348446;
   fMin_1[1][13] = 0.0378077812493;
   fMax_1[1][13] = 0.999781787395;
   fMin_1[2][13] = 0.0378077812493;
   fMax_1[2][13] = 0.999781787395;
   fMin_1[0][14] = 0.0469597056508;
   fMax_1[0][14] = 0.999630331993;
   fMin_1[1][14] = 0.0489051826298;
   fMax_1[1][14] = 0.999580085278;
   fMin_1[2][14] = 0.0469597056508;
   fMax_1[2][14] = 0.999630331993;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
