configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.1f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " CMS"
  extra-label: "Preliminary"
  root: ''
  luminosity: 41529
  luminosity-error: 0.023
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'

files:
  include: ['files.yml']

systematics:
  - nlo_xsec: 1.055  # Constant systematics
  - ttbb_xsec: {type: const, value: 1.3, on: 'hist_TTpowhegttbb.root'}
  - ttcc_xsec: {type: const, value: 1.5, on: 'hist_TTpowhegttcc.root'}
  - pu
  - lepSF
  - lf
  - hf
  - hfstat1
  - hfstat2
  - lfstat1
  - lfstat2
  - cferr1
  - cferr2
  #- beta: {type: shape}  # Shape systematics
  #- gamma: {type: ln, prior: 1.072, pretty-name: "Gamma"}  # Log-normal systematics, +7.2%, -2.97%, exp(+/- 1 * log(prior))
        
plots:
#  include: ['histos.yml']
  include: ['histos_st.yml']
#  include: ['histos_ttbkg.yml']

legend:
  position: [0.18, 0.65, 0.92, 0.89]
  columns: 5

groups:
  include: ['groups.yml']
