configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.1f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " CMS"
  extra-label: "Preliminary"
  root: ''
  luminosity: 41529
  luminosity-error: 0.023
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'

files:
  include: ['files.yml']

systematics:
  - ttbb_xsec:     {type: const, value: 1.055, on: 'hist_TTpowhegttbb.root'}
  - ttbj_xsec:     {type: const, value: 1.055, on: 'hist_TTpowhegttbj.root'}
  - ttcc_xsec:     {type: const, value: 1.055, on: 'hist_TTpowhegttcc.root'}
  - ttlf_xsec:     {type: const, value: 1.055, on: 'hist_TTpowhegttlf.root'}
  - ttother_xsec:  {type: const, value: 1.055, on: 'hist_TTpowhegttother.root'}
  - ttll_xsec:     {type: const, value: 1.055, on: 'hist_TTLLpowheg.root'}
  - tthad_xsec:    {type: const, value: 1.055, on: 'hist_TTHadpowheg.root'}
  - ttbb_xsec2:    {type: const, value: 1.3, on: 'hist_TTpowhegttbb.root'}
  - ttcc_xsec2:    {type: const, value: 1.5, on: 'hist_TTpowhegttcc.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttbj.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttother.root'}
  - scale: {type: shape, on: 'hist_TTLLpowheg.root'}
  - scale: {type: shape, on: 'hist_TTHadpowheg.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttbj.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttother.root'}
  - hdamp: {type: shape, on: 'hist_TTLLpowheg.root'}
  - hdamp: {type: shape, on: 'hist_TTHadpowheg.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttbj.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttother.root'}
  - TuneCP5: {type: shape, on: 'hist_TTLLpowheg.root'}
  - TuneCP5: {type: shape, on: 'hist_TTHadpowheg.root'}
  - pu
  - muid
  - muiso
  - mutrg
  - elid
  - elreco
  - elzvtx
  - lf
  - hf
  - hfstat1
  - hfstat2
  - lfstat1
  - lfstat2
  - cferr1
  - cferr2
  - jec
  - jer
#  - gamma: {type: ln, prior: 1.072, pretty-name: "Gamma"}  # Log-normal systematics, +7.2%, -2.97%, exp(+/- 1 * log(prior))
#  - scale: {type: scaleweight, on: 'hist_TTpowhegttbb.root'}
#  - scale: {type: scaleweight, on: 'hist_TTpowhegttbj.root'}
#  - scale: {type: scaleweight, on: 'hist_TTpowhegttcc.root'}
#  - scale: {type: scaleweight, on: 'hist_TTpowhegttlf.root'}
#  - scale: {type: scaleweight, on: 'hist_TTpowhegttother.root'}
#  - scale: {type: scaleweight, on: 'hist_TTLLpowheg.root'}
#  - scale: {type: scaleweight, on: 'hist_TTHadpowheg.root'}
#  - hdamp: {type: shape, on: 'hist_TTpowhegttbb.root', ext-sum-weight-up: 27191508, ext-sum-weight-down: 26367765}
#  - hdamp: {type: shape, on: 'hist_TTpowhegttbj.root', ext-sum-weight-up: 27191508, ext-sum-weight-down: 26367765}
#  - hdamp: {type: shape, on: 'hist_TTpowhegttcc.root', ext-sum-weight-up: 27191508, ext-sum-weight-down: 26367765}
#  - hdamp: {type: shape, on: 'hist_TTpowhegttlf.root', ext-sum-weight-up: 27191508, ext-sum-weight-down: 26367765}
#  - hdamp: {type: shape, on: 'hist_TTpowhegttother.root', ext-sum-weight-up: 27191508, ext-sum-weight-down: 26367765}
#  - hdamp: {type: shape, on: 'hist_TTLLpowheg.root', ext-sum-weight-up: 5413576, ext-sum-weight-down: 5336672}
#  - hdamp: {type: shape, on: 'hist_TTHadpowheg.root', ext-sum-weight-up: 25821240, ext-sum-weight-down: 27117982}
#  - TuneCP5: {type: shape, on: 'hist_TTpowhegttbb.root', ext-sum-weight-up: 26166070, ext-sum-weight-down: 27104055}
#  - TuneCP5: {type: shape, on: 'hist_TTpowhegttbj.root', ext-sum-weight-up: 26166070, ext-sum-weight-down: 27104055}
#  - TuneCP5: {type: shape, on: 'hist_TTpowhegttcc.root', ext-sum-weight-up: 26166070, ext-sum-weight-down: 27104055}
#  - TuneCP5: {type: shape, on: 'hist_TTpowhegttlf.root', ext-sum-weight-up: 26166070, ext-sum-weight-down: 27104055}
#  - TuneCP5: {type: shape, on: 'hist_TTpowhegttother.root', ext-sum-weight-up: 26166070, ext-sum-weight-down: 27104055}
#  - TuneCP5: {type: shape, on: 'hist_TTLLpowheg.root', ext-sum-weight-up: 5500000, ext-sum-weight-down: 5475200}
#  - TuneCP5: {type: shape, on: 'hist_TTHadpowheg.root', ext-sum-weight-up: 27206470, ext-sum-weight-down: 26155064}

plots:
  include: ['histos.yml'] #,'histos_st.yml'] #'histos_ttfcnc.yml'] 'histos_ttbkg.yml']

legend:
  position: [0.18, 0.65, 0.92, 0.89]
  columns: 5

groups:
  include: ['groups.yml']
