#S4 Mu
'h_PV_Ch0_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch0_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_NBJetCSVv2M_Ch0_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch0_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_MET_Ch0_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch0_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

#S4 elec
'h_PV_Ch1_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch1_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_NBJetCSVv2M_Ch1_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch1_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_MET_Ch1_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch1_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_PV_Ch2_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch2_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_NBJetCSVv2M_Ch2_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch2_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_MET_Ch2_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch2_S4':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch2_S9':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch2_S9':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch2_S9':
  for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
