#S4 Mu
'h_PV_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_NBJetCSVv2M_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepEta_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_MET_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_WMass_Ch0_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch0_S4':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

#S4 elec
'h_PV_Ch1_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch1_S4':
  #for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_NBJetCSVv2M_Ch1_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch1_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepEta_Ch1_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_MET_Ch1_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_WMass_Ch1_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch1_S4':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

#Ch2 S4v
'h_PV_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_NJet_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_NBJetCSVv2M_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepEta_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_MET_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_WMass_Ch2_S4':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch2_S4':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']


#S9
'h_NJet_Ch2_S9':
  #for-yields: true
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']

'h_LepPt_Ch2_S9':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_JetCSV_Ch2_S9':
  y-axis: "Number of jets"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

#lep pt
'h_LepPt_Ch2_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepPt_Ch2_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepPt_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepPt_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true

'h_LepPt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
  for-yields: true
