#HMass
'h_FCNHkinHMass_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch2_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch2_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHMass_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

#dR
'h_FCNHkinDR_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch2_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch2_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinDR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

#LepTonMass
'h_FCNHkinLepTopM_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinLepTopM_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']


#b2 deep csv
'h_FCNHkinHb2CSV_Ch0_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch0_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch0_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch0_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch0_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch1_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch1_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch1_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch1_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch1_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch2_S2':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch2_S3':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch2_S6':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch2_S7':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']

'h_FCNHkinHb2CSV_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.0f GeV"
  save-extensions: ['pdf']
