// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Tue Jul  4 23:27:10 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/analysis_jw/tmva/v1
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 28
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,13]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [3,6]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,8]
Transvers_Mass                Transvers_Mass                Transvers_Mass                Transvers_Mass                                                  'F'    [0.0348501950502,369.078704834]
Lepton_DPhi                   Lepton_DPhi                   Lepton_DPhi                   Lepton_DPhi                                                     'F'    [-3.14140152931,3.14153575897]
Missing_ET                    Missing_ET                    Missing_ET                    Missing_ET                                                      'F'    [0.332486361265,671.120422363]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.388728410006,3.48090934753]
BJet_M_delta_Eta              BJet_M_delta_Eta              BJet_M_delta_Eta              BJet_M_delta_Eta                                                'F'    [2.89678573608e-05,3.13447403908]
BJet_M_delta_Phi              BJet_M_delta_Phi              BJet_M_delta_Phi              BJet_M_delta_Phi                                                'F'    [2.39163637161e-05,6.27293777466]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [18.3813915253,1218.23632812]
BJet_Pt_H                     BJet_Pt_H                     BJet_Pt_H                     BJet_Pt_H                                                       'F'    [30.3176345825,1400.890625]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [31.2792739868,1402.21191406]
Jet1_Pt                       Jet1_Pt                       Jet1_Pt                       Jet1_Pt                                                         'F'    [33.7081336975,1402.21191406]
Jet2_Pt                       Jet2_Pt                       Jet2_Pt                       Jet2_Pt                                                         'F'    [31.1904850006,1149.72290039]
Jet3_Pt                       Jet3_Pt                       Jet3_Pt                       Jet3_Pt                                                         'F'    [30.1826877594,476.129394531]
Jet4_Pt                       Jet4_Pt                       Jet4_Pt                       Jet4_Pt                                                         'F'    [30.0017719269,301.51852417]
Jet1_CSV                      Jet1_CSV                      Jet1_CSV                      Jet1_CSV                                                        'F'    [0.0443393550813,0.999611914158]
Jet2_CSV                      Jet2_CSV                      Jet2_CSV                      Jet2_CSV                                                        'F'    [0.0408265255392,0.99962580204]
Jet3_CSV                      Jet3_CSV                      Jet3_CSV                      Jet3_CSV                                                        'F'    [0.0471053086221,0.999616205692]
Jet4_CSV                      Jet4_CSV                      Jet4_CSV                      Jet4_CSV                                                        'F'    [0.0470969378948,0.999606192112]
Kin_Lep_WMass                 Kin_Lep_WMass                 Kin_Lep_WMass                 Kin_Lep_WMass                                                   'F'    [-24.594379425,559.032531738]
Kin_Lep_TopMass               Kin_Lep_TopMass               Kin_Lep_TopMass               Kin_Lep_TopMass                                                 'F'    [5.32452011108,559.032531738]
Kin_Had_WMass                 Kin_Had_WMass                 Kin_Had_WMass                 Kin_Had_WMass                                                   'F'    [0,95.7668457031]
Kin_Had_TopMass               Kin_Had_TopMass               Kin_Had_TopMass               Kin_Had_TopMass                                                 'F'    [0,177.754180908]
fcnhKin_Lep_WMass             fcnhKin_Lep_WMass             fcnhKin_Lep_WMass             fcnhKin_Lep_WMass                                               'F'    [-267.692596436,678.751220703]
fcnhKin_Lep_TopMass           fcnhKin_Lep_TopMass           fcnhKin_Lep_TopMass           fcnhKin_Lep_TopMass                                             'F'    [1.50358843803,678.751220703]
fcnhKin_HMass                 fcnhKin_HMass                 fcnhKin_HMass                 fcnhKin_HMass                                                   'F'    [0,138.089294434]
fcnhKin_Huc_TopMass           fcnhKin_Huc_TopMass           fcnhKin_Huc_TopMass           fcnhKin_Huc_TopMass                                             'F'    [0,1501.63049316]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 28 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "Transvers_Mass", "Lepton_DPhi", "Missing_ET", "BJet_M_delta_R", "BJet_M_delta_Eta", "BJet_M_delta_Phi", "H_Mass", "BJet_Pt_H", "CJet_Pt", "Jet1_Pt", "Jet2_Pt", "Jet3_Pt", "Jet4_Pt", "Jet1_CSV", "Jet2_CSV", "Jet3_CSV", "Jet4_CSV", "Kin_Lep_WMass", "Kin_Lep_TopMass", "Kin_Had_WMass", "Kin_Had_TopMass", "fcnhKin_Lep_WMass", "fcnhKin_Lep_TopMass", "fcnhKin_HMass", "fcnhKin_Huc_TopMass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;
      fVmin[16] = -1;
      fVmax[16] = 1;
      fVmin[17] = -1;
      fVmax[17] = 1;
      fVmin[18] = -1;
      fVmax[18] = 1;
      fVmin[19] = -1;
      fVmax[19] = 1;
      fVmin[20] = -1;
      fVmax[20] = 1;
      fVmin[21] = -1;
      fVmax[21] = 1;
      fVmin[22] = -1;
      fVmax[22] = 1;
      fVmin[23] = -1;
      fVmax[23] = 1;
      fVmin[24] = -1;
      fVmax[24] = 1;
      fVmin[25] = -1;
      fVmax[25] = 1;
      fVmin[26] = -1;
      fVmax[26] = 1;
      fVmin[27] = -1;
      fVmax[27] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][28];
   double fMax_1[3][28];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[28];
   double fVmax[28];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[28];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[34][29];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][34];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 29; fWeights[0] = new double[29]; 
   fLayerSize[1] = 34; fWeights[1] = new double[34]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.517271410268549;
   fWeightMatrix0to1[1][0] = 0.403712873116876;
   fWeightMatrix0to1[2][0] = 0.340585612283531;
   fWeightMatrix0to1[3][0] = 4.43900551503543;
   fWeightMatrix0to1[4][0] = -5.3439813704363;
   fWeightMatrix0to1[5][0] = -3.36043926076058;
   fWeightMatrix0to1[6][0] = -1.02504792818231;
   fWeightMatrix0to1[7][0] = 0.730906122181502;
   fWeightMatrix0to1[8][0] = -0.972637298442884;
   fWeightMatrix0to1[9][0] = -3.51891492008774;
   fWeightMatrix0to1[10][0] = -1.3097459999951;
   fWeightMatrix0to1[11][0] = -0.367413739229301;
   fWeightMatrix0to1[12][0] = -0.990088439570194;
   fWeightMatrix0to1[13][0] = -0.694813632261603;
   fWeightMatrix0to1[14][0] = 0.0440346109297458;
   fWeightMatrix0to1[15][0] = -0.401803679467079;
   fWeightMatrix0to1[16][0] = -0.306854089768587;
   fWeightMatrix0to1[17][0] = 0.617985602577936;
   fWeightMatrix0to1[18][0] = 1.86822925089209;
   fWeightMatrix0to1[19][0] = 1.06429414126426;
   fWeightMatrix0to1[20][0] = 0.940652304510685;
   fWeightMatrix0to1[21][0] = 2.98330903946682;
   fWeightMatrix0to1[22][0] = 3.19230312891867;
   fWeightMatrix0to1[23][0] = -10.5009330571571;
   fWeightMatrix0to1[24][0] = -0.55119894815386;
   fWeightMatrix0to1[25][0] = 1.68992818298646;
   fWeightMatrix0to1[26][0] = 2.61990854571318;
   fWeightMatrix0to1[27][0] = -0.706239558542142;
   fWeightMatrix0to1[28][0] = -1.8988184712605;
   fWeightMatrix0to1[29][0] = 0.55993044256572;
   fWeightMatrix0to1[30][0] = 2.57159395598288;
   fWeightMatrix0to1[31][0] = 0.803194092661353;
   fWeightMatrix0to1[32][0] = -1.02377721973418;
   fWeightMatrix0to1[0][1] = -2.14303914257138;
   fWeightMatrix0to1[1][1] = 0.593521368002895;
   fWeightMatrix0to1[2][1] = 1.00317108619849;
   fWeightMatrix0to1[3][1] = -2.16787830356437;
   fWeightMatrix0to1[4][1] = 3.13961322562156;
   fWeightMatrix0to1[5][1] = -0.517829136153635;
   fWeightMatrix0to1[6][1] = -0.779863327368732;
   fWeightMatrix0to1[7][1] = 0.170355727778084;
   fWeightMatrix0to1[8][1] = 0.463757804446121;
   fWeightMatrix0to1[9][1] = 3.05492947163135;
   fWeightMatrix0to1[10][1] = 1.43544314404679;
   fWeightMatrix0to1[11][1] = -3.22448420058426;
   fWeightMatrix0to1[12][1] = -1.46744479606244;
   fWeightMatrix0to1[13][1] = 2.22308194466352;
   fWeightMatrix0to1[14][1] = 7.79040076704891;
   fWeightMatrix0to1[15][1] = 0.0389692520293948;
   fWeightMatrix0to1[16][1] = 0.878401196573416;
   fWeightMatrix0to1[17][1] = 2.07727778967156;
   fWeightMatrix0to1[18][1] = 0.108835005588649;
   fWeightMatrix0to1[19][1] = -3.27160318558929;
   fWeightMatrix0to1[20][1] = -0.361521424032227;
   fWeightMatrix0to1[21][1] = -1.72791950739071;
   fWeightMatrix0to1[22][1] = -0.633394245663485;
   fWeightMatrix0to1[23][1] = 0.174869759111322;
   fWeightMatrix0to1[24][1] = 1.51108483896991;
   fWeightMatrix0to1[25][1] = 2.6382430290112;
   fWeightMatrix0to1[26][1] = 3.11296581357058;
   fWeightMatrix0to1[27][1] = -1.55014971660492;
   fWeightMatrix0to1[28][1] = -1.15725070124571;
   fWeightMatrix0to1[29][1] = 1.12771110288871;
   fWeightMatrix0to1[30][1] = 1.70761329343507;
   fWeightMatrix0to1[31][1] = 3.30200986511407;
   fWeightMatrix0to1[32][1] = 1.35574019924001;
   fWeightMatrix0to1[0][2] = 1.17936059861561;
   fWeightMatrix0to1[1][2] = -1.45427981052589;
   fWeightMatrix0to1[2][2] = 2.42229544474249;
   fWeightMatrix0to1[3][2] = -0.19219619853514;
   fWeightMatrix0to1[4][2] = -4.57966686633318;
   fWeightMatrix0to1[5][2] = -2.95647197160811;
   fWeightMatrix0to1[6][2] = 0.781457973806875;
   fWeightMatrix0to1[7][2] = 0.425564716217989;
   fWeightMatrix0to1[8][2] = 2.88959074365944;
   fWeightMatrix0to1[9][2] = -1.18806582998819;
   fWeightMatrix0to1[10][2] = -1.61105966124173;
   fWeightMatrix0to1[11][2] = -3.54594101003559;
   fWeightMatrix0to1[12][2] = 0.6308610496168;
   fWeightMatrix0to1[13][2] = 0.877041360248425;
   fWeightMatrix0to1[14][2] = -0.0601370983369968;
   fWeightMatrix0to1[15][2] = -0.147941510830441;
   fWeightMatrix0to1[16][2] = 1.2568473150334;
   fWeightMatrix0to1[17][2] = -0.218023765457088;
   fWeightMatrix0to1[18][2] = 1.46953326312499;
   fWeightMatrix0to1[19][2] = -0.584328716702742;
   fWeightMatrix0to1[20][2] = 1.42195309013843;
   fWeightMatrix0to1[21][2] = 0.57798893274321;
   fWeightMatrix0to1[22][2] = -3.68480124824681;
   fWeightMatrix0to1[23][2] = 0.635179301467851;
   fWeightMatrix0to1[24][2] = -0.37014302607047;
   fWeightMatrix0to1[25][2] = 1.22551495348237;
   fWeightMatrix0to1[26][2] = 2.74648410338534;
   fWeightMatrix0to1[27][2] = -0.119096051525993;
   fWeightMatrix0to1[28][2] = -1.65533949963023;
   fWeightMatrix0to1[29][2] = 0.210727198703583;
   fWeightMatrix0to1[30][2] = -2.81528871343068;
   fWeightMatrix0to1[31][2] = -3.30857148461623;
   fWeightMatrix0to1[32][2] = -0.151750909093753;
   fWeightMatrix0to1[0][3] = -0.453786826898808;
   fWeightMatrix0to1[1][3] = -1.64529273150044;
   fWeightMatrix0to1[2][3] = -1.54614420065033;
   fWeightMatrix0to1[3][3] = 0.565393720557761;
   fWeightMatrix0to1[4][3] = 0.70413998314989;
   fWeightMatrix0to1[5][3] = 0.697469865305631;
   fWeightMatrix0to1[6][3] = 1.88849030257168;
   fWeightMatrix0to1[7][3] = -1.10364436734671;
   fWeightMatrix0to1[8][3] = 0.107423285019897;
   fWeightMatrix0to1[9][3] = -1.93021662190031;
   fWeightMatrix0to1[10][3] = 2.77269821769149;
   fWeightMatrix0to1[11][3] = -1.70451262161936;
   fWeightMatrix0to1[12][3] = -0.820485535729656;
   fWeightMatrix0to1[13][3] = 0.328414043482458;
   fWeightMatrix0to1[14][3] = 0.277348451355073;
   fWeightMatrix0to1[15][3] = -0.697187106949868;
   fWeightMatrix0to1[16][3] = 2.57446138302672;
   fWeightMatrix0to1[17][3] = -0.352927067925008;
   fWeightMatrix0to1[18][3] = 1.3780898602088;
   fWeightMatrix0to1[19][3] = 0.978729129782556;
   fWeightMatrix0to1[20][3] = -2.77324478599861;
   fWeightMatrix0to1[21][3] = -2.54914230342338;
   fWeightMatrix0to1[22][3] = -2.00015633107177;
   fWeightMatrix0to1[23][3] = -0.520066767678863;
   fWeightMatrix0to1[24][3] = -0.211335152816327;
   fWeightMatrix0to1[25][3] = 3.50988239878251;
   fWeightMatrix0to1[26][3] = 2.05771941450574;
   fWeightMatrix0to1[27][3] = -0.732417201855393;
   fWeightMatrix0to1[28][3] = 0.381254229144485;
   fWeightMatrix0to1[29][3] = 0.888385095448136;
   fWeightMatrix0to1[30][3] = -1.11434474373587;
   fWeightMatrix0to1[31][3] = -0.96510395672295;
   fWeightMatrix0to1[32][3] = -3.74316965924373;
   fWeightMatrix0to1[0][4] = 1.44592389198642;
   fWeightMatrix0to1[1][4] = -0.0245390590098876;
   fWeightMatrix0to1[2][4] = 1.37398331450364;
   fWeightMatrix0to1[3][4] = -0.719947569210897;
   fWeightMatrix0to1[4][4] = 1.69753156435854;
   fWeightMatrix0to1[5][4] = -1.45707075559236;
   fWeightMatrix0to1[6][4] = 0.470912821964786;
   fWeightMatrix0to1[7][4] = 3.09284601955708;
   fWeightMatrix0to1[8][4] = 0.398009694417;
   fWeightMatrix0to1[9][4] = -0.476692954579208;
   fWeightMatrix0to1[10][4] = -1.36141226187662;
   fWeightMatrix0to1[11][4] = 0.480279460316435;
   fWeightMatrix0to1[12][4] = -0.554717281619029;
   fWeightMatrix0to1[13][4] = 1.13855506477296;
   fWeightMatrix0to1[14][4] = 0.190482511154193;
   fWeightMatrix0to1[15][4] = -2.30148055074859;
   fWeightMatrix0to1[16][4] = 0.710904218035922;
   fWeightMatrix0to1[17][4] = -0.358844110442183;
   fWeightMatrix0to1[18][4] = -0.0845703318431919;
   fWeightMatrix0to1[19][4] = 0.144081218960956;
   fWeightMatrix0to1[20][4] = 3.56724595728681;
   fWeightMatrix0to1[21][4] = -2.7716553029015;
   fWeightMatrix0to1[22][4] = -0.322577131558627;
   fWeightMatrix0to1[23][4] = 0.292788546537594;
   fWeightMatrix0to1[24][4] = 0.205592527960637;
   fWeightMatrix0to1[25][4] = 0.24220786491529;
   fWeightMatrix0to1[26][4] = 1.00537813160245;
   fWeightMatrix0to1[27][4] = -1.84622760102362;
   fWeightMatrix0to1[28][4] = 2.38984168469705;
   fWeightMatrix0to1[29][4] = 0.0298320732842594;
   fWeightMatrix0to1[30][4] = -0.137459753440298;
   fWeightMatrix0to1[31][4] = -0.915018655832441;
   fWeightMatrix0to1[32][4] = -0.390721580598594;
   fWeightMatrix0to1[0][5] = -0.26628427581338;
   fWeightMatrix0to1[1][5] = -2.39153914919137;
   fWeightMatrix0to1[2][5] = 0.724171916312214;
   fWeightMatrix0to1[3][5] = -1.45625406970287;
   fWeightMatrix0to1[4][5] = 1.2804139662162;
   fWeightMatrix0to1[5][5] = 2.59025847140628;
   fWeightMatrix0to1[6][5] = -0.261906596221023;
   fWeightMatrix0to1[7][5] = 0.933622351062853;
   fWeightMatrix0to1[8][5] = 1.97211331780749;
   fWeightMatrix0to1[9][5] = 1.0728820151728;
   fWeightMatrix0to1[10][5] = -1.28034279498574;
   fWeightMatrix0to1[11][5] = 0.9441126159754;
   fWeightMatrix0to1[12][5] = 0.149285244082907;
   fWeightMatrix0to1[13][5] = 3.75048464218512;
   fWeightMatrix0to1[14][5] = 0.026023457390402;
   fWeightMatrix0to1[15][5] = -3.27984861013329;
   fWeightMatrix0to1[16][5] = -0.278215109198208;
   fWeightMatrix0to1[17][5] = 1.73169782469742;
   fWeightMatrix0to1[18][5] = -3.09257062259616;
   fWeightMatrix0to1[19][5] = -4.03874429603103;
   fWeightMatrix0to1[20][5] = -1.01122983566453;
   fWeightMatrix0to1[21][5] = 0.315200756246502;
   fWeightMatrix0to1[22][5] = 0.568502194113388;
   fWeightMatrix0to1[23][5] = -0.167287561252578;
   fWeightMatrix0to1[24][5] = 0.797514617944166;
   fWeightMatrix0to1[25][5] = 2.23239887081294;
   fWeightMatrix0to1[26][5] = 0.700313037450498;
   fWeightMatrix0to1[27][5] = 1.43949311008916;
   fWeightMatrix0to1[28][5] = 1.41060426008901;
   fWeightMatrix0to1[29][5] = 0.249686446806202;
   fWeightMatrix0to1[30][5] = 1.26641791926253;
   fWeightMatrix0to1[31][5] = -2.83395483157187;
   fWeightMatrix0to1[32][5] = 0.58053050037905;
   fWeightMatrix0to1[0][6] = 1.66930877894414;
   fWeightMatrix0to1[1][6] = -1.27717171748887;
   fWeightMatrix0to1[2][6] = 0.253067304449244;
   fWeightMatrix0to1[3][6] = -0.829668581089015;
   fWeightMatrix0to1[4][6] = 1.77204751362959;
   fWeightMatrix0to1[5][6] = -0.301155653421119;
   fWeightMatrix0to1[6][6] = 0.0924138900236441;
   fWeightMatrix0to1[7][6] = 0.0441571231039034;
   fWeightMatrix0to1[8][6] = -1.19327822274962;
   fWeightMatrix0to1[9][6] = -1.29851899725262;
   fWeightMatrix0to1[10][6] = 1.4469581689684;
   fWeightMatrix0to1[11][6] = 0.109149468697227;
   fWeightMatrix0to1[12][6] = 1.04924705114002;
   fWeightMatrix0to1[13][6] = -3.23092997989654;
   fWeightMatrix0to1[14][6] = -1.11433757689749;
   fWeightMatrix0to1[15][6] = -2.05781673373548;
   fWeightMatrix0to1[16][6] = 3.7181914822781;
   fWeightMatrix0to1[17][6] = 2.09501707374527;
   fWeightMatrix0to1[18][6] = -2.34067148470173;
   fWeightMatrix0to1[19][6] = -3.39610530789338;
   fWeightMatrix0to1[20][6] = 2.70117594672054;
   fWeightMatrix0to1[21][6] = -1.63732119408955;
   fWeightMatrix0to1[22][6] = -2.3574290331384;
   fWeightMatrix0to1[23][6] = -0.158741620377724;
   fWeightMatrix0to1[24][6] = -2.32238326572273;
   fWeightMatrix0to1[25][6] = 3.66270353295022;
   fWeightMatrix0to1[26][6] = 1.54242316711352;
   fWeightMatrix0to1[27][6] = -2.20769253355068;
   fWeightMatrix0to1[28][6] = 1.50843080693773;
   fWeightMatrix0to1[29][6] = -0.695523408666849;
   fWeightMatrix0to1[30][6] = -3.63470290978632;
   fWeightMatrix0to1[31][6] = -3.76599533613486;
   fWeightMatrix0to1[32][6] = 2.33663480296976;
   fWeightMatrix0to1[0][7] = 1.12344878693025;
   fWeightMatrix0to1[1][7] = 0.341899941643044;
   fWeightMatrix0to1[2][7] = -2.31140440596559;
   fWeightMatrix0to1[3][7] = 1.37372408333222;
   fWeightMatrix0to1[4][7] = -0.720138092944216;
   fWeightMatrix0to1[5][7] = 1.20985318145239;
   fWeightMatrix0to1[6][7] = 0.34404082276671;
   fWeightMatrix0to1[7][7] = -0.458862556378468;
   fWeightMatrix0to1[8][7] = 2.19698327232061;
   fWeightMatrix0to1[9][7] = -0.804290731732425;
   fWeightMatrix0to1[10][7] = 1.41618083198877;
   fWeightMatrix0to1[11][7] = -1.01950739344036;
   fWeightMatrix0to1[12][7] = -0.539598713225697;
   fWeightMatrix0to1[13][7] = -0.952624984317593;
   fWeightMatrix0to1[14][7] = -0.044208331323781;
   fWeightMatrix0to1[15][7] = -0.99173546319464;
   fWeightMatrix0to1[16][7] = 1.74717289873562;
   fWeightMatrix0to1[17][7] = 3.48894509079717;
   fWeightMatrix0to1[18][7] = -1.46210155182431;
   fWeightMatrix0to1[19][7] = 0.189431369685178;
   fWeightMatrix0to1[20][7] = -0.990436323778594;
   fWeightMatrix0to1[21][7] = 0.715162514085811;
   fWeightMatrix0to1[22][7] = 1.43636564565755;
   fWeightMatrix0to1[23][7] = 0.535242345589467;
   fWeightMatrix0to1[24][7] = -0.367034725324179;
   fWeightMatrix0to1[25][7] = -2.20196290020741;
   fWeightMatrix0to1[26][7] = -0.622780623863473;
   fWeightMatrix0to1[27][7] = 1.6734972724331;
   fWeightMatrix0to1[28][7] = -1.29320409246409;
   fWeightMatrix0to1[29][7] = -0.694181613296064;
   fWeightMatrix0to1[30][7] = 0.816217083169598;
   fWeightMatrix0to1[31][7] = 2.58904572418975;
   fWeightMatrix0to1[32][7] = 1.09062399642062;
   fWeightMatrix0to1[0][8] = 1.19377987061805;
   fWeightMatrix0to1[1][8] = -0.96017410201213;
   fWeightMatrix0to1[2][8] = -2.17131639298346;
   fWeightMatrix0to1[3][8] = 3.83313072513553;
   fWeightMatrix0to1[4][8] = 0.65411297366784;
   fWeightMatrix0to1[5][8] = -1.05902498713178;
   fWeightMatrix0to1[6][8] = -2.75673278946967;
   fWeightMatrix0to1[7][8] = 0.0195805067298678;
   fWeightMatrix0to1[8][8] = 2.3452230640206;
   fWeightMatrix0to1[9][8] = -1.05153648833786;
   fWeightMatrix0to1[10][8] = -1.05846252661487;
   fWeightMatrix0to1[11][8] = -0.15467390685837;
   fWeightMatrix0to1[12][8] = -0.906928035743415;
   fWeightMatrix0to1[13][8] = 0.739372614903753;
   fWeightMatrix0to1[14][8] = -0.0140055164462418;
   fWeightMatrix0to1[15][8] = 0.408949164291858;
   fWeightMatrix0to1[16][8] = 0.48312903508446;
   fWeightMatrix0to1[17][8] = -0.186130262780933;
   fWeightMatrix0to1[18][8] = 0.00330969053443399;
   fWeightMatrix0to1[19][8] = -1.16509419479804;
   fWeightMatrix0to1[20][8] = -3.67038775771559;
   fWeightMatrix0to1[21][8] = -1.59863933488573;
   fWeightMatrix0to1[22][8] = -2.73839796488334;
   fWeightMatrix0to1[23][8] = -0.215657254643595;
   fWeightMatrix0to1[24][8] = -0.0188631433851327;
   fWeightMatrix0to1[25][8] = 0.549388177500484;
   fWeightMatrix0to1[26][8] = -2.67068986662594;
   fWeightMatrix0to1[27][8] = 1.6444589261342;
   fWeightMatrix0to1[28][8] = -0.885564025438948;
   fWeightMatrix0to1[29][8] = -0.314007736351009;
   fWeightMatrix0to1[30][8] = 0.324882357255149;
   fWeightMatrix0to1[31][8] = -2.30454871887459;
   fWeightMatrix0to1[32][8] = 0.91151810576945;
   fWeightMatrix0to1[0][9] = 0.324217746996153;
   fWeightMatrix0to1[1][9] = -2.84145366998913;
   fWeightMatrix0to1[2][9] = -2.55495915930929;
   fWeightMatrix0to1[3][9] = -1.11121981604904;
   fWeightMatrix0to1[4][9] = -1.23872101387596;
   fWeightMatrix0to1[5][9] = 2.03060822896981;
   fWeightMatrix0to1[6][9] = 0.24178798794104;
   fWeightMatrix0to1[7][9] = -1.08328925570678;
   fWeightMatrix0to1[8][9] = -3.37164212830197;
   fWeightMatrix0to1[9][9] = -1.92444205992987;
   fWeightMatrix0to1[10][9] = -5.3989970902912;
   fWeightMatrix0to1[11][9] = 1.54981696135909;
   fWeightMatrix0to1[12][9] = -0.0523584938857766;
   fWeightMatrix0to1[13][9] = 1.207220068402;
   fWeightMatrix0to1[14][9] = -14.8145631032331;
   fWeightMatrix0to1[15][9] = -0.562539625609951;
   fWeightMatrix0to1[16][9] = 1.3072505779841;
   fWeightMatrix0to1[17][9] = 2.95587674377923;
   fWeightMatrix0to1[18][9] = -4.70370439489624;
   fWeightMatrix0to1[19][9] = -0.87544098475413;
   fWeightMatrix0to1[20][9] = -0.52558613493846;
   fWeightMatrix0to1[21][9] = 0.444438727449595;
   fWeightMatrix0to1[22][9] = 1.86307238342217;
   fWeightMatrix0to1[23][9] = -0.558149183174406;
   fWeightMatrix0to1[24][9] = -11.9384966857251;
   fWeightMatrix0to1[25][9] = -0.0973760968584292;
   fWeightMatrix0to1[26][9] = -4.33567629145664;
   fWeightMatrix0to1[27][9] = 1.34285452766135;
   fWeightMatrix0to1[28][9] = 1.69824158517407;
   fWeightMatrix0to1[29][9] = 3.54327656950146;
   fWeightMatrix0to1[30][9] = 2.52668791732161;
   fWeightMatrix0to1[31][9] = -1.02536909725505;
   fWeightMatrix0to1[32][9] = 1.11742394486636;
   fWeightMatrix0to1[0][10] = -3.03062557019465;
   fWeightMatrix0to1[1][10] = -1.66869444085998;
   fWeightMatrix0to1[2][10] = -3.7443124312726;
   fWeightMatrix0to1[3][10] = 1.77567737500479;
   fWeightMatrix0to1[4][10] = -0.0572193975391558;
   fWeightMatrix0to1[5][10] = 2.14197479505413;
   fWeightMatrix0to1[6][10] = 0.883085943113661;
   fWeightMatrix0to1[7][10] = 0.40216923301385;
   fWeightMatrix0to1[8][10] = -1.65542904043905;
   fWeightMatrix0to1[9][10] = -0.83337630791851;
   fWeightMatrix0to1[10][10] = -4.08340389493449;
   fWeightMatrix0to1[11][10] = 2.99539538590924;
   fWeightMatrix0to1[12][10] = 3.31368198404128;
   fWeightMatrix0to1[13][10] = 0.368297809660167;
   fWeightMatrix0to1[14][10] = -2.20698946997479;
   fWeightMatrix0to1[15][10] = 0.191283654600012;
   fWeightMatrix0to1[16][10] = -0.32730392233873;
   fWeightMatrix0to1[17][10] = 1.14926980713671;
   fWeightMatrix0to1[18][10] = 3.36059572292694;
   fWeightMatrix0to1[19][10] = -1.9154820499459;
   fWeightMatrix0to1[20][10] = 3.23112182222995;
   fWeightMatrix0to1[21][10] = 2.94824712966489;
   fWeightMatrix0to1[22][10] = 0.323605824423669;
   fWeightMatrix0to1[23][10] = 2.97051282221139;
   fWeightMatrix0to1[24][10] = -1.59008893944526;
   fWeightMatrix0to1[25][10] = -1.25770076603626;
   fWeightMatrix0to1[26][10] = -2.65165422999732;
   fWeightMatrix0to1[27][10] = 1.43158778258237;
   fWeightMatrix0to1[28][10] = -1.26986612508676;
   fWeightMatrix0to1[29][10] = -3.62840505584152;
   fWeightMatrix0to1[30][10] = 1.75235319789788;
   fWeightMatrix0to1[31][10] = 3.12960701901279;
   fWeightMatrix0to1[32][10] = -0.869827447557376;
   fWeightMatrix0to1[0][11] = -1.68033121502903;
   fWeightMatrix0to1[1][11] = 1.25302568246656;
   fWeightMatrix0to1[2][11] = -1.39978067305128;
   fWeightMatrix0to1[3][11] = -1.59479592169335;
   fWeightMatrix0to1[4][11] = -0.950135022330827;
   fWeightMatrix0to1[5][11] = -2.05357724166307;
   fWeightMatrix0to1[6][11] = 0.239968684224398;
   fWeightMatrix0to1[7][11] = 1.2663226021517;
   fWeightMatrix0to1[8][11] = -0.430152239541707;
   fWeightMatrix0to1[9][11] = -0.107818168359564;
   fWeightMatrix0to1[10][11] = 1.77281645147483;
   fWeightMatrix0to1[11][11] = 1.09881907871498;
   fWeightMatrix0to1[12][11] = 0.682601275179609;
   fWeightMatrix0to1[13][11] = -2.82375703206668;
   fWeightMatrix0to1[14][11] = 0.314118058706628;
   fWeightMatrix0to1[15][11] = -0.398484081061793;
   fWeightMatrix0to1[16][11] = 1.80199791988394;
   fWeightMatrix0to1[17][11] = -0.905381878740681;
   fWeightMatrix0to1[18][11] = -2.41295716806289;
   fWeightMatrix0to1[19][11] = -0.814239882201251;
   fWeightMatrix0to1[20][11] = 0.700441331085711;
   fWeightMatrix0to1[21][11] = 2.04718295560523;
   fWeightMatrix0to1[22][11] = 1.84394976065724;
   fWeightMatrix0to1[23][11] = -1.08748137199829;
   fWeightMatrix0to1[24][11] = 2.7740130032741;
   fWeightMatrix0to1[25][11] = 2.32414063115551;
   fWeightMatrix0to1[26][11] = -0.493186345315867;
   fWeightMatrix0to1[27][11] = 1.59711665562511;
   fWeightMatrix0to1[28][11] = -0.103563225725236;
   fWeightMatrix0to1[29][11] = 3.36186456124965;
   fWeightMatrix0to1[30][11] = 0.307839361113375;
   fWeightMatrix0to1[31][11] = -2.088006387676;
   fWeightMatrix0to1[32][11] = 1.4162670526217;
   fWeightMatrix0to1[0][12] = 2.79361778731838;
   fWeightMatrix0to1[1][12] = 2.80410871787746;
   fWeightMatrix0to1[2][12] = 0.951870885643367;
   fWeightMatrix0to1[3][12] = -0.0623070049476758;
   fWeightMatrix0to1[4][12] = 1.28793424643723;
   fWeightMatrix0to1[5][12] = 0.0905173106751259;
   fWeightMatrix0to1[6][12] = 0.911732757934809;
   fWeightMatrix0to1[7][12] = 0.889054243037959;
   fWeightMatrix0to1[8][12] = 1.3018833958457;
   fWeightMatrix0to1[9][12] = -1.83788591510925;
   fWeightMatrix0to1[10][12] = 2.2257425681607;
   fWeightMatrix0to1[11][12] = 0.9316392017464;
   fWeightMatrix0to1[12][12] = -1.74262698322551;
   fWeightMatrix0to1[13][12] = -2.08000859129674;
   fWeightMatrix0to1[14][12] = 0.227599262558091;
   fWeightMatrix0to1[15][12] = -2.50061482216502;
   fWeightMatrix0to1[16][12] = 1.89338234331829;
   fWeightMatrix0to1[17][12] = -2.0869994621948;
   fWeightMatrix0to1[18][12] = -0.881035901515056;
   fWeightMatrix0to1[19][12] = 1.92529718874672;
   fWeightMatrix0to1[20][12] = 1.36173025482325;
   fWeightMatrix0to1[21][12] = 1.79954746549858;
   fWeightMatrix0to1[22][12] = 2.55288393434138;
   fWeightMatrix0to1[23][12] = 1.92173190899194;
   fWeightMatrix0to1[24][12] = -0.814789748631687;
   fWeightMatrix0to1[25][12] = 0.413468358587711;
   fWeightMatrix0to1[26][12] = 4.41439883134914;
   fWeightMatrix0to1[27][12] = -1.33867157910467;
   fWeightMatrix0to1[28][12] = -2.32852708189379;
   fWeightMatrix0to1[29][12] = 7.06917011551929;
   fWeightMatrix0to1[30][12] = -0.697969780867623;
   fWeightMatrix0to1[31][12] = -2.79642490476752;
   fWeightMatrix0to1[32][12] = -1.21374882767135;
   fWeightMatrix0to1[0][13] = 0.470110700910396;
   fWeightMatrix0to1[1][13] = -1.16644485969585;
   fWeightMatrix0to1[2][13] = -1.00861342002473;
   fWeightMatrix0to1[3][13] = -0.554483652188881;
   fWeightMatrix0to1[4][13] = -0.680898317452151;
   fWeightMatrix0to1[5][13] = 1.2585127602826;
   fWeightMatrix0to1[6][13] = 3.86640610687878;
   fWeightMatrix0to1[7][13] = 2.48684341225884;
   fWeightMatrix0to1[8][13] = -1.02424360156982;
   fWeightMatrix0to1[9][13] = -2.21982182895059;
   fWeightMatrix0to1[10][13] = -1.30293972900235;
   fWeightMatrix0to1[11][13] = -3.61738362790959;
   fWeightMatrix0to1[12][13] = -2.32537263810101;
   fWeightMatrix0to1[13][13] = -1.45450393046843;
   fWeightMatrix0to1[14][13] = -0.0966100302544624;
   fWeightMatrix0to1[15][13] = -1.13209233248184;
   fWeightMatrix0to1[16][13] = 1.5942533132833;
   fWeightMatrix0to1[17][13] = 2.28436046603338;
   fWeightMatrix0to1[18][13] = -0.0675864031545735;
   fWeightMatrix0to1[19][13] = -0.768859040487667;
   fWeightMatrix0to1[20][13] = -0.988018279247672;
   fWeightMatrix0to1[21][13] = 2.07465763414745;
   fWeightMatrix0to1[22][13] = -0.166335791768714;
   fWeightMatrix0to1[23][13] = 0.552034001318223;
   fWeightMatrix0to1[24][13] = 1.82696966289363;
   fWeightMatrix0to1[25][13] = 0.920265589913655;
   fWeightMatrix0to1[26][13] = -1.7827257594396;
   fWeightMatrix0to1[27][13] = 0.829059249210108;
   fWeightMatrix0to1[28][13] = -3.09366879862144;
   fWeightMatrix0to1[29][13] = 2.68449918517753;
   fWeightMatrix0to1[30][13] = 0.943130015341002;
   fWeightMatrix0to1[31][13] = -1.33892466136604;
   fWeightMatrix0to1[32][13] = 0.0385142502647854;
   fWeightMatrix0to1[0][14] = 1.34357021116075;
   fWeightMatrix0to1[1][14] = -3.73405744203411;
   fWeightMatrix0to1[2][14] = 0.986062479009807;
   fWeightMatrix0to1[3][14] = -2.99514778044606;
   fWeightMatrix0to1[4][14] = -0.838542398985004;
   fWeightMatrix0to1[5][14] = -0.41038789166374;
   fWeightMatrix0to1[6][14] = 0.705629481542488;
   fWeightMatrix0to1[7][14] = 3.83364685439345;
   fWeightMatrix0to1[8][14] = -0.769159432633349;
   fWeightMatrix0to1[9][14] = -2.72155982714897;
   fWeightMatrix0to1[10][14] = -3.92006296279136;
   fWeightMatrix0to1[11][14] = 3.30314822899984;
   fWeightMatrix0to1[12][14] = -0.489747621471691;
   fWeightMatrix0to1[13][14] = -4.60293106229286;
   fWeightMatrix0to1[14][14] = 0.186650948650218;
   fWeightMatrix0to1[15][14] = -0.773226842938199;
   fWeightMatrix0to1[16][14] = 1.43160069947691;
   fWeightMatrix0to1[17][14] = 0.0817975474139181;
   fWeightMatrix0to1[18][14] = -0.356162096818432;
   fWeightMatrix0to1[19][14] = -0.138361787969083;
   fWeightMatrix0to1[20][14] = 2.0726453852404;
   fWeightMatrix0to1[21][14] = 0.15616798741907;
   fWeightMatrix0to1[22][14] = 3.18817706870805;
   fWeightMatrix0to1[23][14] = 0.774311261558174;
   fWeightMatrix0to1[24][14] = -0.0672161001917989;
   fWeightMatrix0to1[25][14] = -1.26579151415996;
   fWeightMatrix0to1[26][14] = 1.1386265683172;
   fWeightMatrix0to1[27][14] = 1.54843487295368;
   fWeightMatrix0to1[28][14] = -0.625702606774499;
   fWeightMatrix0to1[29][14] = 0.800330760436407;
   fWeightMatrix0to1[30][14] = 0.162001076999648;
   fWeightMatrix0to1[31][14] = -1.48071751415354;
   fWeightMatrix0to1[32][14] = 0.387132069911214;
   fWeightMatrix0to1[0][15] = 0.531589385476015;
   fWeightMatrix0to1[1][15] = 0.462321215522569;
   fWeightMatrix0to1[2][15] = -0.539312568565608;
   fWeightMatrix0to1[3][15] = -2.73543883766116;
   fWeightMatrix0to1[4][15] = 1.96033303131483;
   fWeightMatrix0to1[5][15] = -1.27093888272148;
   fWeightMatrix0to1[6][15] = 1.73777105737508;
   fWeightMatrix0to1[7][15] = 1.33343832519935;
   fWeightMatrix0to1[8][15] = -0.228031377924317;
   fWeightMatrix0to1[9][15] = -0.497680467510531;
   fWeightMatrix0to1[10][15] = -2.3335106945447;
   fWeightMatrix0to1[11][15] = 2.66929738501349;
   fWeightMatrix0to1[12][15] = -2.19226024079295;
   fWeightMatrix0to1[13][15] = -2.00397657077525;
   fWeightMatrix0to1[14][15] = -1.02634336487169;
   fWeightMatrix0to1[15][15] = 3.28490722268323;
   fWeightMatrix0to1[16][15] = -2.17116653721156;
   fWeightMatrix0to1[17][15] = -1.82361714839911;
   fWeightMatrix0to1[18][15] = -1.54377227100572;
   fWeightMatrix0to1[19][15] = 1.55236281204476;
   fWeightMatrix0to1[20][15] = -0.703627657168082;
   fWeightMatrix0to1[21][15] = 0.247015873052932;
   fWeightMatrix0to1[22][15] = -0.19940988384992;
   fWeightMatrix0to1[23][15] = -2.83268695880061;
   fWeightMatrix0to1[24][15] = -0.138705070375749;
   fWeightMatrix0to1[25][15] = 0.606235088533064;
   fWeightMatrix0to1[26][15] = 2.39252894570992;
   fWeightMatrix0to1[27][15] = 2.39650055266137;
   fWeightMatrix0to1[28][15] = -0.525509413521668;
   fWeightMatrix0to1[29][15] = 1.62520506296728;
   fWeightMatrix0to1[30][15] = 2.37133099086576;
   fWeightMatrix0to1[31][15] = 1.68329902895618;
   fWeightMatrix0to1[32][15] = 3.06917833241551;
   fWeightMatrix0to1[0][16] = 4.72753019294256;
   fWeightMatrix0to1[1][16] = -1.80760533430608;
   fWeightMatrix0to1[2][16] = 1.208019279554;
   fWeightMatrix0to1[3][16] = 0.177594974060878;
   fWeightMatrix0to1[4][16] = -2.87137877951114;
   fWeightMatrix0to1[5][16] = -0.46984249926344;
   fWeightMatrix0to1[6][16] = -0.346543438531638;
   fWeightMatrix0to1[7][16] = -0.276157876967379;
   fWeightMatrix0to1[8][16] = -0.542854018245566;
   fWeightMatrix0to1[9][16] = -0.582665381821768;
   fWeightMatrix0to1[10][16] = -1.18737368564417;
   fWeightMatrix0to1[11][16] = -0.288740815865421;
   fWeightMatrix0to1[12][16] = -0.335482042213812;
   fWeightMatrix0to1[13][16] = -1.78434541890867;
   fWeightMatrix0to1[14][16] = 0.350944314654196;
   fWeightMatrix0to1[15][16] = -2.9339760783718;
   fWeightMatrix0to1[16][16] = 0.215344805695032;
   fWeightMatrix0to1[17][16] = 0.695437996204853;
   fWeightMatrix0to1[18][16] = -2.52100717483255;
   fWeightMatrix0to1[19][16] = -1.04134916952152;
   fWeightMatrix0to1[20][16] = 2.0187569707033;
   fWeightMatrix0to1[21][16] = 0.0134953590943832;
   fWeightMatrix0to1[22][16] = 0.507789731900608;
   fWeightMatrix0to1[23][16] = -0.431339907155928;
   fWeightMatrix0to1[24][16] = -0.238054902940197;
   fWeightMatrix0to1[25][16] = -2.51802226704081;
   fWeightMatrix0to1[26][16] = -2.34388671934673;
   fWeightMatrix0to1[27][16] = 0.0260557034994197;
   fWeightMatrix0to1[28][16] = 0.828591139544765;
   fWeightMatrix0to1[29][16] = -3.077878096917;
   fWeightMatrix0to1[30][16] = 2.54623220781058;
   fWeightMatrix0to1[31][16] = -1.01679507165738;
   fWeightMatrix0to1[32][16] = -0.444699633442346;
   fWeightMatrix0to1[0][17] = 5.48564154320301;
   fWeightMatrix0to1[1][17] = 1.00873798079726;
   fWeightMatrix0to1[2][17] = 1.37359460663781;
   fWeightMatrix0to1[3][17] = 0.53446176940718;
   fWeightMatrix0to1[4][17] = -0.175427551449309;
   fWeightMatrix0to1[5][17] = -0.187114492029289;
   fWeightMatrix0to1[6][17] = -1.66996376578038;
   fWeightMatrix0to1[7][17] = -1.71272772444794;
   fWeightMatrix0to1[8][17] = -1.17690408766406;
   fWeightMatrix0to1[9][17] = -0.732778655943478;
   fWeightMatrix0to1[10][17] = -0.061218002354595;
   fWeightMatrix0to1[11][17] = 0.660354624902805;
   fWeightMatrix0to1[12][17] = 1.11993017990742;
   fWeightMatrix0to1[13][17] = -1.32639504046534;
   fWeightMatrix0to1[14][17] = 0.0531728457311808;
   fWeightMatrix0to1[15][17] = 0.811326382372947;
   fWeightMatrix0to1[16][17] = -0.857069948698338;
   fWeightMatrix0to1[17][17] = 1.47613187804799;
   fWeightMatrix0to1[18][17] = -1.02909502883791;
   fWeightMatrix0to1[19][17] = -0.690954351527316;
   fWeightMatrix0to1[20][17] = -1.20464767098968;
   fWeightMatrix0to1[21][17] = 0.490926152723729;
   fWeightMatrix0to1[22][17] = -1.2763171410297;
   fWeightMatrix0to1[23][17] = -0.281305542100901;
   fWeightMatrix0to1[24][17] = -0.0428668929702931;
   fWeightMatrix0to1[25][17] = -1.23658459210326;
   fWeightMatrix0to1[26][17] = -0.446472851401551;
   fWeightMatrix0to1[27][17] = 0.093863655952727;
   fWeightMatrix0to1[28][17] = 0.899010664396945;
   fWeightMatrix0to1[29][17] = -0.813779832721552;
   fWeightMatrix0to1[30][17] = 0.715612236858018;
   fWeightMatrix0to1[31][17] = -0.0897434500008321;
   fWeightMatrix0to1[32][17] = 1.08743822947929;
   fWeightMatrix0to1[0][18] = -1.14915101329377;
   fWeightMatrix0to1[1][18] = 0.0754339328802147;
   fWeightMatrix0to1[2][18] = 3.45457238256017;
   fWeightMatrix0to1[3][18] = -0.622984407881955;
   fWeightMatrix0to1[4][18] = 0.0862739354050434;
   fWeightMatrix0to1[5][18] = -0.341316975795327;
   fWeightMatrix0to1[6][18] = 1.98570520150055;
   fWeightMatrix0to1[7][18] = 1.74491933633484;
   fWeightMatrix0to1[8][18] = 0.0382025198995004;
   fWeightMatrix0to1[9][18] = -0.410629259660875;
   fWeightMatrix0to1[10][18] = 0.393781032171412;
   fWeightMatrix0to1[11][18] = 1.71415168354386;
   fWeightMatrix0to1[12][18] = 4.34776974585602;
   fWeightMatrix0to1[13][18] = -0.0411877955074695;
   fWeightMatrix0to1[14][18] = -0.0317371516030388;
   fWeightMatrix0to1[15][18] = 1.49621121780807;
   fWeightMatrix0to1[16][18] = -2.16648553497708;
   fWeightMatrix0to1[17][18] = 0.958846598993151;
   fWeightMatrix0to1[18][18] = -0.632094454580212;
   fWeightMatrix0to1[19][18] = -0.250407694322164;
   fWeightMatrix0to1[20][18] = -1.7500074814799;
   fWeightMatrix0to1[21][18] = 0.117098764184845;
   fWeightMatrix0to1[22][18] = -1.04665173945421;
   fWeightMatrix0to1[23][18] = 0.618590252071888;
   fWeightMatrix0to1[24][18] = -0.026493239101406;
   fWeightMatrix0to1[25][18] = -0.967510016799478;
   fWeightMatrix0to1[26][18] = 0.479410236034843;
   fWeightMatrix0to1[27][18] = 4.53406733057258;
   fWeightMatrix0to1[28][18] = 0.974849497556961;
   fWeightMatrix0to1[29][18] = -0.012242373882476;
   fWeightMatrix0to1[30][18] = -0.52397922673055;
   fWeightMatrix0to1[31][18] = -0.33634353705809;
   fWeightMatrix0to1[32][18] = -3.31447850088894;
   fWeightMatrix0to1[0][19] = 0.206344264571579;
   fWeightMatrix0to1[1][19] = 0.176953725282987;
   fWeightMatrix0to1[2][19] = 0.693715199556299;
   fWeightMatrix0to1[3][19] = -0.249702223317883;
   fWeightMatrix0to1[4][19] = -0.0908767531552007;
   fWeightMatrix0to1[5][19] = -0.234698081190339;
   fWeightMatrix0to1[6][19] = -2.66728549196491;
   fWeightMatrix0to1[7][19] = -2.11870227763153;
   fWeightMatrix0to1[8][19] = 0.137152395984474;
   fWeightMatrix0to1[9][19] = -0.0816668972378686;
   fWeightMatrix0to1[10][19] = 0.128872955887735;
   fWeightMatrix0to1[11][19] = 0.493667553256376;
   fWeightMatrix0to1[12][19] = 0.481240891051445;
   fWeightMatrix0to1[13][19] = 0.357462089103674;
   fWeightMatrix0to1[14][19] = -0.107825774113544;
   fWeightMatrix0to1[15][19] = 0.791282639907973;
   fWeightMatrix0to1[16][19] = 0.981432098643634;
   fWeightMatrix0to1[17][19] = -4.49389977315637;
   fWeightMatrix0to1[18][19] = -0.139450216947688;
   fWeightMatrix0to1[19][19] = -3.83463885453367;
   fWeightMatrix0to1[20][19] = 0.336619352465651;
   fWeightMatrix0to1[21][19] = 0.564731220371312;
   fWeightMatrix0to1[22][19] = 2.86184680189039;
   fWeightMatrix0to1[23][19] = 0.110243488121845;
   fWeightMatrix0to1[24][19] = -0.189171583341991;
   fWeightMatrix0to1[25][19] = -0.958008743148267;
   fWeightMatrix0to1[26][19] = 0.173857556758879;
   fWeightMatrix0to1[27][19] = 0.799918541394564;
   fWeightMatrix0to1[28][19] = -0.172091232063659;
   fWeightMatrix0to1[29][19] = -0.0598074567455834;
   fWeightMatrix0to1[30][19] = -0.739495723124333;
   fWeightMatrix0to1[31][19] = 0.641087614308634;
   fWeightMatrix0to1[32][19] = -1.44049088071746;
   fWeightMatrix0to1[0][20] = -1.92995178353115;
   fWeightMatrix0to1[1][20] = 3.68494052420344;
   fWeightMatrix0to1[2][20] = 0.512389510640734;
   fWeightMatrix0to1[3][20] = -1.57018126860853;
   fWeightMatrix0to1[4][20] = -0.662059589993751;
   fWeightMatrix0to1[5][20] = -2.16992077798569;
   fWeightMatrix0to1[6][20] = 0.496896112187268;
   fWeightMatrix0to1[7][20] = 1.04112869156033;
   fWeightMatrix0to1[8][20] = 1.56851180824625;
   fWeightMatrix0to1[9][20] = 1.41118289721643;
   fWeightMatrix0to1[10][20] = -1.75719234475089;
   fWeightMatrix0to1[11][20] = -0.661629545229606;
   fWeightMatrix0to1[12][20] = -1.50315203285015;
   fWeightMatrix0to1[13][20] = 0.355573410334848;
   fWeightMatrix0to1[14][20] = 1.94138237279439;
   fWeightMatrix0to1[15][20] = -2.44335408022214;
   fWeightMatrix0to1[16][20] = 0.822676082159536;
   fWeightMatrix0to1[17][20] = 0.0980550494257952;
   fWeightMatrix0to1[18][20] = -1.29146675235629;
   fWeightMatrix0to1[19][20] = -0.757054280160929;
   fWeightMatrix0to1[20][20] = 1.80322049347317;
   fWeightMatrix0to1[21][20] = 0.238840711035113;
   fWeightMatrix0to1[22][20] = 1.85739329484148;
   fWeightMatrix0to1[23][20] = 0.150154119934761;
   fWeightMatrix0to1[24][20] = 1.16118180307104;
   fWeightMatrix0to1[25][20] = 0.424703232356186;
   fWeightMatrix0to1[26][20] = 0.16753818281475;
   fWeightMatrix0to1[27][20] = -2.18296445615479;
   fWeightMatrix0to1[28][20] = -0.84342268735488;
   fWeightMatrix0to1[29][20] = -2.11511949045995;
   fWeightMatrix0to1[30][20] = 1.06237187108152;
   fWeightMatrix0to1[31][20] = 0.923136050176561;
   fWeightMatrix0to1[32][20] = -0.00891367420437506;
   fWeightMatrix0to1[0][21] = 0.721335451251255;
   fWeightMatrix0to1[1][21] = 1.6219205888548;
   fWeightMatrix0to1[2][21] = -0.768824169527279;
   fWeightMatrix0to1[3][21] = 1.33979059561764;
   fWeightMatrix0to1[4][21] = 1.74766751758474;
   fWeightMatrix0to1[5][21] = -1.96105039294876;
   fWeightMatrix0to1[6][21] = 0.393699561243246;
   fWeightMatrix0to1[7][21] = 0.54220016393548;
   fWeightMatrix0to1[8][21] = 1.89130068152987;
   fWeightMatrix0to1[9][21] = 1.25708293903601;
   fWeightMatrix0to1[10][21] = -0.284444872344109;
   fWeightMatrix0to1[11][21] = -0.567340738664875;
   fWeightMatrix0to1[12][21] = -1.44930692034519;
   fWeightMatrix0to1[13][21] = -0.0894464501249267;
   fWeightMatrix0to1[14][21] = -0.889235296325871;
   fWeightMatrix0to1[15][21] = -0.198934768380146;
   fWeightMatrix0to1[16][21] = 0.0921481079530471;
   fWeightMatrix0to1[17][21] = -0.157564730692954;
   fWeightMatrix0to1[18][21] = -0.0675350855691573;
   fWeightMatrix0to1[19][21] = 1.64150684982026;
   fWeightMatrix0to1[20][21] = 0.522130321632463;
   fWeightMatrix0to1[21][21] = -0.625676088245508;
   fWeightMatrix0to1[22][21] = 0.483865365399511;
   fWeightMatrix0to1[23][21] = 2.17103195444512;
   fWeightMatrix0to1[24][21] = -0.658418930899269;
   fWeightMatrix0to1[25][21] = 1.97879526790994;
   fWeightMatrix0to1[26][21] = -0.906828642446221;
   fWeightMatrix0to1[27][21] = -1.78287370539048;
   fWeightMatrix0to1[28][21] = 2.99572487108512;
   fWeightMatrix0to1[29][21] = -2.74539586918477;
   fWeightMatrix0to1[30][21] = -0.383257909165821;
   fWeightMatrix0to1[31][21] = 2.10062368560346;
   fWeightMatrix0to1[32][21] = -0.690003124158622;
   fWeightMatrix0to1[0][22] = 0.522710934087747;
   fWeightMatrix0to1[1][22] = -0.330661484155864;
   fWeightMatrix0to1[2][22] = 1.84865062929309;
   fWeightMatrix0to1[3][22] = 2.1552567985669;
   fWeightMatrix0to1[4][22] = 1.2241866749892;
   fWeightMatrix0to1[5][22] = 0.107922431462261;
   fWeightMatrix0to1[6][22] = 1.3665230324268;
   fWeightMatrix0to1[7][22] = 1.86683600372969;
   fWeightMatrix0to1[8][22] = -0.00944751243634683;
   fWeightMatrix0to1[9][22] = 0.249800387631523;
   fWeightMatrix0to1[10][22] = -1.83065093012845;
   fWeightMatrix0to1[11][22] = 3.92118834486207;
   fWeightMatrix0to1[12][22] = -0.232565634672143;
   fWeightMatrix0to1[13][22] = 0.589186160572823;
   fWeightMatrix0to1[14][22] = -3.18415501244112;
   fWeightMatrix0to1[15][22] = 1.87632331077013;
   fWeightMatrix0to1[16][22] = -2.10086620071142;
   fWeightMatrix0to1[17][22] = -0.918435031625097;
   fWeightMatrix0to1[18][22] = -0.0150017448383682;
   fWeightMatrix0to1[19][22] = 1.09157930465466;
   fWeightMatrix0to1[20][22] = 2.41034900291686;
   fWeightMatrix0to1[21][22] = 0.176438484975736;
   fWeightMatrix0to1[22][22] = -1.65839825111567;
   fWeightMatrix0to1[23][22] = 0.562073535691624;
   fWeightMatrix0to1[24][22] = -0.967508284582364;
   fWeightMatrix0to1[25][22] = 1.74178529036389;
   fWeightMatrix0to1[26][22] = 1.13308567584906;
   fWeightMatrix0to1[27][22] = 0.0214895509725888;
   fWeightMatrix0to1[28][22] = 1.61929145812316;
   fWeightMatrix0to1[29][22] = -0.0489328605598831;
   fWeightMatrix0to1[30][22] = -0.408267073612968;
   fWeightMatrix0to1[31][22] = 0.492741413128553;
   fWeightMatrix0to1[32][22] = -1.28261391911525;
   fWeightMatrix0to1[0][23] = 0.170584333627326;
   fWeightMatrix0to1[1][23] = 0.640589226065715;
   fWeightMatrix0to1[2][23] = -0.0418877351905629;
   fWeightMatrix0to1[3][23] = -0.545826474063326;
   fWeightMatrix0to1[4][23] = -1.41683758614028;
   fWeightMatrix0to1[5][23] = 3.37927630037147;
   fWeightMatrix0to1[6][23] = -1.0905346691539;
   fWeightMatrix0to1[7][23] = -1.03758101992196;
   fWeightMatrix0to1[8][23] = 1.17736258388914;
   fWeightMatrix0to1[9][23] = -1.8189314647557;
   fWeightMatrix0to1[10][23] = -5.05013204479207;
   fWeightMatrix0to1[11][23] = -2.87698868021729;
   fWeightMatrix0to1[12][23] = 1.69438841259125;
   fWeightMatrix0to1[13][23] = -0.552963430634686;
   fWeightMatrix0to1[14][23] = 3.11273335137186;
   fWeightMatrix0to1[15][23] = 0.00864464670018626;
   fWeightMatrix0to1[16][23] = -1.33470804139085;
   fWeightMatrix0to1[17][23] = -2.97998249510458;
   fWeightMatrix0to1[18][23] = 0.79037825042971;
   fWeightMatrix0to1[19][23] = 0.088208837857953;
   fWeightMatrix0to1[20][23] = 0.22717970156495;
   fWeightMatrix0to1[21][23] = -1.92566834273496;
   fWeightMatrix0to1[22][23] = 0.753465838066555;
   fWeightMatrix0to1[23][23] = -0.707318537920986;
   fWeightMatrix0to1[24][23] = -6.00021503335243;
   fWeightMatrix0to1[25][23] = -0.161818245108442;
   fWeightMatrix0to1[26][23] = 4.41253268380276;
   fWeightMatrix0to1[27][23] = -2.60395351429758;
   fWeightMatrix0to1[28][23] = 0.210993910597143;
   fWeightMatrix0to1[29][23] = 0.551325907731379;
   fWeightMatrix0to1[30][23] = -3.08851238222774;
   fWeightMatrix0to1[31][23] = 1.83804901513349;
   fWeightMatrix0to1[32][23] = -1.37599638071955;
   fWeightMatrix0to1[0][24] = -0.545726640815771;
   fWeightMatrix0to1[1][24] = -1.90536074477136;
   fWeightMatrix0to1[2][24] = 1.76177536257303;
   fWeightMatrix0to1[3][24] = -0.840643841139005;
   fWeightMatrix0to1[4][24] = 1.02426538101899;
   fWeightMatrix0to1[5][24] = 1.50240091176642;
   fWeightMatrix0to1[6][24] = 0.0738217991569718;
   fWeightMatrix0to1[7][24] = -0.738624010892067;
   fWeightMatrix0to1[8][24] = 1.4715891453633;
   fWeightMatrix0to1[9][24] = 1.95087780173836;
   fWeightMatrix0to1[10][24] = 0.49046053933625;
   fWeightMatrix0to1[11][24] = 0.499286527601266;
   fWeightMatrix0to1[12][24] = -1.3241748806977;
   fWeightMatrix0to1[13][24] = -1.21164973409666;
   fWeightMatrix0to1[14][24] = -1.52817980725585;
   fWeightMatrix0to1[15][24] = -0.845066105975322;
   fWeightMatrix0to1[16][24] = -0.0803246742608519;
   fWeightMatrix0to1[17][24] = 0.70044100874208;
   fWeightMatrix0to1[18][24] = 0.463317979829405;
   fWeightMatrix0to1[19][24] = 1.90727115192377;
   fWeightMatrix0to1[20][24] = -0.879736004964743;
   fWeightMatrix0to1[21][24] = -0.278520179260186;
   fWeightMatrix0to1[22][24] = -0.633850560923976;
   fWeightMatrix0to1[23][24] = 0.739342754833791;
   fWeightMatrix0to1[24][24] = 0.100387269231369;
   fWeightMatrix0to1[25][24] = -0.153469263688167;
   fWeightMatrix0to1[26][24] = -1.92053927521866;
   fWeightMatrix0to1[27][24] = 0.501865481764159;
   fWeightMatrix0to1[28][24] = -1.17083382455972;
   fWeightMatrix0to1[29][24] = 0.0225717341264672;
   fWeightMatrix0to1[30][24] = 1.11461113547818;
   fWeightMatrix0to1[31][24] = -1.5567984034595;
   fWeightMatrix0to1[32][24] = 1.15873718340602;
   fWeightMatrix0to1[0][25] = -0.991056837811644;
   fWeightMatrix0to1[1][25] = 1.08698630383003;
   fWeightMatrix0to1[2][25] = 0.478098997200562;
   fWeightMatrix0to1[3][25] = -1.31218527901773;
   fWeightMatrix0to1[4][25] = 0.954212254133137;
   fWeightMatrix0to1[5][25] = -1.64905242877095;
   fWeightMatrix0to1[6][25] = 1.81913460239734;
   fWeightMatrix0to1[7][25] = 2.24539891071753;
   fWeightMatrix0to1[8][25] = 1.80230582401357;
   fWeightMatrix0to1[9][25] = -1.05275471881988;
   fWeightMatrix0to1[10][25] = 2.11019245277663;
   fWeightMatrix0to1[11][25] = 1.16573982446019;
   fWeightMatrix0to1[12][25] = 1.39259491628036;
   fWeightMatrix0to1[13][25] = -2.01876495850271;
   fWeightMatrix0to1[14][25] = -1.00149991015268;
   fWeightMatrix0to1[15][25] = -0.778919043661605;
   fWeightMatrix0to1[16][25] = 0.723697062756954;
   fWeightMatrix0to1[17][25] = 0.0661147185813105;
   fWeightMatrix0to1[18][25] = -2.18786631145224;
   fWeightMatrix0to1[19][25] = -0.899499876749006;
   fWeightMatrix0to1[20][25] = -0.486331300474419;
   fWeightMatrix0to1[21][25] = -1.28408910891303;
   fWeightMatrix0to1[22][25] = -0.506799493786024;
   fWeightMatrix0to1[23][25] = 0.346169406312929;
   fWeightMatrix0to1[24][25] = -0.800689234248264;
   fWeightMatrix0to1[25][25] = -1.46622250446442;
   fWeightMatrix0to1[26][25] = 0.339871583320274;
   fWeightMatrix0to1[27][25] = -3.79480453314296;
   fWeightMatrix0to1[28][25] = 1.62564735304836;
   fWeightMatrix0to1[29][25] = 0.048328892372056;
   fWeightMatrix0to1[30][25] = 0.676150465661708;
   fWeightMatrix0to1[31][25] = -0.78959310301217;
   fWeightMatrix0to1[32][25] = 0.577549883535748;
   fWeightMatrix0to1[0][26] = 0.579307027443063;
   fWeightMatrix0to1[1][26] = -0.615246863759271;
   fWeightMatrix0to1[2][26] = -0.1753341838287;
   fWeightMatrix0to1[3][26] = 3.21559688221676;
   fWeightMatrix0to1[4][26] = -0.448827715431989;
   fWeightMatrix0to1[5][26] = 0.541802880718297;
   fWeightMatrix0to1[6][26] = 1.09654216588672;
   fWeightMatrix0to1[7][26] = -0.942795302211098;
   fWeightMatrix0to1[8][26] = 1.93916981101891;
   fWeightMatrix0to1[9][26] = -2.98553851290127;
   fWeightMatrix0to1[10][26] = 0.70162571688706;
   fWeightMatrix0to1[11][26] = 4.06294219318953;
   fWeightMatrix0to1[12][26] = 0.522657116303125;
   fWeightMatrix0to1[13][26] = 3.9832855287079;
   fWeightMatrix0to1[14][26] = -0.671120575031436;
   fWeightMatrix0to1[15][26] = 1.24736906105253;
   fWeightMatrix0to1[16][26] = -3.0879626793496;
   fWeightMatrix0to1[17][26] = 0.706389060977205;
   fWeightMatrix0to1[18][26] = 0.658113627062671;
   fWeightMatrix0to1[19][26] = -5.24374268405236;
   fWeightMatrix0to1[20][26] = -1.07979566275039;
   fWeightMatrix0to1[21][26] = 3.23059835433788;
   fWeightMatrix0to1[22][26] = 1.8670402301414;
   fWeightMatrix0to1[23][26] = 0.151138877905357;
   fWeightMatrix0to1[24][26] = -0.222601597240134;
   fWeightMatrix0to1[25][26] = -0.546344979980428;
   fWeightMatrix0to1[26][26] = 0.0954431768980833;
   fWeightMatrix0to1[27][26] = -2.21407571146535;
   fWeightMatrix0to1[28][26] = -2.29318831505856;
   fWeightMatrix0to1[29][26] = 1.1898414545993;
   fWeightMatrix0to1[30][26] = 2.38741209335075;
   fWeightMatrix0to1[31][26] = 1.90254368989425;
   fWeightMatrix0to1[32][26] = 0.460312674155685;
   fWeightMatrix0to1[0][27] = 1.1336167480626;
   fWeightMatrix0to1[1][27] = 4.67895770238236;
   fWeightMatrix0to1[2][27] = -0.342225157754801;
   fWeightMatrix0to1[3][27] = 2.1169596309651;
   fWeightMatrix0to1[4][27] = -1.1604634514571;
   fWeightMatrix0to1[5][27] = -1.48601705159514;
   fWeightMatrix0to1[6][27] = -0.885403268873751;
   fWeightMatrix0to1[7][27] = -1.1205797740121;
   fWeightMatrix0to1[8][27] = 1.39361850264646;
   fWeightMatrix0to1[9][27] = -1.1928739695741;
   fWeightMatrix0to1[10][27] = 1.26101041682553;
   fWeightMatrix0to1[11][27] = -0.950000293913512;
   fWeightMatrix0to1[12][27] = 0.754845794276627;
   fWeightMatrix0to1[13][27] = 2.10214967750523;
   fWeightMatrix0to1[14][27] = 7.00492940256676;
   fWeightMatrix0to1[15][27] = 1.42357598456319;
   fWeightMatrix0to1[16][27] = 0.939463607189681;
   fWeightMatrix0to1[17][27] = 1.25392330109275;
   fWeightMatrix0to1[18][27] = 0.235594007203887;
   fWeightMatrix0to1[19][27] = -3.66123042318916;
   fWeightMatrix0to1[20][27] = -0.915087110176125;
   fWeightMatrix0to1[21][27] = 1.85663763136815;
   fWeightMatrix0to1[22][27] = 2.28649276757193;
   fWeightMatrix0to1[23][27] = -0.643020929232935;
   fWeightMatrix0to1[24][27] = -0.0667680435579067;
   fWeightMatrix0to1[25][27] = -0.508961590813782;
   fWeightMatrix0to1[26][27] = 0.395025966732473;
   fWeightMatrix0to1[27][27] = -2.79411144477311;
   fWeightMatrix0to1[28][27] = -0.51147010432264;
   fWeightMatrix0to1[29][27] = -8.79820581401034;
   fWeightMatrix0to1[30][27] = 1.97007820449676;
   fWeightMatrix0to1[31][27] = 1.47790648792989;
   fWeightMatrix0to1[32][27] = 1.71495940910989;
   fWeightMatrix0to1[0][28] = -0.81559451877208;
   fWeightMatrix0to1[1][28] = 0.477329010462808;
   fWeightMatrix0to1[2][28] = -0.67390255915957;
   fWeightMatrix0to1[3][28] = 0.27251150753906;
   fWeightMatrix0to1[4][28] = 2.30513597877354;
   fWeightMatrix0to1[5][28] = 0.593471647632581;
   fWeightMatrix0to1[6][28] = -1.42189995100228;
   fWeightMatrix0to1[7][28] = -1.30596827849209;
   fWeightMatrix0to1[8][28] = 2.43432261739507;
   fWeightMatrix0to1[9][28] = 1.00656936449911;
   fWeightMatrix0to1[10][28] = -2.47810875287334;
   fWeightMatrix0to1[11][28] = 1.32453216619124;
   fWeightMatrix0to1[12][28] = 0.00497885281568943;
   fWeightMatrix0to1[13][28] = -0.557308657908183;
   fWeightMatrix0to1[14][28] = -2.57468304445837;
   fWeightMatrix0to1[15][28] = 1.59714722534649;
   fWeightMatrix0to1[16][28] = 2.06938334204985;
   fWeightMatrix0to1[17][28] = -2.05608150333851;
   fWeightMatrix0to1[18][28] = -3.55895986676355;
   fWeightMatrix0to1[19][28] = 1.72915921936128;
   fWeightMatrix0to1[20][28] = -0.795590391107591;
   fWeightMatrix0to1[21][28] = -1.17598429194041;
   fWeightMatrix0to1[22][28] = -0.575735499906334;
   fWeightMatrix0to1[23][28] = -6.03491164065747;
   fWeightMatrix0to1[24][28] = -0.746239197841798;
   fWeightMatrix0to1[25][28] = 0.721267228144342;
   fWeightMatrix0to1[26][28] = 0.442250388883261;
   fWeightMatrix0to1[27][28] = 0.238046262978394;
   fWeightMatrix0to1[28][28] = 1.47181589245847;
   fWeightMatrix0to1[29][28] = 9.21368907010436;
   fWeightMatrix0to1[30][28] = 1.09049230309618;
   fWeightMatrix0to1[31][28] = -0.288557165990716;
   fWeightMatrix0to1[32][28] = -2.38988079552486;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.398291530860151;
   fWeightMatrix1to2[0][1] = -0.481115499332669;
   fWeightMatrix1to2[0][2] = -3.25713499955866;
   fWeightMatrix1to2[0][3] = 0.422429037665006;
   fWeightMatrix1to2[0][4] = 0.370229234529491;
   fWeightMatrix1to2[0][5] = 0.683425302041898;
   fWeightMatrix1to2[0][6] = 2.83092495089226;
   fWeightMatrix1to2[0][7] = -3.59414328612834;
   fWeightMatrix1to2[0][8] = -0.505774706152843;
   fWeightMatrix1to2[0][9] = 3.72777955855675;
   fWeightMatrix1to2[0][10] = 0.438395570565938;
   fWeightMatrix1to2[0][11] = 0.620433937703928;
   fWeightMatrix1to2[0][12] = 0.70299901666245;
   fWeightMatrix1to2[0][13] = 0.38541323219068;
   fWeightMatrix1to2[0][14] = -0.993991789293816;
   fWeightMatrix1to2[0][15] = -1.77210719717101;
   fWeightMatrix1to2[0][16] = -1.5956335238477;
   fWeightMatrix1to2[0][17] = -1.46639488697194;
   fWeightMatrix1to2[0][18] = 0.763889661778093;
   fWeightMatrix1to2[0][19] = 1.46924953477172;
   fWeightMatrix1to2[0][20] = 0.26645620290536;
   fWeightMatrix1to2[0][21] = -2.25619088904035;
   fWeightMatrix1to2[0][22] = 2.12877633856261;
   fWeightMatrix1to2[0][23] = 0.536810825576617;
   fWeightMatrix1to2[0][24] = 1.14964544782918;
   fWeightMatrix1to2[0][25] = 4.01055465617979;
   fWeightMatrix1to2[0][26] = -0.380970343872729;
   fWeightMatrix1to2[0][27] = 0.332107734528331;
   fWeightMatrix1to2[0][28] = -3.43110380094243;
   fWeightMatrix1to2[0][29] = -1.17606656173141;
   fWeightMatrix1to2[0][30] = 2.52495996241959;
   fWeightMatrix1to2[0][31] = 0.428798518059105;
   fWeightMatrix1to2[0][32] = -2.99736451247811;
   fWeightMatrix1to2[0][33] = 0.836933135408131;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 12;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 13;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 13;
   fMin_1[0][1] = 3;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 3;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 3;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 7;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 8;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 8;
   fMin_1[0][3] = 0.0348501950502;
   fMax_1[0][3] = 357.257141113;
   fMin_1[1][3] = 0.106996804476;
   fMax_1[1][3] = 369.078704834;
   fMin_1[2][3] = 0.0348501950502;
   fMax_1[2][3] = 369.078704834;
   fMin_1[0][4] = -3.14109992981;
   fMax_1[0][4] = 3.14153575897;
   fMin_1[1][4] = -3.14140152931;
   fMax_1[1][4] = 3.14062786102;
   fMin_1[2][4] = -3.14140152931;
   fMax_1[2][4] = 3.14153575897;
   fMin_1[0][5] = 0.37144780159;
   fMax_1[0][5] = 671.120422363;
   fMin_1[1][5] = 0.332486361265;
   fMax_1[1][5] = 566.580749512;
   fMin_1[2][5] = 0.332486361265;
   fMax_1[2][5] = 671.120422363;
   fMin_1[0][6] = 0.388728410006;
   fMax_1[0][6] = 3.48090934753;
   fMin_1[1][6] = 0.399907410145;
   fMax_1[1][6] = 3.32630109787;
   fMin_1[2][6] = 0.388728410006;
   fMax_1[2][6] = 3.48090934753;
   fMin_1[0][7] = 4.95910644531e-05;
   fMax_1[0][7] = 3.13447403908;
   fMin_1[1][7] = 2.89678573608e-05;
   fMax_1[1][7] = 3.13183999062;
   fMin_1[2][7] = 2.89678573608e-05;
   fMax_1[2][7] = 3.13447403908;
   fMin_1[0][8] = 2.39163637161e-05;
   fMax_1[0][8] = 6.27293777466;
   fMin_1[1][8] = 0.000352144241333;
   fMax_1[1][8] = 6.24672985077;
   fMin_1[2][8] = 2.39163637161e-05;
   fMax_1[2][8] = 6.27293777466;
   fMin_1[0][9] = 19.4228515625;
   fMax_1[0][9] = 809.097412109;
   fMin_1[1][9] = 18.3813915253;
   fMax_1[1][9] = 1218.23632812;
   fMin_1[2][9] = 18.3813915253;
   fMax_1[2][9] = 1218.23632812;
   fMin_1[0][10] = 30.3176345825;
   fMax_1[0][10] = 1400.890625;
   fMin_1[1][10] = 30.4168453217;
   fMax_1[1][10] = 1166.04785156;
   fMin_1[2][10] = 30.3176345825;
   fMax_1[2][10] = 1400.890625;
   fMin_1[0][11] = 31.2792739868;
   fMax_1[0][11] = 1267.67236328;
   fMin_1[1][11] = 32.6458206177;
   fMax_1[1][11] = 1402.21191406;
   fMin_1[2][11] = 31.2792739868;
   fMax_1[2][11] = 1402.21191406;
   fMin_1[0][12] = 33.7081336975;
   fMax_1[0][12] = 1400.890625;
   fMin_1[1][12] = 37.2772979736;
   fMax_1[1][12] = 1402.21191406;
   fMin_1[2][12] = 33.7081336975;
   fMax_1[2][12] = 1402.21191406;
   fMin_1[0][13] = 31.1904850006;
   fMax_1[0][13] = 1149.72290039;
   fMin_1[1][13] = 32.6458206177;
   fMax_1[1][13] = 763.240661621;
   fMin_1[2][13] = 31.1904850006;
   fMax_1[2][13] = 1149.72290039;
   fMin_1[0][14] = 30.1826877594;
   fMax_1[0][14] = 433.978668213;
   fMin_1[1][14] = 30.3089332581;
   fMax_1[1][14] = 476.129394531;
   fMin_1[2][14] = 30.1826877594;
   fMax_1[2][14] = 476.129394531;
   fMin_1[0][15] = 30.0017719269;
   fMax_1[0][15] = 255.48236084;
   fMin_1[1][15] = 30.0096645355;
   fMax_1[1][15] = 301.51852417;
   fMin_1[2][15] = 30.0017719269;
   fMax_1[2][15] = 301.51852417;
   fMin_1[0][16] = 0.0443393550813;
   fMax_1[0][16] = 0.999611914158;
   fMin_1[1][16] = 0.0492535606027;
   fMax_1[1][16] = 0.999404430389;
   fMin_1[2][16] = 0.0443393550813;
   fMax_1[2][16] = 0.999611914158;
   fMin_1[0][17] = 0.0408265255392;
   fMax_1[0][17] = 0.999617695808;
   fMin_1[1][17] = 0.041913960129;
   fMax_1[1][17] = 0.99962580204;
   fMin_1[2][17] = 0.0408265255392;
   fMax_1[2][17] = 0.99962580204;
   fMin_1[0][18] = 0.0482494644821;
   fMax_1[0][18] = 0.999607205391;
   fMin_1[1][18] = 0.0471053086221;
   fMax_1[1][18] = 0.999616205692;
   fMin_1[2][18] = 0.0471053086221;
   fMax_1[2][18] = 0.999616205692;
   fMin_1[0][19] = 0.0470969378948;
   fMax_1[0][19] = 0.999558746815;
   fMin_1[1][19] = 0.0474232248962;
   fMax_1[1][19] = 0.999606192112;
   fMin_1[2][19] = 0.0470969378948;
   fMax_1[2][19] = 0.999606192112;
   fMin_1[0][20] = -24.594379425;
   fMax_1[0][20] = 413.393310547;
   fMin_1[1][20] = 3.29525971413;
   fMax_1[1][20] = 559.032531738;
   fMin_1[2][20] = -24.594379425;
   fMax_1[2][20] = 559.032531738;
   fMin_1[0][21] = 8.81959342957;
   fMax_1[0][21] = 413.393310547;
   fMin_1[1][21] = 5.32452011108;
   fMax_1[1][21] = 559.032531738;
   fMin_1[2][21] = 5.32452011108;
   fMax_1[2][21] = 559.032531738;
   fMin_1[0][22] = 0;
   fMax_1[0][22] = 95.7668457031;
   fMin_1[1][22] = 0;
   fMax_1[1][22] = 88.5530014038;
   fMin_1[2][22] = 0;
   fMax_1[2][22] = 95.7668457031;
   fMin_1[0][23] = 0;
   fMax_1[0][23] = 175.345123291;
   fMin_1[1][23] = 0;
   fMax_1[1][23] = 177.754180908;
   fMin_1[2][23] = 0;
   fMax_1[2][23] = 177.754180908;
   fMin_1[0][24] = -202.563400269;
   fMax_1[0][24] = 525.054321289;
   fMin_1[1][24] = -267.692596436;
   fMax_1[1][24] = 678.751220703;
   fMin_1[2][24] = -267.692596436;
   fMax_1[2][24] = 678.751220703;
   fMin_1[0][25] = 1.6611661911;
   fMax_1[0][25] = 525.054321289;
   fMin_1[1][25] = 1.50358843803;
   fMax_1[1][25] = 678.751220703;
   fMin_1[2][25] = 1.50358843803;
   fMax_1[2][25] = 678.751220703;
   fMin_1[0][26] = 0;
   fMax_1[0][26] = 138.089294434;
   fMin_1[1][26] = 0;
   fMax_1[1][26] = 138.071853638;
   fMin_1[2][26] = 0;
   fMax_1[2][26] = 138.089294434;
   fMin_1[0][27] = 0;
   fMax_1[0][27] = 1501.63049316;
   fMin_1[1][27] = 0;
   fMax_1[1][27] = 880.89263916;
   fMin_1[2][27] = 0;
   fMax_1[2][27] = 1501.63049316;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 28;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
      indicesGet.push_back( 20);
      indicesGet.push_back( 21);
      indicesGet.push_back( 22);
      indicesGet.push_back( 23);
      indicesGet.push_back( 24);
      indicesGet.push_back( 25);
      indicesGet.push_back( 26);
      indicesGet.push_back( 27);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
      indicesPut.push_back( 20);
      indicesPut.push_back( 21);
      indicesPut.push_back( 22);
      indicesPut.push_back( 23);
      indicesPut.push_back( 24);
      indicesPut.push_back( 25);
      indicesPut.push_back( 26);
      indicesPut.push_back( 27);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<28;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
