// Class: ReadDNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : DNN::DNN
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Tue Jul  4 23:38:34 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/analysis_jw/tmva/v1
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|30,TANH|20,LINEAR" [Layou of the network.]
ErrorStrategy: "CROSSENTROPY" [Loss function: Mean squared error (regression) or cross entropy (binary classifcation).]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
TrainingStrategy: "LearningRate=0.01,Momentum=0.4,Repetitions=1,ConvergenceSteps=300,BatchSize=100,DropConfig=0.0+0.2+0.0,WeightDecay=0.001,Regularization=L2,TestRepetitions=5,Multithreading=True" [Defines the training strategies.]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Architecture: "STANDARD" [Which architecture to perfrom the training on.]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 28
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,13]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [3,6]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,8]
Transvers_Mass                Transvers_Mass                Transvers_Mass                Transvers_Mass                                                  'F'    [0.0348501950502,369.078704834]
Lepton_DPhi                   Lepton_DPhi                   Lepton_DPhi                   Lepton_DPhi                                                     'F'    [-3.14140152931,3.14153575897]
Missing_ET                    Missing_ET                    Missing_ET                    Missing_ET                                                      'F'    [0.332486361265,671.120422363]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.388728410006,3.48090934753]
BJet_M_delta_Eta              BJet_M_delta_Eta              BJet_M_delta_Eta              BJet_M_delta_Eta                                                'F'    [2.89678573608e-05,3.13447403908]
BJet_M_delta_Phi              BJet_M_delta_Phi              BJet_M_delta_Phi              BJet_M_delta_Phi                                                'F'    [2.39163637161e-05,6.27293777466]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [18.3813915253,1218.23632812]
BJet_Pt_H                     BJet_Pt_H                     BJet_Pt_H                     BJet_Pt_H                                                       'F'    [30.3176345825,1400.890625]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [31.2792739868,1402.21191406]
Jet1_Pt                       Jet1_Pt                       Jet1_Pt                       Jet1_Pt                                                         'F'    [33.7081336975,1402.21191406]
Jet2_Pt                       Jet2_Pt                       Jet2_Pt                       Jet2_Pt                                                         'F'    [31.1904850006,1149.72290039]
Jet3_Pt                       Jet3_Pt                       Jet3_Pt                       Jet3_Pt                                                         'F'    [30.1826877594,476.129394531]
Jet4_Pt                       Jet4_Pt                       Jet4_Pt                       Jet4_Pt                                                         'F'    [30.0017719269,301.51852417]
Jet1_CSV                      Jet1_CSV                      Jet1_CSV                      Jet1_CSV                                                        'F'    [0.0443393550813,0.999611914158]
Jet2_CSV                      Jet2_CSV                      Jet2_CSV                      Jet2_CSV                                                        'F'    [0.0408265255392,0.99962580204]
Jet3_CSV                      Jet3_CSV                      Jet3_CSV                      Jet3_CSV                                                        'F'    [0.0471053086221,0.999616205692]
Jet4_CSV                      Jet4_CSV                      Jet4_CSV                      Jet4_CSV                                                        'F'    [0.0470969378948,0.999606192112]
Kin_Lep_WMass                 Kin_Lep_WMass                 Kin_Lep_WMass                 Kin_Lep_WMass                                                   'F'    [-24.594379425,559.032531738]
Kin_Lep_TopMass               Kin_Lep_TopMass               Kin_Lep_TopMass               Kin_Lep_TopMass                                                 'F'    [5.32452011108,559.032531738]
Kin_Had_WMass                 Kin_Had_WMass                 Kin_Had_WMass                 Kin_Had_WMass                                                   'F'    [0,95.7668457031]
Kin_Had_TopMass               Kin_Had_TopMass               Kin_Had_TopMass               Kin_Had_TopMass                                                 'F'    [0,177.754180908]
fcnhKin_Lep_WMass             fcnhKin_Lep_WMass             fcnhKin_Lep_WMass             fcnhKin_Lep_WMass                                               'F'    [-267.692596436,678.751220703]
fcnhKin_Lep_TopMass           fcnhKin_Lep_TopMass           fcnhKin_Lep_TopMass           fcnhKin_Lep_TopMass                                             'F'    [1.50358843803,678.751220703]
fcnhKin_HMass                 fcnhKin_HMass                 fcnhKin_HMass                 fcnhKin_HMass                                                   'F'    [0,138.089294434]
fcnhKin_Huc_TopMass           fcnhKin_Huc_TopMass           fcnhKin_Huc_TopMass           fcnhKin_Huc_TopMass                                             'F'    [0,1501.63049316]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDNN : public IClassifierReader {

 public:

   // constructor
   ReadDNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadDNN" ),
        fNvars( 28 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "Transvers_Mass", "Lepton_DPhi", "Missing_ET", "BJet_M_delta_R", "BJet_M_delta_Eta", "BJet_M_delta_Phi", "H_Mass", "BJet_Pt_H", "CJet_Pt", "Jet1_Pt", "Jet2_Pt", "Jet3_Pt", "Jet4_Pt", "Jet1_CSV", "Jet2_CSV", "Jet3_CSV", "Jet4_CSV", "Kin_Lep_WMass", "Kin_Lep_TopMass", "Kin_Had_WMass", "Kin_Had_TopMass", "fcnhKin_Lep_WMass", "fcnhKin_Lep_TopMass", "fcnhKin_HMass", "fcnhKin_Huc_TopMass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.555555582046509;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.714285850524902;
      fVmin[3] = -0.999774694442749;
      fVmax[3] = 1.40607285499573;
      fVmin[4] = -0.998027801513672;
      fVmax[4] = 0.999710917472839;
      fVmin[5] = -0.992869853973389;
      fVmax[5] = 0.549082279205322;
      fVmin[6] = -0.988046944141388;
      fVmax[6] = 0.877346754074097;
      fVmin[7] = -0.999890029430389;
      fVmax[7] = 0.934100866317749;
      fVmin[8] = -0.99835079908371;
      fVmax[8] = 0.955153107643127;
      fVmin[9] = -0.996218740940094;
      fVmax[9] = 0.334717988967896;
      fVmin[10] = -0.999532639980316;
      fVmax[10] = 0.0913434028625488;
      fVmin[11] = -0.993268668651581;
      fVmax[11] = 0.277730941772461;
      fVmin[12] = -0.992325723171234;
      fVmax[12] = 0.276449084281921;
      fVmin[13] = -0.993108868598938;
      fVmax[13] = 0.12924063205719;
      fVmin[14] = -0.997958362102509;
      fVmax[14] = 0.921802043914795;
      fVmin[15] = -0.999673068523407;
      fVmax[15] = 0.667370915412903;
      fVmin[16] = -0.985146641731262;
      fVmax[16] = 0.999539852142334;
      fVmin[17] = -0.98082572221756;
      fVmax[17] = 1;
      fVmin[18] = -0.999711811542511;
      fVmax[18] = 0.999585866928101;
      fVmin[19] = -0.994408369064331;
      fVmax[19] = 0.999707698822021;
      fVmin[20] = -0.884678959846497;
      fVmax[20] = 0.340574026107788;
      fVmin[21] = -0.986515164375305;
      fVmax[21] = 0.304942727088928;
      fVmin[22] = -1;
      fVmax[22] = 0.821285724639893;
      fVmin[23] = -1;
      fVmax[23] = 0.974177360534668;
      fVmin[24] = -0.584818959236145;
      fVmax[24] = 0.609210968017578;
      fVmin[25] = -0.998839139938354;
      fVmax[25] = 0.453877925872803;
      fVmin[26] = -1;
      fVmax[26] = 0.999095916748047;
      fVmin[27] = -1;
      fVmax[27] = 0.0316100120544434;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][28];
   double fMax_1[3][28];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[28];
   double fVmax[28];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[28];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadDNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadDNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 12;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 13;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 13;
   fMin_1[0][1] = 3;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 3;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 3;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 7;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 8;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 8;
   fMin_1[0][3] = 0.0348501950502;
   fMax_1[0][3] = 357.257141113;
   fMin_1[1][3] = 0.106996804476;
   fMax_1[1][3] = 369.078704834;
   fMin_1[2][3] = 0.0348501950502;
   fMax_1[2][3] = 369.078704834;
   fMin_1[0][4] = -3.14109992981;
   fMax_1[0][4] = 3.14153575897;
   fMin_1[1][4] = -3.14140152931;
   fMax_1[1][4] = 3.14062786102;
   fMin_1[2][4] = -3.14140152931;
   fMax_1[2][4] = 3.14153575897;
   fMin_1[0][5] = 0.37144780159;
   fMax_1[0][5] = 671.120422363;
   fMin_1[1][5] = 0.332486361265;
   fMax_1[1][5] = 566.580749512;
   fMin_1[2][5] = 0.332486361265;
   fMax_1[2][5] = 671.120422363;
   fMin_1[0][6] = 0.388728410006;
   fMax_1[0][6] = 3.48090934753;
   fMin_1[1][6] = 0.399907410145;
   fMax_1[1][6] = 3.32630109787;
   fMin_1[2][6] = 0.388728410006;
   fMax_1[2][6] = 3.48090934753;
   fMin_1[0][7] = 4.95910644531e-05;
   fMax_1[0][7] = 3.13447403908;
   fMin_1[1][7] = 2.89678573608e-05;
   fMax_1[1][7] = 3.13183999062;
   fMin_1[2][7] = 2.89678573608e-05;
   fMax_1[2][7] = 3.13447403908;
   fMin_1[0][8] = 2.39163637161e-05;
   fMax_1[0][8] = 6.27293777466;
   fMin_1[1][8] = 0.000352144241333;
   fMax_1[1][8] = 6.24672985077;
   fMin_1[2][8] = 2.39163637161e-05;
   fMax_1[2][8] = 6.27293777466;
   fMin_1[0][9] = 19.4228515625;
   fMax_1[0][9] = 809.097412109;
   fMin_1[1][9] = 18.3813915253;
   fMax_1[1][9] = 1218.23632812;
   fMin_1[2][9] = 18.3813915253;
   fMax_1[2][9] = 1218.23632812;
   fMin_1[0][10] = 30.3176345825;
   fMax_1[0][10] = 1400.890625;
   fMin_1[1][10] = 30.4168453217;
   fMax_1[1][10] = 1166.04785156;
   fMin_1[2][10] = 30.3176345825;
   fMax_1[2][10] = 1400.890625;
   fMin_1[0][11] = 31.2792739868;
   fMax_1[0][11] = 1267.67236328;
   fMin_1[1][11] = 32.6458206177;
   fMax_1[1][11] = 1402.21191406;
   fMin_1[2][11] = 31.2792739868;
   fMax_1[2][11] = 1402.21191406;
   fMin_1[0][12] = 33.7081336975;
   fMax_1[0][12] = 1400.890625;
   fMin_1[1][12] = 37.2772979736;
   fMax_1[1][12] = 1402.21191406;
   fMin_1[2][12] = 33.7081336975;
   fMax_1[2][12] = 1402.21191406;
   fMin_1[0][13] = 31.1904850006;
   fMax_1[0][13] = 1149.72290039;
   fMin_1[1][13] = 32.6458206177;
   fMax_1[1][13] = 763.240661621;
   fMin_1[2][13] = 31.1904850006;
   fMax_1[2][13] = 1149.72290039;
   fMin_1[0][14] = 30.1826877594;
   fMax_1[0][14] = 433.978668213;
   fMin_1[1][14] = 30.3089332581;
   fMax_1[1][14] = 476.129394531;
   fMin_1[2][14] = 30.1826877594;
   fMax_1[2][14] = 476.129394531;
   fMin_1[0][15] = 30.0017719269;
   fMax_1[0][15] = 255.48236084;
   fMin_1[1][15] = 30.0096645355;
   fMax_1[1][15] = 301.51852417;
   fMin_1[2][15] = 30.0017719269;
   fMax_1[2][15] = 301.51852417;
   fMin_1[0][16] = 0.0443393550813;
   fMax_1[0][16] = 0.999611914158;
   fMin_1[1][16] = 0.0492535606027;
   fMax_1[1][16] = 0.999404430389;
   fMin_1[2][16] = 0.0443393550813;
   fMax_1[2][16] = 0.999611914158;
   fMin_1[0][17] = 0.0408265255392;
   fMax_1[0][17] = 0.999617695808;
   fMin_1[1][17] = 0.041913960129;
   fMax_1[1][17] = 0.99962580204;
   fMin_1[2][17] = 0.0408265255392;
   fMax_1[2][17] = 0.99962580204;
   fMin_1[0][18] = 0.0482494644821;
   fMax_1[0][18] = 0.999607205391;
   fMin_1[1][18] = 0.0471053086221;
   fMax_1[1][18] = 0.999616205692;
   fMin_1[2][18] = 0.0471053086221;
   fMax_1[2][18] = 0.999616205692;
   fMin_1[0][19] = 0.0470969378948;
   fMax_1[0][19] = 0.999558746815;
   fMin_1[1][19] = 0.0474232248962;
   fMax_1[1][19] = 0.999606192112;
   fMin_1[2][19] = 0.0470969378948;
   fMax_1[2][19] = 0.999606192112;
   fMin_1[0][20] = -24.594379425;
   fMax_1[0][20] = 413.393310547;
   fMin_1[1][20] = 3.29525971413;
   fMax_1[1][20] = 559.032531738;
   fMin_1[2][20] = -24.594379425;
   fMax_1[2][20] = 559.032531738;
   fMin_1[0][21] = 8.81959342957;
   fMax_1[0][21] = 413.393310547;
   fMin_1[1][21] = 5.32452011108;
   fMax_1[1][21] = 559.032531738;
   fMin_1[2][21] = 5.32452011108;
   fMax_1[2][21] = 559.032531738;
   fMin_1[0][22] = 0;
   fMax_1[0][22] = 95.7668457031;
   fMin_1[1][22] = 0;
   fMax_1[1][22] = 88.5530014038;
   fMin_1[2][22] = 0;
   fMax_1[2][22] = 95.7668457031;
   fMin_1[0][23] = 0;
   fMax_1[0][23] = 175.345123291;
   fMin_1[1][23] = 0;
   fMax_1[1][23] = 177.754180908;
   fMin_1[2][23] = 0;
   fMax_1[2][23] = 177.754180908;
   fMin_1[0][24] = -202.563400269;
   fMax_1[0][24] = 525.054321289;
   fMin_1[1][24] = -267.692596436;
   fMax_1[1][24] = 678.751220703;
   fMin_1[2][24] = -267.692596436;
   fMax_1[2][24] = 678.751220703;
   fMin_1[0][25] = 1.6611661911;
   fMax_1[0][25] = 525.054321289;
   fMin_1[1][25] = 1.50358843803;
   fMax_1[1][25] = 678.751220703;
   fMin_1[2][25] = 1.50358843803;
   fMax_1[2][25] = 678.751220703;
   fMin_1[0][26] = 0;
   fMax_1[0][26] = 138.089294434;
   fMin_1[1][26] = 0;
   fMax_1[1][26] = 138.071853638;
   fMin_1[2][26] = 0;
   fMax_1[2][26] = 138.089294434;
   fMin_1[0][27] = 0;
   fMax_1[0][27] = 1501.63049316;
   fMin_1[1][27] = 0;
   fMax_1[1][27] = 880.89263916;
   fMin_1[2][27] = 0;
   fMax_1[2][27] = 1501.63049316;
}

//_______________________________________________________________________
inline void ReadDNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 28;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
      indicesGet.push_back( 15);
      indicesGet.push_back( 16);
      indicesGet.push_back( 17);
      indicesGet.push_back( 18);
      indicesGet.push_back( 19);
      indicesGet.push_back( 20);
      indicesGet.push_back( 21);
      indicesGet.push_back( 22);
      indicesGet.push_back( 23);
      indicesGet.push_back( 24);
      indicesGet.push_back( 25);
      indicesGet.push_back( 26);
      indicesGet.push_back( 27);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
      indicesPut.push_back( 15);
      indicesPut.push_back( 16);
      indicesPut.push_back( 17);
      indicesPut.push_back( 18);
      indicesPut.push_back( 19);
      indicesPut.push_back( 20);
      indicesPut.push_back( 21);
      indicesPut.push_back( 22);
      indicesPut.push_back( 23);
      indicesPut.push_back( 24);
      indicesPut.push_back( 25);
      indicesPut.push_back( 26);
      indicesPut.push_back( 27);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<28;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadDNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
