// Class: ReadDNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : DNN::DNN
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Thu May 25 01:23:10 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva/v2/mkNtuple_v2
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|30,TANH|20,LINEAR" [Layou of the network.]
ErrorStrategy: "CROSSENTROPY" [Loss function: Mean squared error (regression) or cross entropy (binary classifcation).]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
TrainingStrategy: "LearningRate=0.01,Momentum=0.4,Repetitions=1,ConvergenceSteps=300,BatchSize=100,DropConfig=0.0+0.2+0.0,WeightDecay=0.001,Regularization=L2,TestRepetitions=5,Multithreading=True" [Defines the training strategies.]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Architecture: "STANDARD" [Which architecture to perfrom the training on.]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,13]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,7]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,10]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.396064758301,5.07587337494]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [17.3422145844,299.998291016]
BJet_Pt                       BJet_Pt                       BJet_Pt                       BJet_Pt                                                         'F'    [30.4308242798,299.903961182]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [30.4533519745,299.903961182]
Jet1_Pt                       Jet1_Pt                       Jet1_Pt                       Jet1_Pt                                                         'F'    [33.8219299316,299.983215332]
Jet2_Pt                       Jet2_Pt                       Jet2_Pt                       Jet2_Pt                                                         'F'    [31.1904850006,289.616546631]
Jet3_Pt                       Jet3_Pt                       Jet3_Pt                       Jet3_Pt                                                         'F'    [30.1238079071,260.883880615]
Jet4_Pt                       Jet4_Pt                       Jet4_Pt                       Jet4_Pt                                                         'F'    [30.0009651184,227.541931152]
Jet1_CSV                      Jet1_CSV                      Jet1_CSV                      Jet1_CSV                                                        'F'    [0.0351784825325,0.999602913857]
Jet2_CSV                      Jet2_CSV                      Jet2_CSV                      Jet2_CSV                                                        'F'    [0.0428134761751,1]
Jet3_CSV                      Jet3_CSV                      Jet3_CSV                      Jet3_CSV                                                        'F'    [0.0378077812493,0.999781787395]
Jet4_CSV                      Jet4_CSV                      Jet4_CSV                      Jet4_CSV                                                        'F'    [0.0469597056508,0.999630331993]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDNN : public IClassifierReader {

 public:

   // constructor
   ReadDNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadDNN" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJet_M_delta_R", "H_Mass", "BJet_Pt", "CJet_Pt", "Jet1_Pt", "Jet2_Pt", "Jet3_Pt", "Jet4_Pt", "Jet1_CSV", "Jet2_CSV", "Jet3_CSV", "Jet4_CSV" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.777777791023254;
      fVmin[1] = -1;
      fVmax[1] = 0.666666746139526;
      fVmin[2] = -1;
      fVmax[2] = 0.555555582046509;
      fVmin[3] = -0.996643483638763;
      fVmax[3] = 0.935463070869446;
      fVmin[4] = -0.990551710128784;
      fVmax[4] = 0.999513745307922;
      fVmin[5] = -0.999248802661896;
      fVmax[5] = 0.999540686607361;
      fVmin[6] = -0.994108915328979;
      fVmax[6] = 1.00052332878113;
      fVmin[7] = -0.971983134746552;
      fVmax[7] = 0.999934315681458;
      fVmin[8] = -0.996496438980103;
      fVmax[8] = 1.044349193573;
      fVmin[9] = -1.00005078315735;
      fVmax[9] = 0.93570339679718;
      fVmin[10] = -1;
      fVmax[10] = 0.937178492546082;
      fVmin[11] = -1.00184535980225;
      fVmax[11] = 0.999672055244446;
      fVmin[12] = -0.988905489444733;
      fVmax[12] = 0.999239325523376;
      fVmin[13] = -0.991477310657501;
      fVmax[13] = 0.999688863754272;
      fVmin[14] = -0.998343706130981;
      fVmax[14] = 0.999984383583069;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][15];
   double fMax_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadDNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadDNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 11;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 13;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 13;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 5;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 7;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 9;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 10;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 10;
   fMin_1[0][3] = 0.399108380079;
   fMax_1[0][3] = 4.68654870987;
   fMin_1[1][3] = 0.396064758301;
   fMax_1[1][3] = 5.07587337494;
   fMin_1[2][3] = 0.396064758301;
   fMax_1[2][3] = 5.07587337494;
   fMin_1[0][4] = 19.7999248505;
   fMax_1[0][4] = 299.975952148;
   fMin_1[1][4] = 17.3422145844;
   fMax_1[1][4] = 299.998291016;
   fMin_1[2][4] = 17.3422145844;
   fMax_1[2][4] = 299.998291016;
   fMin_1[0][5] = 30.4533519745;
   fMax_1[0][5] = 299.703308105;
   fMin_1[1][5] = 30.4308242798;
   fMax_1[1][5] = 299.903961182;
   fMin_1[2][5] = 30.4308242798;
   fMax_1[2][5] = 299.903961182;
   fMin_1[0][6] = 30.4533519745;
   fMax_1[0][6] = 299.703308105;
   fMin_1[1][6] = 31.5732555389;
   fMax_1[1][6] = 299.903961182;
   fMin_1[2][6] = 30.4533519745;
   fMax_1[2][6] = 299.903961182;
   fMin_1[0][7] = 33.8219299316;
   fMax_1[0][7] = 299.983215332;
   fMin_1[1][7] = 36.9922218323;
   fMax_1[1][7] = 299.940673828;
   fMin_1[2][7] = 33.8219299316;
   fMax_1[2][7] = 299.983215332;
   fMin_1[0][8] = 31.1904850006;
   fMax_1[0][8] = 288.066101074;
   fMin_1[1][8] = 31.8723602295;
   fMax_1[1][8] = 289.616546631;
   fMin_1[2][8] = 31.1904850006;
   fMax_1[2][8] = 289.616546631;
   fMin_1[0][9] = 30.1670379639;
   fMax_1[0][9] = 237.090316772;
   fMin_1[1][9] = 30.1238079071;
   fMax_1[1][9] = 260.883880615;
   fMin_1[2][9] = 30.1238079071;
   fMax_1[2][9] = 260.883880615;
   fMin_1[0][10] = 30.0009651184;
   fMax_1[0][10] = 187.586990356;
   fMin_1[1][10] = 30.0026092529;
   fMax_1[1][10] = 227.541931152;
   fMin_1[2][10] = 30.0009651184;
   fMax_1[2][10] = 227.541931152;
   fMin_1[0][11] = 0.0351784825325;
   fMax_1[0][11] = 0.999602913857;
   fMin_1[1][11] = 0.0368843339384;
   fMax_1[1][11] = 0.999452471733;
   fMin_1[2][11] = 0.0351784825325;
   fMax_1[2][11] = 0.999602913857;
   fMin_1[0][12] = 0.0428134761751;
   fMax_1[0][12] = 0.999524593353;
   fMin_1[1][12] = 0.0438870862126;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0.0428134761751;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0.0419070869684;
   fMax_1[0][13] = 0.999528348446;
   fMin_1[1][13] = 0.0378077812493;
   fMax_1[1][13] = 0.999781787395;
   fMin_1[2][13] = 0.0378077812493;
   fMax_1[2][13] = 0.999781787395;
   fMin_1[0][14] = 0.0469597056508;
   fMax_1[0][14] = 0.999630331993;
   fMin_1[1][14] = 0.0489051826298;
   fMax_1[1][14] = 0.999580085278;
   fMin_1[2][14] = 0.0469597056508;
   fMax_1[2][14] = 0.999630331993;
}

//_______________________________________________________________________
inline void ReadDNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadDNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
