// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Tue Jul  4 14:40:07 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/analysis_javier/tmva/v3
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,13]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [3,6]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,10]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.3915143013,3.62139201164]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [18.1019706726,299.993682861]
BJet_Pt                       BJet_Pt                       BJet_Pt                       BJet_Pt                                                         'F'    [30.2222366333,299.903961182]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [30.7679386139,299.903961182]
Jet1_Pt                       Jet1_Pt                       Jet1_Pt                       Jet1_Pt                                                         'F'    [34.9363479614,299.90512085]
Jet2_Pt                       Jet2_Pt                       Jet2_Pt                       Jet2_Pt                                                         'F'    [31.6454200745,295.347045898]
Jet3_Pt                       Jet3_Pt                       Jet3_Pt                       Jet3_Pt                                                         'F'    [30.1570491791,254.746459961]
Jet4_Pt                       Jet4_Pt                       Jet4_Pt                       Jet4_Pt                                                         'F'    [30.0013217926,221.337020874]
Jet1_CSV                      Jet1_CSV                      Jet1_CSV                      Jet1_CSV                                                        'F'    [0.0351784825325,0.999445080757]
Jet2_CSV                      Jet2_CSV                      Jet2_CSV                      Jet2_CSV                                                        'F'    [0.0474148988724,1]
Jet3_CSV                      Jet3_CSV                      Jet3_CSV                      Jet3_CSV                                                        'F'    [0.0426050275564,0.999781787395]
Jet4_CSV                      Jet4_CSV                      Jet4_CSV                      Jet4_CSV                                                        'F'    [0.0420862697065,0.999633193016]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJet_M_delta_R", "H_Mass", "BJet_Pt", "CJet_Pt", "Jet1_Pt", "Jet2_Pt", "Jet3_Pt", "Jet4_Pt", "Jet1_CSV", "Jet2_CSV", "Jet3_CSV", "Jet4_CSV" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][15];
   double fMax_1[3][15];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[21][16];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][21];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 16; fWeights[0] = new double[16]; 
   fLayerSize[1] = 21; fWeights[1] = new double[21]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.04494740906693;
   fWeightMatrix0to1[1][0] = -0.259373621376521;
   fWeightMatrix0to1[2][0] = 0.602564441200346;
   fWeightMatrix0to1[3][0] = 2.04382093394258;
   fWeightMatrix0to1[4][0] = -2.28982855694776;
   fWeightMatrix0to1[5][0] = -7.4550048476882;
   fWeightMatrix0to1[6][0] = -0.864202545161278;
   fWeightMatrix0to1[7][0] = 1.92846119422788;
   fWeightMatrix0to1[8][0] = -1.05136280455363;
   fWeightMatrix0to1[9][0] = -0.460571584396244;
   fWeightMatrix0to1[10][0] = -2.1695501549402;
   fWeightMatrix0to1[11][0] = -0.876195972893971;
   fWeightMatrix0to1[12][0] = 1.00142658609596;
   fWeightMatrix0to1[13][0] = 0.517756702934077;
   fWeightMatrix0to1[14][0] = -0.412459763438612;
   fWeightMatrix0to1[15][0] = 0.0822698652066661;
   fWeightMatrix0to1[16][0] = -1.04051595262113;
   fWeightMatrix0to1[17][0] = -1.93712257161908;
   fWeightMatrix0to1[18][0] = 0.28728746110163;
   fWeightMatrix0to1[19][0] = 1.35043781999211;
   fWeightMatrix0to1[0][1] = -1.23626403576705;
   fWeightMatrix0to1[1][1] = -0.724536124599509;
   fWeightMatrix0to1[2][1] = -1.72686329908683;
   fWeightMatrix0to1[3][1] = 1.85577175507241;
   fWeightMatrix0to1[4][1] = 2.92423769265575;
   fWeightMatrix0to1[5][1] = 0.0334592336300852;
   fWeightMatrix0to1[6][1] = 2.26322090248265;
   fWeightMatrix0to1[7][1] = -2.76513455454032;
   fWeightMatrix0to1[8][1] = 1.89572235658096;
   fWeightMatrix0to1[9][1] = -0.587432745973694;
   fWeightMatrix0to1[10][1] = 0.772599502518656;
   fWeightMatrix0to1[11][1] = -0.616944457321909;
   fWeightMatrix0to1[12][1] = -5.89739906280694;
   fWeightMatrix0to1[13][1] = 0.70413376805068;
   fWeightMatrix0to1[14][1] = 0.322731216845344;
   fWeightMatrix0to1[15][1] = -0.0167474477305771;
   fWeightMatrix0to1[16][1] = -1.17707604422355;
   fWeightMatrix0to1[17][1] = 4.9491754482466;
   fWeightMatrix0to1[18][1] = 1.02833605597032;
   fWeightMatrix0to1[19][1] = 3.44178599503605;
   fWeightMatrix0to1[0][2] = -0.913114188009907;
   fWeightMatrix0to1[1][2] = 0.739131701165818;
   fWeightMatrix0to1[2][2] = 1.22584131396584;
   fWeightMatrix0to1[3][2] = 2.24872474320766;
   fWeightMatrix0to1[4][2] = -1.27668686128814;
   fWeightMatrix0to1[5][2] = -1.74393505095236;
   fWeightMatrix0to1[6][2] = -2.1825436678534;
   fWeightMatrix0to1[7][2] = 0.192432011145844;
   fWeightMatrix0to1[8][2] = 1.91750424827589;
   fWeightMatrix0to1[9][2] = 0.717826053237952;
   fWeightMatrix0to1[10][2] = 2.97761844760836;
   fWeightMatrix0to1[11][2] = 1.46357867072376;
   fWeightMatrix0to1[12][2] = -0.393404631141138;
   fWeightMatrix0to1[13][2] = 0.216051659562188;
   fWeightMatrix0to1[14][2] = -1.45130584100936;
   fWeightMatrix0to1[15][2] = -0.827589381420399;
   fWeightMatrix0to1[16][2] = -0.859561970435674;
   fWeightMatrix0to1[17][2] = 2.27996432631555;
   fWeightMatrix0to1[18][2] = 0.029573800019364;
   fWeightMatrix0to1[19][2] = 2.66469033343594;
   fWeightMatrix0to1[0][3] = -1.44081515985827;
   fWeightMatrix0to1[1][3] = 1.13949844328915;
   fWeightMatrix0to1[2][3] = 0.101643262536349;
   fWeightMatrix0to1[3][3] = -0.156916757220107;
   fWeightMatrix0to1[4][3] = 0.944409168741056;
   fWeightMatrix0to1[5][3] = -1.07781900661177;
   fWeightMatrix0to1[6][3] = 2.00373968718496;
   fWeightMatrix0to1[7][3] = -0.181695726477566;
   fWeightMatrix0to1[8][3] = -1.98722092203849;
   fWeightMatrix0to1[9][3] = 0.0897332905606097;
   fWeightMatrix0to1[10][3] = 0.686308914834313;
   fWeightMatrix0to1[11][3] = -1.00234795317754;
   fWeightMatrix0to1[12][3] = 2.35614755048829;
   fWeightMatrix0to1[13][3] = 0.918000033739217;
   fWeightMatrix0to1[14][3] = -0.214661447664324;
   fWeightMatrix0to1[15][3] = -0.339110978562999;
   fWeightMatrix0to1[16][3] = -1.88710298340968;
   fWeightMatrix0to1[17][3] = -2.43563966616124;
   fWeightMatrix0to1[18][3] = 2.56164664531656;
   fWeightMatrix0to1[19][3] = 1.2828425430002;
   fWeightMatrix0to1[0][4] = 3.58663234623577;
   fWeightMatrix0to1[1][4] = 7.12479217195602;
   fWeightMatrix0to1[2][4] = 1.29519348450014;
   fWeightMatrix0to1[3][4] = -5.6651540776487;
   fWeightMatrix0to1[4][4] = -1.25753882460648;
   fWeightMatrix0to1[5][4] = 0.880332119889314;
   fWeightMatrix0to1[6][4] = 1.97492507208667;
   fWeightMatrix0to1[7][4] = -3.34227826735637;
   fWeightMatrix0to1[8][4] = -2.63155833536283;
   fWeightMatrix0to1[9][4] = -0.423476629795965;
   fWeightMatrix0to1[10][4] = -0.79725268872427;
   fWeightMatrix0to1[11][4] = -0.0347897554942641;
   fWeightMatrix0to1[12][4] = 7.11199782729273;
   fWeightMatrix0to1[13][4] = -2.24320516918379;
   fWeightMatrix0to1[14][4] = -1.08154377964465;
   fWeightMatrix0to1[15][4] = 0.2385256191717;
   fWeightMatrix0to1[16][4] = 0.276313342833826;
   fWeightMatrix0to1[17][4] = -6.2878361285255;
   fWeightMatrix0to1[18][4] = -4.26135658981379;
   fWeightMatrix0to1[19][4] = 1.46780155044369;
   fWeightMatrix0to1[0][5] = -2.2859852581257;
   fWeightMatrix0to1[1][5] = -0.388491330954585;
   fWeightMatrix0to1[2][5] = 2.96509007340978;
   fWeightMatrix0to1[3][5] = 1.62725219204679;
   fWeightMatrix0to1[4][5] = -0.35365597357978;
   fWeightMatrix0to1[5][5] = 0.0449527361356882;
   fWeightMatrix0to1[6][5] = -0.979657216911605;
   fWeightMatrix0to1[7][5] = 0.47181444827896;
   fWeightMatrix0to1[8][5] = -0.552589595271919;
   fWeightMatrix0to1[9][5] = 0.0968965507277104;
   fWeightMatrix0to1[10][5] = -0.627629489515768;
   fWeightMatrix0to1[11][5] = -0.476458370962371;
   fWeightMatrix0to1[12][5] = 0.41587661364824;
   fWeightMatrix0to1[13][5] = 0.737769666684874;
   fWeightMatrix0to1[14][5] = -1.19196619486967;
   fWeightMatrix0to1[15][5] = 0.283973714254181;
   fWeightMatrix0to1[16][5] = -0.135792646522508;
   fWeightMatrix0to1[17][5] = 2.56008556753353;
   fWeightMatrix0to1[18][5] = 0.412360103548664;
   fWeightMatrix0to1[19][5] = -1.77730125849258;
   fWeightMatrix0to1[0][6] = -1.27889239406073;
   fWeightMatrix0to1[1][6] = -0.240923163096693;
   fWeightMatrix0to1[2][6] = -2.40061149952754;
   fWeightMatrix0to1[3][6] = 1.18212644104822;
   fWeightMatrix0to1[4][6] = 2.69921690274114;
   fWeightMatrix0to1[5][6] = 0.402275649971254;
   fWeightMatrix0to1[6][6] = 0.439636090193258;
   fWeightMatrix0to1[7][6] = -0.681425994292839;
   fWeightMatrix0to1[8][6] = -2.97071732167923;
   fWeightMatrix0to1[9][6] = 0.306324846760132;
   fWeightMatrix0to1[10][6] = 1.54603603189686;
   fWeightMatrix0to1[11][6] = -0.841760562872528;
   fWeightMatrix0to1[12][6] = -0.00888278447149029;
   fWeightMatrix0to1[13][6] = -1.41564111490824;
   fWeightMatrix0to1[14][6] = -0.314162084388147;
   fWeightMatrix0to1[15][6] = 0.589383618402286;
   fWeightMatrix0to1[16][6] = 3.9321443720544;
   fWeightMatrix0to1[17][6] = -1.45521705365296;
   fWeightMatrix0to1[18][6] = -1.23921072542978;
   fWeightMatrix0to1[19][6] = 0.973800207030486;
   fWeightMatrix0to1[0][7] = 1.28442645922027;
   fWeightMatrix0to1[1][7] = 0.386089691643181;
   fWeightMatrix0to1[2][7] = -2.68270673898286;
   fWeightMatrix0to1[3][7] = 0.669977031033871;
   fWeightMatrix0to1[4][7] = -4.38783964672921;
   fWeightMatrix0to1[5][7] = -1.04273130034777;
   fWeightMatrix0to1[6][7] = 1.24684751085154;
   fWeightMatrix0to1[7][7] = -0.0549299590534113;
   fWeightMatrix0to1[8][7] = 0.711497112154123;
   fWeightMatrix0to1[9][7] = -0.109304487467905;
   fWeightMatrix0to1[10][7] = -3.25571824050146;
   fWeightMatrix0to1[11][7] = 1.11325688414719;
   fWeightMatrix0to1[12][7] = 0.303144044640229;
   fWeightMatrix0to1[13][7] = 3.90764762869616;
   fWeightMatrix0to1[14][7] = 1.29044111495668;
   fWeightMatrix0to1[15][7] = -0.100311446295642;
   fWeightMatrix0to1[16][7] = 2.58216695332825;
   fWeightMatrix0to1[17][7] = -0.175808100875505;
   fWeightMatrix0to1[18][7] = -0.106848521380724;
   fWeightMatrix0to1[19][7] = 0.845831173466726;
   fWeightMatrix0to1[0][8] = 2.67702419077581;
   fWeightMatrix0to1[1][8] = 0.0108794740333708;
   fWeightMatrix0to1[2][8] = 1.6602346572362;
   fWeightMatrix0to1[3][8] = -1.81350273749448;
   fWeightMatrix0to1[4][8] = 3.45140030486064;
   fWeightMatrix0to1[5][8] = 0.676087428619801;
   fWeightMatrix0to1[6][8] = -0.419940663174715;
   fWeightMatrix0to1[7][8] = 0.8622454066873;
   fWeightMatrix0to1[8][8] = -0.417869818183807;
   fWeightMatrix0to1[9][8] = -0.290306741776456;
   fWeightMatrix0to1[10][8] = 0.83714137339328;
   fWeightMatrix0to1[11][8] = 1.67102129873678;
   fWeightMatrix0to1[12][8] = 1.3686596058087;
   fWeightMatrix0to1[13][8] = 4.46220356647821;
   fWeightMatrix0to1[14][8] = 2.61638159716591;
   fWeightMatrix0to1[15][8] = -1.40147025897537;
   fWeightMatrix0to1[16][8] = -0.186211721847677;
   fWeightMatrix0to1[17][8] = 1.34893586103346;
   fWeightMatrix0to1[18][8] = 1.86899661415054;
   fWeightMatrix0to1[19][8] = 0.0875427435878418;
   fWeightMatrix0to1[0][9] = -2.44963148377044;
   fWeightMatrix0to1[1][9] = -0.513971579313189;
   fWeightMatrix0to1[2][9] = 0.606669575834244;
   fWeightMatrix0to1[3][9] = 1.42001581579609;
   fWeightMatrix0to1[4][9] = -1.43506477923452;
   fWeightMatrix0to1[5][9] = -0.264279985209217;
   fWeightMatrix0to1[6][9] = 0.820549650845268;
   fWeightMatrix0to1[7][9] = 0.108167507385514;
   fWeightMatrix0to1[8][9] = -1.17713365537073;
   fWeightMatrix0to1[9][9] = -0.418496440117717;
   fWeightMatrix0to1[10][9] = -2.6498573056375;
   fWeightMatrix0to1[11][9] = 0.387474775922839;
   fWeightMatrix0to1[12][9] = -0.108512099461857;
   fWeightMatrix0to1[13][9] = -0.818234826568194;
   fWeightMatrix0to1[14][9] = 0.700864485470155;
   fWeightMatrix0to1[15][9] = -0.635732705228104;
   fWeightMatrix0to1[16][9] = -1.21826663103044;
   fWeightMatrix0to1[17][9] = -0.105250644920244;
   fWeightMatrix0to1[18][9] = 0.938868856005304;
   fWeightMatrix0to1[19][9] = 0.495259755350894;
   fWeightMatrix0to1[0][10] = 0.160990211282376;
   fWeightMatrix0to1[1][10] = -0.216060424098085;
   fWeightMatrix0to1[2][10] = 3.50065267351237;
   fWeightMatrix0to1[3][10] = -0.590939867785564;
   fWeightMatrix0to1[4][10] = -2.2356949770538;
   fWeightMatrix0to1[5][10] = -0.00748468551805421;
   fWeightMatrix0to1[6][10] = 0.0628698677272196;
   fWeightMatrix0to1[7][10] = -0.676045820536747;
   fWeightMatrix0to1[8][10] = 1.67983125877291;
   fWeightMatrix0to1[9][10] = 0.529441844333508;
   fWeightMatrix0to1[10][10] = -0.747489167051653;
   fWeightMatrix0to1[11][10] = -0.450952580437764;
   fWeightMatrix0to1[12][10] = 0.508048663637089;
   fWeightMatrix0to1[13][10] = 0.646390331645088;
   fWeightMatrix0to1[14][10] = 2.69431160726051;
   fWeightMatrix0to1[15][10] = 0.821994672620958;
   fWeightMatrix0to1[16][10] = 0.318683187084954;
   fWeightMatrix0to1[17][10] = 0.289522526403508;
   fWeightMatrix0to1[18][10] = 0.784285294610931;
   fWeightMatrix0to1[19][10] = -0.386144314356237;
   fWeightMatrix0to1[0][11] = -1.05188781800376;
   fWeightMatrix0to1[1][11] = -0.201001329740484;
   fWeightMatrix0to1[2][11] = 0.154548738381025;
   fWeightMatrix0to1[3][11] = -0.135804576231515;
   fWeightMatrix0to1[4][11] = 2.02369159412094;
   fWeightMatrix0to1[5][11] = 0.217519825520505;
   fWeightMatrix0to1[6][11] = 2.23435154059474;
   fWeightMatrix0to1[7][11] = 0.784191335965072;
   fWeightMatrix0to1[8][11] = -3.60048949710031;
   fWeightMatrix0to1[9][11] = -0.170391710316109;
   fWeightMatrix0to1[10][11] = 1.30355890186991;
   fWeightMatrix0to1[11][11] = 0.829971390501794;
   fWeightMatrix0to1[12][11] = 0.266191021533;
   fWeightMatrix0to1[13][11] = -0.0569141913517157;
   fWeightMatrix0to1[14][11] = 1.06344185647241;
   fWeightMatrix0to1[15][11] = -0.134597361768252;
   fWeightMatrix0to1[16][11] = 1.84414777989706;
   fWeightMatrix0to1[17][11] = -0.227622196765818;
   fWeightMatrix0to1[18][11] = -1.0674940357195;
   fWeightMatrix0to1[19][11] = -0.019219999281561;
   fWeightMatrix0to1[0][12] = -1.40541886695644;
   fWeightMatrix0to1[1][12] = -0.137517379146623;
   fWeightMatrix0to1[2][12] = -1.75272373758485;
   fWeightMatrix0to1[3][12] = 0.0327040833317574;
   fWeightMatrix0to1[4][12] = -0.649349068308949;
   fWeightMatrix0to1[5][12] = 0.0157735717548493;
   fWeightMatrix0to1[6][12] = 0.1418911377715;
   fWeightMatrix0to1[7][12] = 0.378686104688995;
   fWeightMatrix0to1[8][12] = 0.113287591585748;
   fWeightMatrix0to1[9][12] = -0.0807280817718091;
   fWeightMatrix0to1[10][12] = 0.791465838028621;
   fWeightMatrix0to1[11][12] = 0.470755054459103;
   fWeightMatrix0to1[12][12] = 0.0994987854892262;
   fWeightMatrix0to1[13][12] = 0.151906612529879;
   fWeightMatrix0to1[14][12] = 1.19069473032808;
   fWeightMatrix0to1[15][12] = 0.188747538956105;
   fWeightMatrix0to1[16][12] = -0.311010400067535;
   fWeightMatrix0to1[17][12] = 0.254580156397049;
   fWeightMatrix0to1[18][12] = -0.361949899883717;
   fWeightMatrix0to1[19][12] = 0.0301668393575189;
   fWeightMatrix0to1[0][13] = -0.782297228010337;
   fWeightMatrix0to1[1][13] = -0.123597563906864;
   fWeightMatrix0to1[2][13] = 0.806140223806236;
   fWeightMatrix0to1[3][13] = -0.78055783191201;
   fWeightMatrix0to1[4][13] = 0.491812029391254;
   fWeightMatrix0to1[5][13] = -0.191853303175527;
   fWeightMatrix0to1[6][13] = -0.217788991077926;
   fWeightMatrix0to1[7][13] = -0.0156089647914272;
   fWeightMatrix0to1[8][13] = 1.21759081778925;
   fWeightMatrix0to1[9][13] = -0.0823850039996445;
   fWeightMatrix0to1[10][13] = -0.160374059659413;
   fWeightMatrix0to1[11][13] = -1.89222307331832;
   fWeightMatrix0to1[12][13] = 0.151767711692939;
   fWeightMatrix0to1[13][13] = -0.100199253425987;
   fWeightMatrix0to1[14][13] = 0.162711978468782;
   fWeightMatrix0to1[15][13] = -0.207245832701954;
   fWeightMatrix0to1[16][13] = 2.38722146173109;
   fWeightMatrix0to1[17][13] = -0.0396302757873959;
   fWeightMatrix0to1[18][13] = 0.348270707678601;
   fWeightMatrix0to1[19][13] = -0.0415183194752576;
   fWeightMatrix0to1[0][14] = -0.166685090713919;
   fWeightMatrix0to1[1][14] = -0.240271891015001;
   fWeightMatrix0to1[2][14] = -0.295716606459156;
   fWeightMatrix0to1[3][14] = -0.159755791442987;
   fWeightMatrix0to1[4][14] = 0.31230543248284;
   fWeightMatrix0to1[5][14] = 0.0185080451101819;
   fWeightMatrix0to1[6][14] = -0.151156011736741;
   fWeightMatrix0to1[7][14] = 0.360064442004941;
   fWeightMatrix0to1[8][14] = -0.321965479839588;
   fWeightMatrix0to1[9][14] = -0.0173801621077333;
   fWeightMatrix0to1[10][14] = 0.774013981541246;
   fWeightMatrix0to1[11][14] = -0.142866195691064;
   fWeightMatrix0to1[12][14] = -0.0761493641670935;
   fWeightMatrix0to1[13][14] = 0.306331467415664;
   fWeightMatrix0to1[14][14] = 1.01203107519316;
   fWeightMatrix0to1[15][14] = 0.168543851640887;
   fWeightMatrix0to1[16][14] = 0.0193842628041433;
   fWeightMatrix0to1[17][14] = -0.399085956832365;
   fWeightMatrix0to1[18][14] = -1.40156153137342;
   fWeightMatrix0to1[19][14] = -0.136585484744088;
   fWeightMatrix0to1[0][15] = -1.68485751408661;
   fWeightMatrix0to1[1][15] = 0.916638369612444;
   fWeightMatrix0to1[2][15] = 4.34041522920595;
   fWeightMatrix0to1[3][15] = 0.931252512078057;
   fWeightMatrix0to1[4][15] = -3.13097027853856;
   fWeightMatrix0to1[5][15] = -7.38981551154167;
   fWeightMatrix0to1[6][15] = -2.08700071736627;
   fWeightMatrix0to1[7][15] = -3.19201933430975;
   fWeightMatrix0to1[8][15] = -1.51787648353183;
   fWeightMatrix0to1[9][15] = -0.474756839081447;
   fWeightMatrix0to1[10][15] = -2.10879239914791;
   fWeightMatrix0to1[11][15] = 0.114460749878038;
   fWeightMatrix0to1[12][15] = -0.873621517985627;
   fWeightMatrix0to1[13][15] = 6.28961176655954;
   fWeightMatrix0to1[14][15] = 0.813615700542289;
   fWeightMatrix0to1[15][15] = -0.0862457561713342;
   fWeightMatrix0to1[16][15] = 1.41219446173352;
   fWeightMatrix0to1[17][15] = 0.475015322325502;
   fWeightMatrix0to1[18][15] = 1.90048550600297;
   fWeightMatrix0to1[19][15] = 5.57517810207371;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.336164069328524;
   fWeightMatrix1to2[0][1] = -1.07941475329562;
   fWeightMatrix1to2[0][2] = -0.290231209382764;
   fWeightMatrix1to2[0][3] = -0.379360471524612;
   fWeightMatrix1to2[0][4] = 0.390689060286764;
   fWeightMatrix1to2[0][5] = 0.574420096262262;
   fWeightMatrix1to2[0][6] = -0.722358569575478;
   fWeightMatrix1to2[0][7] = -0.524893168435173;
   fWeightMatrix1to2[0][8] = 0.350212158391174;
   fWeightMatrix1to2[0][9] = -0.0302720113239511;
   fWeightMatrix1to2[0][10] = -0.31737752217144;
   fWeightMatrix1to2[0][11] = 0.377990689317069;
   fWeightMatrix1to2[0][12] = 0.732383984663823;
   fWeightMatrix1to2[0][13] = -0.769472510074239;
   fWeightMatrix1to2[0][14] = -0.318497052335064;
   fWeightMatrix1to2[0][15] = -0.151459311999138;
   fWeightMatrix1to2[0][16] = 0.323502377602349;
   fWeightMatrix1to2[0][17] = -0.333638545014481;
   fWeightMatrix1to2[0][18] = -0.347891483516418;
   fWeightMatrix1to2[0][19] = -0.545841751261826;
   fWeightMatrix1to2[0][20] = -0.858568465175807;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 13;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 13;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 13;
   fMin_1[0][1] = 3;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 3;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 3;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 7;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 10;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 10;
   fMin_1[0][3] = 0.40086761117;
   fMax_1[0][3] = 3.48090934753;
   fMin_1[1][3] = 0.3915143013;
   fMax_1[1][3] = 3.62139201164;
   fMin_1[2][3] = 0.3915143013;
   fMax_1[2][3] = 3.62139201164;
   fMin_1[0][4] = 18.1019706726;
   fMax_1[0][4] = 298.377258301;
   fMin_1[1][4] = 18.2769832611;
   fMax_1[1][4] = 299.993682861;
   fMin_1[2][4] = 18.1019706726;
   fMax_1[2][4] = 299.993682861;
   fMin_1[0][5] = 30.2222366333;
   fMax_1[0][5] = 299.548950195;
   fMin_1[1][5] = 30.868970871;
   fMax_1[1][5] = 299.903961182;
   fMin_1[2][5] = 30.2222366333;
   fMax_1[2][5] = 299.903961182;
   fMin_1[0][6] = 30.7679386139;
   fMax_1[0][6] = 299.820800781;
   fMin_1[1][6] = 31.9563426971;
   fMax_1[1][6] = 299.903961182;
   fMin_1[2][6] = 30.7679386139;
   fMax_1[2][6] = 299.903961182;
   fMin_1[0][7] = 34.9363479614;
   fMax_1[0][7] = 299.820800781;
   fMin_1[1][7] = 37.5980606079;
   fMax_1[1][7] = 299.90512085;
   fMin_1[2][7] = 34.9363479614;
   fMax_1[2][7] = 299.90512085;
   fMin_1[0][8] = 31.6454200745;
   fMax_1[0][8] = 294.691680908;
   fMin_1[1][8] = 31.9563426971;
   fMax_1[1][8] = 295.347045898;
   fMin_1[2][8] = 31.6454200745;
   fMax_1[2][8] = 295.347045898;
   fMin_1[0][9] = 30.1570491791;
   fMax_1[0][9] = 254.746459961;
   fMin_1[1][9] = 30.3130378723;
   fMax_1[1][9] = 254.595474243;
   fMin_1[2][9] = 30.1570491791;
   fMax_1[2][9] = 254.746459961;
   fMin_1[0][10] = 30.0013217926;
   fMax_1[0][10] = 208.918029785;
   fMin_1[1][10] = 30.0026817322;
   fMax_1[1][10] = 221.337020874;
   fMin_1[2][10] = 30.0013217926;
   fMax_1[2][10] = 221.337020874;
   fMin_1[0][11] = 0.0351784825325;
   fMax_1[0][11] = 0.999438822269;
   fMin_1[1][11] = 0.0449013523757;
   fMax_1[1][11] = 0.999445080757;
   fMin_1[2][11] = 0.0351784825325;
   fMax_1[2][11] = 0.999445080757;
   fMin_1[0][12] = 0.0474148988724;
   fMax_1[0][12] = 0.999635875225;
   fMin_1[1][12] = 0.047779712826;
   fMax_1[1][12] = 1;
   fMin_1[2][12] = 0.0474148988724;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0.0426050275564;
   fMax_1[0][13] = 0.9995855093;
   fMin_1[1][13] = 0.049080748111;
   fMax_1[1][13] = 0.999781787395;
   fMin_1[2][13] = 0.0426050275564;
   fMax_1[2][13] = 0.999781787395;
   fMin_1[0][14] = 0.0420862697065;
   fMax_1[0][14] = 0.999633193016;
   fMin_1[1][14] = 0.0434354804456;
   fMax_1[1][14] = 0.999622881413;
   fMin_1[2][14] = 0.0420862697065;
   fMax_1[2][14] = 0.999633193016;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 15;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
      indicesGet.push_back( 11);
      indicesGet.push_back( 12);
      indicesGet.push_back( 13);
      indicesGet.push_back( 14);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
      indicesPut.push_back( 11);
      indicesPut.push_back( 12);
      indicesPut.push_back( 13);
      indicesPut.push_back( 14);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<15;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
