// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : minerva1993
Date           : Wed May 17 21:11:08 2017
Host           : Linux vocms0301.cern.ch 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Nov 16 09:40:09 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /cms/home/minerva1993/fcnc/fcnc/tmva/basic_example
Training events: 6000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "2" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 3
var1                          var1                          var1                          var1                                                            'F'    [-4.95827770233,4.76391029358]
var2                          var2                          var2                          var2                                                            'F'    [-5.24535989761,4.82998085022]
var3                          var3                          var3                          var3                                                            'F'    [-5.05078554153,4.35967063904]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 3 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1", "var2", "var3" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[3];
   double fVmax[3];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[3];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.536417429242585);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442857,-99) , 
0, 1.5581, 1, 0, 0.667831,-99) , 
NN(
0, 
0, 
-1, 2.55394, 1, -1, 0.104,-99) , 
0, 2.1752, 1, 0, 0.596206,-99) , 
NN(
0, 
0, 
-1, -2.21081, 0, -1, 0.0961263,-99) , 
2, -1.5451, 0, 0, 0.500685,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.368189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456123,-99) , 
2, -0.500114, 0, 0, 0.588446,-99) , 
NN(
0, 
0, 
-1, 2.3633, 1, -1, 0.0818685,-99) , 
0, 2.40725, 1, 0, 0.546831,-99) , 
NN(
0, 
0, 
-1, -2.14981, 0, -1, 0.0680625,-99) , 
2, -1.94727, 0, 0, 0.482997,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.302112);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4778,-99) , 
0, 0.639881, 1, 0, 0.562753,-99) , 
NN(
0, 
0, 
-1, 2.00029, 1, -1, 0.171326,-99) , 
0, 2.11657, 1, 0, 0.521426,-99) , 
NN(
0, 
0, 
-1, -2.22383, 0, -1, 0.0543996,-99) , 
2, -1.89272, 0, 0, 0.464632,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.327377);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4124,-99) , 
0, -0.877153, 0, 0, 0.570014,-99) , 
NN(
0, 
0, 
-1, 1.36527, 1, -1, 0.214805,-99) , 
0, 2.00943, 1, 0, 0.52945,-99) , 
NN(
0, 
0, 
-1, -2.38898, 0, -1, 0.0710344,-99) , 
2, -1.93828, 0, 0, 0.47524,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.232438);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333675,-99) , 
1, -1.08197, 0, 0, 0.502456,-99) , 
NN(
0, 
0, 
-1, 2.34063, 1, -1, 0.216079,-99) , 
2, 1.94852, 1, 0, 0.467546,-99) , 
NN(
0, 
0, 
-1, -2.51841, 0, -1, 0.018279,-99) , 
2, -2.41815, 0, 0, 0.43109,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.197748);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400413,-99) , 
2, -0.861434, 0, 0, 0.503489,-99) , 
NN(
0, 
0, 
-1, 2.01622, 1, -1, 0.222454,-99) , 
1, 1.8913, 1, 0, 0.473471,-99) , 
NN(
0, 
0, 
-1, -2.19118, 0, -1, 0.0475375,-99) , 
2, -2.36208, 0, 0, 0.44061,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.174055);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334298,-99) , 
0, -1.48498, 0, 0, 0.504042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.117232,-99) , 
0, 2.55486, 1, 0, 0.482947,-99) , 
NN(
0, 
0, 
-1, -1.98681, 0, -1, 0.0656244,-99) , 
1, -1.98012, 0, 0, 0.448583,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.181929);
  fForest.push_back( 
NN(
0, 
0, 
-1, -1.87659, 0, -1, 0.410026,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.180858);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520914,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414036,-99) , 
0, 1.26309, 1, 0, 0.498835,-99) , 
NN(
0, 
0, 
-1, 1.91498, 1, -1, 0.158248,-99) , 
0, 2.39356, 1, 0, 0.474606,-99) , 
NN(
0, 
0, 
-1, -2.24751, 0, -1, 0.101639,-99) , 
2, -1.91397, 0, 0, 0.438376,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.145302);
  fForest.push_back( 
NN(
0, 
0, 
-1, -1.99993, 0, -1, 0.427856,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.15058);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352544,-99) , 
2, -0.799196, 0, 0, 0.47365,-99) , 
NN(
0, 
0, 
-1, 2.10809, 1, -1, 0.236062,-99) , 
1, 2.00938, 1, 0, 0.453765,-99) , 
NN(
0, 
0, 
-1, -2.36224, 0, -1, 0.0570488,-99) , 
2, -2.2814, 0, 0, 0.429569,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.137571);
  fForest.push_back( 
NN(
0, 
0, 
-1, -2.74792, 0, -1, 0.431645,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.149761);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468843,-99) , 
2, 0.336381, 0, 0, 0.506674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197014,-99) , 
0, 2.63859, 1, 0, 0.493449,-99) , 
NN(
0, 
0, 
-1, -2.72357, 0, -1, 0.0894724,-99) , 
1, -2.06307, 0, 0, 0.467313,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.121034);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289246,-99) , 
1, 2.1499, 1, 0, 0.496528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0869667,-99) , 
0, 2.60665, 1, 0, 0.479785,-99) , 
NN(
0, 
0, 
-1, -2.42956, 0, -1, 0.0490263,-99) , 
2, -2.27151, 0, 0, 0.454673,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.125461);
  fForest.push_back( 
NN(
0, 
0, 
-1, -2.04461, 0, -1, 0.437597,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.132564);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413993,-99) , 
1, 1.18336, 1, 0, 0.494341,-99) , 
NN(
0, 
0, 
-1, 1.50706, 1, -1, 0.203824,-99) , 
0, 2.15917, 1, 0, 0.471811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, -2.82629, 0, 0, 0.455302,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.115308);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410986,-99) , 
0, 1.15028, 1, 0, 0.481878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151833,-99) , 
2, 2.78149, 1, 0, 0.471389,-99) , 
NN(
0, 
0, 
-1, -2.65812, 0, -1, 0.091892,-99) , 
2, -2.2814, 0, 0, 0.451081,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.160085);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443499,-99) , 
2, 0.819984, 0, 0, 0.474891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.126668,-99) , 
0, 2.5933, 1, 0, 0.461406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0210842,-99) , 
2, -2.82954, 0, 0, 0.446008,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.100331);
  fForest.push_back( 
NN(
0, 
0, 
-1, -2.86495, 0, -1, 0.450002,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.116697);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287366,-99) , 
1, -1.87659, 0, 0, 0.51324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210376,-99) , 
0, 2.63035, 1, 0, 0.503452,-99) , 
NN(
0, 
0, 
-1, -2.27154, 0, -1, 0.0768427,-99) , 
0, -2.23426, 0, 0, 0.481267,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0784746);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280768,-99) , 
1, -1.88766, 0, 0, 0.497205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271188,-99) , 
1, 2.31111, 1, 0, 0.485891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0275059,-99) , 
2, -2.72414, 0, 0, 0.470668,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.152908);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264864,-99) , 
1, -1.94374, 0, 0, 0.517545,-99) , 
NN(
0, 
0, 
-1, 1.90707, 1, -1, 0.398992,-99) , 
1, 0.800554, 1, 0, 0.477479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0279279,-99) , 
2, -2.8102, 0, 0, 0.462568,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.117872);
  fForest.push_back( 
NN(
0, 
0, 
-1, -2.8403, 0, -1, 0.441336,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0770303);
  fForest.push_back( 
NN(
0, 
0, 
-1, -2.8102, 0, -1, 0.461561,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0926844);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391414,-99) , 
0, 1.9173, 1, 0, 0.502456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197635,-99) , 
2, 2.56275, 1, 0, 0.490743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.142358,-99) , 
0, -2.14621, 0, 0, 0.473447,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0933019);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469973,-99) , 
0, 0.431752, 1, 0, 0.498196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327597,-99) , 
0, 2.4114, 1, 0, 0.489266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.130296,-99) , 
1, -2.17981, 0, 0, 0.474424,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.112848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462487,-99) , 
1, 0.699284, 0, 0, 0.482706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.212803,-99) , 
2, 2.69864, 1, 0, 0.475011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0612634,-99) , 
2, -2.36252, 0, 0, 0.459133,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.119431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476398,-99) , 
2, -0.367285, 0, 0, 0.521907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303339,-99) , 
1, 2.23034, 1, 0, 0.510569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191214,-99) , 
1, -2.04206, 0, 0, 0.493921,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0796235);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366742,-99) , 
2, -1.74773, 0, 0, 0.495177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.243805,-99) , 
0, 2.44934, 1, 0, 0.483334,-99) , 
NN(
0, 
0, 
-1, -1.73726, 0, -1, 0.166011,-99) , 
0, -2.18051, 0, 0, 0.465503,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0515648);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.44221, 1, 1, 0.507221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292557,-99) , 
0, 2.46332, 1, 0, 0.498922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0545758,-99) , 
2, -2.8102, 0, 0, 0.487776,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.126128);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436677,-99) , 
0, 0.323219, 1, 0, 0.473253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197711,-99) , 
0, 2.49075, 1, 0, 0.465121,-99) , 
NN(
0, 
0, 
-1, -1.85326, 0, -1, 0.110629,-99) , 
0, -2.07143, 0, 0, 0.447186,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.114116);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479835,-99) , 
2, 1.71202, 0, 0, 0.486048,-99) , 
NN(
0, 
0, 
-1, 2.38112, 1, -1, 0.395783,-99) , 
1, 1.2035, 1, 0, 0.465617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0678443,-99) , 
2, -2.35245, 0, 0, 0.450944,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.106439);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457083,-99) , 
0, 0.696372, 0, 0, 0.477834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322915,-99) , 
0, 2.55258, 1, 0, 0.471653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0379824,-99) , 
2, -2.41053, 0, 0, 0.458092,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0814993);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.80799, 1, 1, 0.508171,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385934,-99) , 
1, 0.656951, 1, 0, 0.429303,-99) , 
0, 1.03252, 1, 0, 0.485702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.167653,-99) , 
2, -2.3471, 0, 0, 0.473145,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0910272);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471554,-99) , 
0, 0.93402, 0, 0, 0.487297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370111,-99) , 
2, 2.52719, 1, 0, 0.48156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0704894,-99) , 
2, -2.44248, 0, 0, 0.46892,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.136784);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475189,-99) , 
1, -0.689184, 0, 0, 0.528817,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441246,-99) , 
1, -0.876664, 1, 0, 0.453818,-99) , 
0, 0.0179435, 1, 0, 0.483428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.168325,-99) , 
2, -2.35245, 0, 0, 0.472262,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0911567);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.117688, 0, 1, 0.537345,-99) , 
NN(
0, 
0, 
-1, 2.18459, 1, -1, 0.467555,-99) , 
1, 0.318453, 1, 0, 0.502878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246846,-99) , 
1, -1.94874, 0, 0, 0.490527,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0958765);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355952,-99) , 
2, 2.17805, 1, 0, 0.514876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.24108,-99) , 
0, 2.60306, 1, 0, 0.506776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190782,-99) , 
0, -2.14621, 0, 0, 0.492612,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0841718);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499783,-99) , 
2, 0.668965, 0, 0, 0.514608,-99) , 
NN(
0, 
0, 
-1, 2.22222, 1, -1, 0.431381,-99) , 
2, 1.17059, 1, 0, 0.491248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.107774,-99) , 
2, -2.33932, 0, 0, 0.478581,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0757633);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.66305, 0, 1, 0.522304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366342,-99) , 
1, 2.45465, 1, 0, 0.516967,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224753,-99) , 
1, -1.94663, 0, 0, 0.50325,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0820758);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499258,-99) , 
0, 1.77099, 0, 0, 0.508622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403878,-99) , 
0, 0.609416, 1, 0, 0.453465,-99) , 
1, 1.22345, 1, 0, 0.496497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181447,-99) , 
2, -2.39063, 0, 0, 0.485057,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0556203);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.47625, 1, 1, 0.509071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27139,-99) , 
0, 2.49651, 1, 0, 0.50124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.131522,-99) , 
2, -2.39063, 0, 0, 0.489191,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0834771);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.62044, 1, 1, 0.596146,-99) , 
NN(
0, 
0, 
-1, 2.62601, 1, -1, 0.482468,-99) , 
0, -0.956224, 1, 0, 0.501591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.1837,-99) , 
0, -2.22902, 0, 0, 0.489472,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.129552);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464523,-99) , 
2, -0.00550376, 0, 0, 0.511954,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195155,-99) , 
1, 1.44431, 1, 0, 0.361692,-99) , 
0, 1.98826, 1, 0, 0.500064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0799985,-99) , 
2, -2.37566, 0, 0, 0.485969,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0548893);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497073,-99) , 
1, -1.13635, 1, 0, 0.505029,-99) , 
NN(
0, 
0, 
-1, 1.53287, 1, -1, 0.408561,-99) , 
1, 1.95131, 1, 0, 0.496959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.197971,-99) , 
0, -2.12992, 0, 0, 0.485887,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0946718);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445676,-99) , 
0, -1.42561, 0, 0, 0.522474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400672,-99) , 
0, 2.40282, 1, 0, 0.516775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0960483,-99) , 
2, -2.35245, 0, 0, 0.504479,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0874751);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.108913, 0, 1, 0.537248,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46872,-99) , 
2, -0.406714, 1, 0, 0.481008,-99) , 
1, -0.0616485, 1, 0, 0.501989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324091,-99) , 
0, -2.12992, 0, 0, 0.494075,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0559441);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -0.856718, 1, 1, 0.513694,-99) , 
NN(
0, 
0, 
-1, 2.71844, 0, -1, 0.376478,-99) , 
2, 2.26012, 1, 0, 0.505348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268779,-99) , 
2, -2.41815, 0, 0, 0.496856,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0846192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482535,-99) , 
1, -0.223675, 1, 0, 0.501068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386899,-99) , 
2, -0.554384, 1, 0, 0.461533,-99) , 
0, -0.752343, 0, 0, 0.492801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203168,-99) , 
0, -1.98814, 0, 0, 0.480433,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0839844);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402161,-99) , 
0, 2.18649, 1, 0, 0.523962,-99) , 
NN(
0, 
0, 
-1, 0.499712, 1, -1, 0.481054,-99) , 
1, 0.706706, 0, 0, 0.496036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.108087,-99) , 
2, -2.31996, 0, 0, 0.48413,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
