// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Mon May 22 01:44:36 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva
Training events: 200000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 5
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,17]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,7]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,10]
BJMDPhi                       BJMDPhi                       BJMDPhi                       BJMDPhi                                                         'F'    [-3.14159011841,3.14156198502]
BJMDEta                       BJMDEta                       BJMDEta                       BJMDEta                                                         'F'    [-4.75499534607,4.76451778412]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 5 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJMDPhi", "BJMDEta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][5];
   double fMax_1[3][5];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[5];
   double fVmax[5];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[5];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[11][6];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][11];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 6; fWeights[0] = new double[6]; 
   fLayerSize[1] = 11; fWeights[1] = new double[11]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 1.01177633303599;
   fWeightMatrix0to1[1][0] = 0.0483191731035;
   fWeightMatrix0to1[2][0] = 0.489556021241881;
   fWeightMatrix0to1[3][0] = 5.13634203711641;
   fWeightMatrix0to1[4][0] = -10.5873032154685;
   fWeightMatrix0to1[5][0] = 0.388243113339402;
   fWeightMatrix0to1[6][0] = -0.108825082312435;
   fWeightMatrix0to1[7][0] = -0.827535963203514;
   fWeightMatrix0to1[8][0] = -1.25981555207369;
   fWeightMatrix0to1[9][0] = -0.678101201296263;
   fWeightMatrix0to1[0][1] = -1.91018605129751;
   fWeightMatrix0to1[1][1] = -0.105506370168225;
   fWeightMatrix0to1[2][1] = 3.77052129150343;
   fWeightMatrix0to1[3][1] = 0.185928544000534;
   fWeightMatrix0to1[4][1] = 0.677592410170738;
   fWeightMatrix0to1[5][1] = 0.213292680301649;
   fWeightMatrix0to1[6][1] = 0.145604926937995;
   fWeightMatrix0to1[7][1] = 0.697318198348202;
   fWeightMatrix0to1[8][1] = 2.38319157381675;
   fWeightMatrix0to1[9][1] = 11.9179326623632;
   fWeightMatrix0to1[0][2] = -3.48684570360663;
   fWeightMatrix0to1[1][2] = 0.285639182028581;
   fWeightMatrix0to1[2][2] = 0.867016880226104;
   fWeightMatrix0to1[3][2] = 1.12504987035131;
   fWeightMatrix0to1[4][2] = 1.14590878972928;
   fWeightMatrix0to1[5][2] = 1.14278105285155;
   fWeightMatrix0to1[6][2] = -0.374203066610013;
   fWeightMatrix0to1[7][2] = 1.66462008677131;
   fWeightMatrix0to1[8][2] = 0.826654607338374;
   fWeightMatrix0to1[9][2] = 0.0682343825940679;
   fWeightMatrix0to1[0][3] = 0.211216963482015;
   fWeightMatrix0to1[1][3] = -0.0132527850251722;
   fWeightMatrix0to1[2][3] = 0.00412010605081868;
   fWeightMatrix0to1[3][3] = 0.0629890053032747;
   fWeightMatrix0to1[4][3] = 0.0367602246263682;
   fWeightMatrix0to1[5][3] = -0.0307229493647992;
   fWeightMatrix0to1[6][3] = 0.0239479937650803;
   fWeightMatrix0to1[7][3] = -0.0533830103735144;
   fWeightMatrix0to1[8][3] = -0.0890161693273282;
   fWeightMatrix0to1[9][3] = 0.0251533161551995;
   fWeightMatrix0to1[0][4] = 0.549803454189159;
   fWeightMatrix0to1[1][4] = -0.335422511350443;
   fWeightMatrix0to1[2][4] = 0.786572723101359;
   fWeightMatrix0to1[3][4] = -0.336730167510307;
   fWeightMatrix0to1[4][4] = 0.386218318639228;
   fWeightMatrix0to1[5][4] = -2.14680352423342;
   fWeightMatrix0to1[6][4] = 0.465359864694676;
   fWeightMatrix0to1[7][4] = 2.77711297526814;
   fWeightMatrix0to1[8][4] = -2.43018052199382;
   fWeightMatrix0to1[9][4] = 2.22787421931682;
   fWeightMatrix0to1[0][5] = 0.925684971180404;
   fWeightMatrix0to1[1][5] = 0.17086096131688;
   fWeightMatrix0to1[2][5] = 1.28547915260649;
   fWeightMatrix0to1[3][5] = 4.60926193653138;
   fWeightMatrix0to1[4][5] = -9.45501510869087;
   fWeightMatrix0to1[5][5] = -0.0755731015283298;
   fWeightMatrix0to1[6][5] = -0.25046500963109;
   fWeightMatrix0to1[7][5] = -0.983501448484378;
   fWeightMatrix0to1[8][5] = 0.92176510636808;
   fWeightMatrix0to1[9][5] = 9.61384229609902;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.87440206547579;
   fWeightMatrix1to2[0][1] = -0.172584282480235;
   fWeightMatrix1to2[0][2] = -0.813566108052585;
   fWeightMatrix1to2[0][3] = -0.520829908895842;
   fWeightMatrix1to2[0][4] = 0.649131663949797;
   fWeightMatrix1to2[0][5] = -1.03855665045295;
   fWeightMatrix1to2[0][6] = 0.23845926573513;
   fWeightMatrix1to2[0][7] = -0.576755481343796;
   fWeightMatrix1to2[0][8] = 0.335420382418614;
   fWeightMatrix1to2[0][9] = -0.996485984566124;
   fWeightMatrix1to2[0][10] = 0.157127106650208;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 14;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 17;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 17;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 7;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 7;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 7;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 8;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 10;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 10;
   fMin_1[0][3] = -3.14159011841;
   fMax_1[0][3] = 3.1415309906;
   fMin_1[1][3] = -3.1415681839;
   fMax_1[1][3] = 3.14156198502;
   fMin_1[2][3] = -3.14159011841;
   fMax_1[2][3] = 3.14156198502;
   fMin_1[0][4] = -4.70970201492;
   fMax_1[0][4] = 4.74954795837;
   fMin_1[1][4] = -4.75499534607;
   fMax_1[1][4] = 4.76451778412;
   fMin_1[2][4] = -4.75499534607;
   fMax_1[2][4] = 4.76451778412;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 5;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<5;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
