// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Wed May 24 16:38:25 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva/v2/mkNtuple_v2
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,17]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,6]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,9]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.388728410006,5.07587337494]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [17.3422145844,299.92956543]
CSVv2_M                       CSVv2_M                       CSVv2_M                       CSVv2_M                                                         'F'    [0.850588262081,1]
CvsL_M                        CvsL_M                        CvsL_M                        CvsL_M                                                          'F'    [0.800013184547,0.997556328773]
BJet_Pt                       BJet_Pt                       BJet_Pt                       BJet_Pt                                                         'F'    [30.4866390228,1102.10168457]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [34.0188293457,1324.11791992]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJet_M_delta_R", "H_Mass", "CSVv2_M", "CvsL_M", "BJet_Pt", "CJet_Pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[15][10];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][15];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 10; fWeights[0] = new double[10]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.49269389968385;
   fWeightMatrix0to1[1][0] = 0.271544763782371;
   fWeightMatrix0to1[2][0] = 0.00899631042545427;
   fWeightMatrix0to1[3][0] = 1.98508041335136;
   fWeightMatrix0to1[4][0] = -0.265410084114622;
   fWeightMatrix0to1[5][0] = -2.8687413854613;
   fWeightMatrix0to1[6][0] = -0.148361195434383;
   fWeightMatrix0to1[7][0] = -0.831623749001834;
   fWeightMatrix0to1[8][0] = -6.41412572391307;
   fWeightMatrix0to1[9][0] = 0.477436715548597;
   fWeightMatrix0to1[10][0] = -1.95576899607215;
   fWeightMatrix0to1[11][0] = -0.735345841904034;
   fWeightMatrix0to1[12][0] = -0.715400320928281;
   fWeightMatrix0to1[13][0] = -0.00801455649859819;
   fWeightMatrix0to1[0][1] = -5.51149942503564;
   fWeightMatrix0to1[1][1] = -0.300910836647848;
   fWeightMatrix0to1[2][1] = 0.0376871773618707;
   fWeightMatrix0to1[3][1] = 0.405257032884365;
   fWeightMatrix0to1[4][1] = -0.19405688844112;
   fWeightMatrix0to1[5][1] = 0.332136631055836;
   fWeightMatrix0to1[6][1] = -0.102196364788614;
   fWeightMatrix0to1[7][1] = -1.13629079781147;
   fWeightMatrix0to1[8][1] = 1.00330786454909;
   fWeightMatrix0to1[9][1] = 2.22411065777397;
   fWeightMatrix0to1[10][1] = -2.71075186956714;
   fWeightMatrix0to1[11][1] = -0.9180693844646;
   fWeightMatrix0to1[12][1] = 3.14357720820232;
   fWeightMatrix0to1[13][1] = 0.101213710744888;
   fWeightMatrix0to1[0][2] = -0.820246898806608;
   fWeightMatrix0to1[1][2] = 0.0612067233629785;
   fWeightMatrix0to1[2][2] = -0.137059072593977;
   fWeightMatrix0to1[3][2] = -0.16681498739719;
   fWeightMatrix0to1[4][2] = 0.242734688296765;
   fWeightMatrix0to1[5][2] = -1.62123219937551;
   fWeightMatrix0to1[6][2] = 0.063290708514559;
   fWeightMatrix0to1[7][2] = -0.0830201099455499;
   fWeightMatrix0to1[8][2] = 0.583976794284809;
   fWeightMatrix0to1[9][2] = 1.49495303802476;
   fWeightMatrix0to1[10][2] = -2.07315906115926;
   fWeightMatrix0to1[11][2] = 0.601474010478563;
   fWeightMatrix0to1[12][2] = 0.200241015511621;
   fWeightMatrix0to1[13][2] = 0.104135109470385;
   fWeightMatrix0to1[0][3] = -2.22322651830657;
   fWeightMatrix0to1[1][3] = 1.55260639338484;
   fWeightMatrix0to1[2][3] = 0.657148465241501;
   fWeightMatrix0to1[3][3] = -0.282412844295663;
   fWeightMatrix0to1[4][3] = 0.360613562031725;
   fWeightMatrix0to1[5][3] = 2.52615072277076;
   fWeightMatrix0to1[6][3] = -0.175545351305316;
   fWeightMatrix0to1[7][3] = 4.25675157130368;
   fWeightMatrix0to1[8][3] = 0.198659182425261;
   fWeightMatrix0to1[9][3] = 1.14592579299539;
   fWeightMatrix0to1[10][3] = -0.387230067187047;
   fWeightMatrix0to1[11][3] = 0.445170506743616;
   fWeightMatrix0to1[12][3] = -3.28611188231641;
   fWeightMatrix0to1[13][3] = 0.60714441314442;
   fWeightMatrix0to1[0][4] = -1.4994790139388;
   fWeightMatrix0to1[1][4] = 0.715658252277502;
   fWeightMatrix0to1[2][4] = 9.3014468150053;
   fWeightMatrix0to1[3][4] = 0.561653159918787;
   fWeightMatrix0to1[4][4] = -0.27052560636231;
   fWeightMatrix0to1[5][4] = -0.601706330989192;
   fWeightMatrix0to1[6][4] = 5.00991131052782;
   fWeightMatrix0to1[7][4] = 0.297792627168625;
   fWeightMatrix0to1[8][4] = 0.0394843460730032;
   fWeightMatrix0to1[9][4] = 0.217186951082058;
   fWeightMatrix0to1[10][4] = 1.22044976657423;
   fWeightMatrix0to1[11][4] = -0.723032677112046;
   fWeightMatrix0to1[12][4] = 0.339032269741204;
   fWeightMatrix0to1[13][4] = -6.43988473446536;
   fWeightMatrix0to1[0][5] = -0.539525655799031;
   fWeightMatrix0to1[1][5] = -0.514190922475954;
   fWeightMatrix0to1[2][5] = -0.451436107365391;
   fWeightMatrix0to1[3][5] = -0.0907141223083069;
   fWeightMatrix0to1[4][5] = 0.0149846581543995;
   fWeightMatrix0to1[5][5] = 0.0603917128241514;
   fWeightMatrix0to1[6][5] = -0.756612715399628;
   fWeightMatrix0to1[7][5] = -0.516346054988638;
   fWeightMatrix0to1[8][5] = 0.0629575663930457;
   fWeightMatrix0to1[9][5] = -0.064645068600564;
   fWeightMatrix0to1[10][5] = 0.506869777633394;
   fWeightMatrix0to1[11][5] = 0.344528048736094;
   fWeightMatrix0to1[12][5] = 0.310644450658827;
   fWeightMatrix0to1[13][5] = 0.149954585471425;
   fWeightMatrix0to1[0][6] = 0.00376152817994292;
   fWeightMatrix0to1[1][6] = 0.181319789298505;
   fWeightMatrix0to1[2][6] = 0.390506047561357;
   fWeightMatrix0to1[3][6] = -0.0806624290882016;
   fWeightMatrix0to1[4][6] = 0.0865001833625847;
   fWeightMatrix0to1[5][6] = -0.423638347728016;
   fWeightMatrix0to1[6][6] = 0.146567679452096;
   fWeightMatrix0to1[7][6] = 0.146192917450798;
   fWeightMatrix0to1[8][6] = -0.181846034523301;
   fWeightMatrix0to1[9][6] = -0.837094516843403;
   fWeightMatrix0to1[10][6] = -1.03295229458604;
   fWeightMatrix0to1[11][6] = 0.303590845641587;
   fWeightMatrix0to1[12][6] = -0.0962141203620434;
   fWeightMatrix0to1[13][6] = -0.278391924605512;
   fWeightMatrix0to1[0][7] = -0.116059503551615;
   fWeightMatrix0to1[1][7] = -0.311400310030165;
   fWeightMatrix0to1[2][7] = -1.00147597229954;
   fWeightMatrix0to1[3][7] = -6.28391855287562;
   fWeightMatrix0to1[4][7] = 0.522318338691934;
   fWeightMatrix0to1[5][7] = -3.05049810608434;
   fWeightMatrix0to1[6][7] = -4.47407187967094;
   fWeightMatrix0to1[7][7] = 1.33826673060844;
   fWeightMatrix0to1[8][7] = 0.380902113987689;
   fWeightMatrix0to1[9][7] = -2.8223071491131;
   fWeightMatrix0to1[10][7] = 0.249748588805934;
   fWeightMatrix0to1[11][7] = -0.611613388418029;
   fWeightMatrix0to1[12][7] = -1.00277923828704;
   fWeightMatrix0to1[13][7] = 0.545911302442598;
   fWeightMatrix0to1[0][8] = -1.6284695854889;
   fWeightMatrix0to1[1][8] = 1.00663557271931;
   fWeightMatrix0to1[2][8] = 0.122771378319353;
   fWeightMatrix0to1[3][8] = 14.4581032419461;
   fWeightMatrix0to1[4][8] = 0.428840304056633;
   fWeightMatrix0to1[5][8] = -1.36934381663261;
   fWeightMatrix0to1[6][8] = -0.591582491223709;
   fWeightMatrix0to1[7][8] = -2.45767422886114;
   fWeightMatrix0to1[8][8] = 2.77030501934033;
   fWeightMatrix0to1[9][8] = -1.7740292419141;
   fWeightMatrix0to1[10][8] = -0.117148441080243;
   fWeightMatrix0to1[11][8] = 0.44579230777894;
   fWeightMatrix0to1[12][8] = -2.4395938274836;
   fWeightMatrix0to1[13][8] = 0.560258400279816;
   fWeightMatrix0to1[0][9] = -3.03213062753658;
   fWeightMatrix0to1[1][9] = 1.36364360910149;
   fWeightMatrix0to1[2][9] = 1.36128477982271;
   fWeightMatrix0to1[3][9] = 10.4374468885908;
   fWeightMatrix0to1[4][9] = 0.613409779261668;
   fWeightMatrix0to1[5][9] = -4.76213756651783;
   fWeightMatrix0to1[6][9] = -0.496800448283765;
   fWeightMatrix0to1[7][9] = -1.95757646883961;
   fWeightMatrix0to1[8][9] = -2.6013529881243;
   fWeightMatrix0to1[9][9] = -0.926979388502517;
   fWeightMatrix0to1[10][9] = 2.12362525353298;
   fWeightMatrix0to1[11][9] = -1.03254296841466;
   fWeightMatrix0to1[12][9] = 1.37048377103088;
   fWeightMatrix0to1[13][9] = -0.397050400712946;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.82929479347205;
   fWeightMatrix1to2[0][1] = -0.591922930576072;
   fWeightMatrix1to2[0][2] = -1.20647620986092;
   fWeightMatrix1to2[0][3] = -1.5205485489783;
   fWeightMatrix1to2[0][4] = 0.198479243310922;
   fWeightMatrix1to2[0][5] = 0.443580148411995;
   fWeightMatrix1to2[0][6] = 0.748041018468096;
   fWeightMatrix1to2[0][7] = 0.578128768580071;
   fWeightMatrix1to2[0][8] = 0.697106851873089;
   fWeightMatrix1to2[0][9] = -0.444067602488919;
   fWeightMatrix1to2[0][10] = -1.40744704938608;
   fWeightMatrix1to2[0][11] = -0.547808563332875;
   fWeightMatrix1to2[0][12] = 1.46270428542732;
   fWeightMatrix1to2[0][13] = -1.14995879322035;
   fWeightMatrix1to2[0][14] = 0.0976762486782554;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 12;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 17;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 17;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 9;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 8;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 9;
   fMin_1[0][3] = 0.388728410006;
   fMax_1[0][3] = 4.63860177994;
   fMin_1[1][3] = 0.404239505529;
   fMax_1[1][3] = 5.07587337494;
   fMin_1[2][3] = 0.388728410006;
   fMax_1[2][3] = 5.07587337494;
   fMin_1[0][4] = 21.2812328339;
   fMax_1[0][4] = 299.907989502;
   fMin_1[1][4] = 17.3422145844;
   fMax_1[1][4] = 299.92956543;
   fMin_1[2][4] = 17.3422145844;
   fMax_1[2][4] = 299.92956543;
   fMin_1[0][5] = 0.851404845715;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0.850588262081;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0.850588262081;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.800013184547;
   fMax_1[0][6] = 0.997556328773;
   fMin_1[1][6] = 0.800312757492;
   fMax_1[1][6] = 0.996954023838;
   fMin_1[2][6] = 0.800013184547;
   fMax_1[2][6] = 0.997556328773;
   fMin_1[0][7] = 30.8079624176;
   fMax_1[0][7] = 873.140991211;
   fMin_1[1][7] = 30.4866390228;
   fMax_1[1][7] = 1102.10168457;
   fMin_1[2][7] = 30.4866390228;
   fMax_1[2][7] = 1102.10168457;
   fMin_1[0][8] = 34.0188293457;
   fMax_1[0][8] = 1059.98620605;
   fMin_1[1][8] = 36.9922218323;
   fMax_1[1][8] = 1324.11791992;
   fMin_1[2][8] = 34.0188293457;
   fMax_1[2][8] = 1324.11791992;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
