// Class: ReadDNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : DNN::DNN
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.08/02       [395266]
Creator        : minerva1993
Date           : Wed May 24 16:56:31 2017
Host           : Linux htop.hanyang.ac.kr 2.6.32-696.el6.centos.plus.x86_64 #1 SMP Mon Apr 3 14:56:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/minerva1993/fcnc/tmva/v2/mkNtuple_v2
Training events: 60000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
Layout: "TANH|30,TANH|20,LINEAR" [Layou of the network.]
ErrorStrategy: "CROSSENTROPY" [Loss function: Mean squared error (regression) or cross entropy (binary classifcation).]
WeightInitialization: "XAVIERUNIFORM" [Weight initialization strategy]
TrainingStrategy: "LearningRate=0.01,Momentum=0.4,Repetitions=1,ConvergenceSteps=300,BatchSize=100,DropConfig=0.0+0.2+0.0,WeightDecay=0.001,Regularization=L2,TestRepetitions=5,Multithreading=True" [Defines the training strategies.]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Architecture: "STANDARD" [Which architecture to perfrom the training on.]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
NJets                         NJets                         NJets                         NJets                                                           'I'    [4,17]
NBJets_M                      NBJets_M                      NBJets_M                      NBJets_M                                                        'I'    [1,6]
NCJets_M                      NCJets_M                      NCJets_M                      NCJets_M                                                        'I'    [1,9]
BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                BJet_M_delta_R                                                  'F'    [0.388728410006,5.07587337494]
H_Mass                        H_Mass                        H_Mass                        H_Mass                                                          'F'    [17.3422145844,299.92956543]
CSVv2_M                       CSVv2_M                       CSVv2_M                       CSVv2_M                                                         'F'    [0.850588262081,1]
CvsL_M                        CvsL_M                        CvsL_M                        CvsL_M                                                          'F'    [0.800013184547,0.997556328773]
BJet_Pt                       BJet_Pt                       BJet_Pt                       BJet_Pt                                                         'F'    [30.4866390228,1102.10168457]
CJet_Pt                       CJet_Pt                       CJet_Pt                       CJet_Pt                                                         'F'    [34.0188293457,1324.11791992]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDNN : public IClassifierReader {

 public:

   // constructor
   ReadDNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadDNN" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "NJets", "NBJets_M", "NCJets_M", "BJet_M_delta_R", "H_Mass", "CSVv2_M", "CvsL_M", "BJet_Pt", "CJet_Pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.384615421295166;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.75;
      fVmin[3] = -0.9988112449646;
      fVmax[3] = 0.837623238563538;
      fVmin[4] = -0.990549385547638;
      fVmax[4] = 1.0001277923584;
      fVmin[5] = -0.954070508480072;
      fVmax[5] = 0.997079014778137;
      fVmin[6] = -0.999890148639679;
      fVmax[6] = 0.994209766387939;
      fVmin[7] = -0.999190151691437;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;

      // initialize input variable types
      fType[0] = 'I';
      fType[1] = 'I';
      fType[2] = 'I';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][9];
   double fMax_1[3][9];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadDNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadDNN::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 4;
   fMax_1[0][0] = 12;
   fMin_1[1][0] = 4;
   fMax_1[1][0] = 17;
   fMin_1[2][0] = 4;
   fMax_1[2][0] = 17;
   fMin_1[0][1] = 1;
   fMax_1[0][1] = 6;
   fMin_1[1][1] = 1;
   fMax_1[1][1] = 6;
   fMin_1[2][1] = 1;
   fMax_1[2][1] = 6;
   fMin_1[0][2] = 1;
   fMax_1[0][2] = 9;
   fMin_1[1][2] = 1;
   fMax_1[1][2] = 8;
   fMin_1[2][2] = 1;
   fMax_1[2][2] = 9;
   fMin_1[0][3] = 0.388728410006;
   fMax_1[0][3] = 4.63860177994;
   fMin_1[1][3] = 0.404239505529;
   fMax_1[1][3] = 5.07587337494;
   fMin_1[2][3] = 0.388728410006;
   fMax_1[2][3] = 5.07587337494;
   fMin_1[0][4] = 21.2812328339;
   fMax_1[0][4] = 299.907989502;
   fMin_1[1][4] = 17.3422145844;
   fMax_1[1][4] = 299.92956543;
   fMin_1[2][4] = 17.3422145844;
   fMax_1[2][4] = 299.92956543;
   fMin_1[0][5] = 0.851404845715;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0.850588262081;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0.850588262081;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.800013184547;
   fMax_1[0][6] = 0.997556328773;
   fMin_1[1][6] = 0.800312757492;
   fMax_1[1][6] = 0.996954023838;
   fMin_1[2][6] = 0.800013184547;
   fMax_1[2][6] = 0.997556328773;
   fMin_1[0][7] = 30.8079624176;
   fMax_1[0][7] = 873.140991211;
   fMin_1[1][7] = 30.4866390228;
   fMax_1[1][7] = 1102.10168457;
   fMin_1[2][7] = 30.4866390228;
   fMax_1[2][7] = 1102.10168457;
   fMin_1[0][8] = 34.0188293457;
   fMax_1[0][8] = 1059.98620605;
   fMin_1[1][8] = 36.9922218323;
   fMax_1[1][8] = 1324.11791992;
   fMin_1[2][8] = 34.0188293457;
   fMax_1[2][8] = 1324.11791992;
}

//_______________________________________________________________________
inline void ReadDNN::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 9;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<9;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadDNN::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDNN::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
